import i18next from 'i18next'
import { enabledStatusOptions } from '@/constants/module-options'
import { getSettlementCompanyOptions } from '@/module-system/core/module-option-resolvers'
import type { ModulePageConfig } from '@/types/module-page'
import { actionSet, buildMasterOverview, statusMap } from '../shared/shared'
import { masterStatusFilter } from '../shared/shared-filters'

export const customersPageConfig: ModulePageConfig = {
  key: 'customer',
  title: i18next.t('modules.pages.customer.title'),
  kicker: 'Master Data',
  description: i18next.t('modules.pages.customer.description'),
  primaryNoKey: 'customerCode',
  showGeneratedPrimaryNoOnCreate: true,
  actions: [
    ...actionSet.slice(0, 1),
    {
      key: 'manage_customer_projects',
      label: i18next.t('modules.pages.customer.manageProjects'),
      type: 'default',
    },
    ...actionSet.slice(1),
  ],
  filters: [
    {
      key: 'keyword',
      label: i18next.t('modules.filter.keyword'),
      type: 'input',
      placeholder: i18next.t('modules.pages.customer.placeholderKeyword'),
    },
    { ...masterStatusFilter },
  ],
  columns: [
    {
      title: i18next.t('modules.pages.customer.colCustomerCode'),
      dataIndex: 'customerCode',
      width: 140,
    },
    {
      title: i18next.t('modules.pages.customer.colCustomerName'),
      dataIndex: 'customerName',
      width: 180,
    },
    {
      title: i18next.t('modules.pages.customer.colProjectName'),
      dataIndex: 'projectNames',
      width: 320,
    },
    {
      title: i18next.t('modules.pages.customer.colContactName'),
      dataIndex: 'contactName',
      width: 110,
    },
    {
      title: i18next.t('modules.pages.customer.colContactPhone'),
      dataIndex: 'contactPhone',
      width: 140,
    },
    {
      title: i18next.t('modules.pages.customer.colCity'),
      dataIndex: 'city',
      width: 120,
    },
    {
      title: i18next.t('modules.pages.customer.colSettlementMode'),
      dataIndex: 'settlementMode',
      width: 110,
    },
    {
      title: i18next.t('modules.pages.customer.colDefaultSettlementCompany'),
      dataIndex: 'defaultSettlementCompanyName',
      width: 180,
    },
    {
      title: i18next.t('modules.columns.status'),
      dataIndex: 'status',
      width: 100,
      type: 'status',
      align: 'center',
    },
  ],
  defaultHiddenColumnKeys: ['contactPhone', 'city'],
  detailFields: [
    {
      label: i18next.t('modules.pages.customer.colCustomerCode'),
      key: 'customerCode',
    },
    {
      label: i18next.t('modules.pages.customer.colCustomerName'),
      key: 'customerName',
    },
    {
      label: i18next.t('modules.pages.customer.colProjectName'),
      key: 'projectNames',
    },
    {
      label: i18next.t('modules.pages.customer.colContactName'),
      key: 'contactName',
    },
    {
      label: i18next.t('modules.pages.customer.colContactPhone'),
      key: 'contactPhone',
    },
    { label: i18next.t('modules.pages.customer.colCity'), key: 'city' },
    {
      label: i18next.t('modules.pages.customer.colSettlementMode'),
      key: 'settlementMode',
    },
    {
      label: i18next.t('modules.pages.customer.colDefaultSettlementCompany'),
      key: 'defaultSettlementCompanyName',
    },
    {
      label: i18next.t('modules.columns.status'),
      key: 'status',
      type: 'status',
    },
    { label: i18next.t('modules.columns.remark'), key: 'remark' },
  ],
  detailColumnCount: 4,
  formFields: [
    {
      key: 'customerCode',
      label: i18next.t('modules.pages.customer.colCustomerCode'),
      type: 'input',
      required: true,
      disabled: true,
      placeholder: i18next.t(
        'modules.editorWorkspace.autoGeneratedPlaceholder',
      ),
      row: 1,
    },
    {
      key: 'customerName',
      label: i18next.t('modules.pages.customer.colCustomerName'),
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'contactName',
      label: i18next.t('modules.pages.customer.colContactName'),
      type: 'input',
      row: 2,
    },
    {
      key: 'contactPhone',
      label: i18next.t('modules.pages.customer.colContactPhone'),
      type: 'input',
      row: 2,
    },
    {
      key: 'city',
      label: i18next.t('modules.pages.customer.colCity'),
      type: 'input',
      row: 2,
    },
    {
      key: 'settlementMode',
      label: i18next.t('modules.pages.customer.colSettlementMode'),
      type: 'select',
      options: [
        {
          label: i18next.t('modules.pages.customer.settlementCash'),
          value: '现结',
        },
        {
          label: i18next.t('modules.pages.customer.settlementMonthly'),
          value: '月结',
        },
        {
          label: i18next.t('modules.pages.customer.settlementCredit'),
          value: '授信',
        },
      ],
      row: 2,
    },
    {
      key: 'defaultSettlementCompanyId',
      label: i18next.t('modules.pages.customer.colDefaultSettlementCompany'),
      type: 'select',
      required: true,
      options: getSettlementCompanyOptions,
      row: 3,
    },
    {
      key: 'status',
      label: i18next.t('modules.columns.status'),
      type: 'select',
      defaultValue: '正常',
      options: enabledStatusOptions,
      row: 3,
    },
    {
      key: 'remark',
      label: i18next.t('modules.columns.remark'),
      type: 'textarea',
      row: 4,
      fullRow: true,
    },
  ],
  data: [],
  buildOverview: (rows) => buildMasterOverview(rows),
  statusMap,
  rowHighlightStatuses: ['禁用'],
  saveFields: {
    scalar: [
      'customerCode',
      'customerName',
      'contactName',
      'contactPhone',
      'city',
      'settlementMode',
      'defaultSettlementCompanyId',
      'defaultSettlementCompanyName',
      'status',
      'remark',
    ],
  },
}
