import i18next from 'i18next'
import { enabledStatusOptions } from '@/constants/module-options'
import {
  getCustomerOptions,
  getSettlementCompanyOptions,
} from '@/module-system/core/module-option-resolvers'
import type { ModulePageConfig } from '@/types/module-page'
import { actionSet, buildMasterOverview, statusMap } from '../shared/shared'
import { masterStatusFilter } from '../shared/shared-filters'
import { resolveProjectCustomerDisplay } from './project-page-utils'

const customerFieldOptions = () =>
  getCustomerOptions().map((option) => ({
    label: option.customerName || option.label,
    value: option.id,
    customerCode: option.customerCode,
    customerName: option.customerName,
    settlementCompanyId: option.defaultSettlementCompanyId,
    settlementCompanyName: option.defaultSettlementCompanyName,
  }))

const projectPageConfig: ModulePageConfig = {
  key: 'project',
  title: i18next.t('modules.pages.project.title'),
  kicker: 'Master Data',
  description: i18next.t('modules.pages.project.description'),
  primaryNoKey: 'projectCode',
  showGeneratedPrimaryNoOnCreate: true,
  actions: actionSet,
  filters: [
    {
      key: 'keyword',
      label: i18next.t('modules.filter.keyword'),
      type: 'input',
      placeholder: i18next.t('modules.pages.project.placeholderKeyword'),
    },
    {
      key: 'customerId',
      label: i18next.t('modules.pages.project.customer'),
      type: 'select',
      options: getCustomerOptions,
    },
    { ...masterStatusFilter },
  ],
  columns: [
    {
      title: i18next.t('modules.pages.project.projectCode'),
      dataIndex: 'projectCode',
      width: 140,
    },
    {
      title: i18next.t('modules.pages.project.projectName'),
      dataIndex: 'projectName',
      width: 200,
    },
    {
      title: i18next.t('modules.pages.project.projectNameAbbr'),
      dataIndex: 'projectNameAbbr',
      width: 140,
    },
    {
      title: i18next.t('modules.pages.project.customer'),
      dataIndex: 'customerCode',
      width: 180,
      render: (_value, record) =>
        resolveProjectCustomerDisplay(record, getCustomerOptions()),
    },
    {
      title: i18next.t('modules.pages.project.settlementCompany'),
      dataIndex: 'settlementCompanyName',
      width: 180,
    },
    {
      title: i18next.t('modules.pages.project.projectManager'),
      dataIndex: 'projectManager',
      width: 140,
    },
    {
      title: i18next.t('modules.pages.project.projectAddress'),
      dataIndex: 'projectAddress',
      width: 220,
    },
    {
      title: i18next.t('modules.columns.status'),
      dataIndex: 'status',
      width: 100,
      type: 'status',
      align: 'center',
    },
    {
      title: i18next.t('modules.columns.remark'),
      dataIndex: 'remark',
      width: 180,
    },
  ],
  defaultHiddenColumnKeys: ['projectNameAbbr', 'projectAddress', 'remark'],
  detailFields: [
    {
      label: i18next.t('modules.pages.project.projectCode'),
      key: 'projectCode',
    },
    {
      label: i18next.t('modules.pages.project.projectName'),
      key: 'projectName',
    },
    {
      label: i18next.t('modules.pages.project.projectNameAbbr'),
      key: 'projectNameAbbr',
    },
    {
      label: i18next.t('modules.pages.project.customer'),
      key: 'customerCode',
    },
    {
      label: i18next.t('modules.pages.project.settlementCompany'),
      key: 'settlementCompanyName',
    },
    {
      label: i18next.t('modules.pages.project.projectManager'),
      key: 'projectManager',
    },
    {
      label: i18next.t('modules.pages.project.projectAddress'),
      key: 'projectAddress',
    },
    {
      label: i18next.t('modules.columns.status'),
      key: 'status',
      type: 'status',
    },
    { label: i18next.t('modules.columns.remark'), key: 'remark' },
  ],
  detailColumnCount: 4,
  formFields: [
    {
      key: 'projectCode',
      label: i18next.t('modules.pages.project.projectCode'),
      type: 'input',
      required: true,
      disabled: true,
      placeholder: i18next.t(
        'modules.editorWorkspace.autoGeneratedPlaceholder',
      ),
      row: 1,
    },
    {
      key: 'projectName',
      label: i18next.t('modules.pages.project.projectName'),
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'projectNameAbbr',
      label: i18next.t('modules.pages.project.projectNameAbbr'),
      type: 'input',
      row: 2,
    },
    {
      key: 'customerId',
      label: i18next.t('modules.pages.project.customer'),
      type: 'select',
      required: true,
      options: customerFieldOptions,
      masterOptionRequirements: { customers: true },
      row: 2,
    },
    {
      key: 'settlementCompanyId',
      label: i18next.t('modules.pages.project.settlementCompany'),
      type: 'select',
      required: true,
      options: getSettlementCompanyOptions,
      masterOptionRequirements: { settlementCompanies: true },
      row: 3,
    },
    {
      key: 'projectManager',
      label: i18next.t('modules.pages.project.projectManager'),
      type: 'input',
      row: 3,
    },
    {
      key: 'projectAddress',
      label: i18next.t('modules.pages.project.projectAddress'),
      type: 'input',
      row: 4,
      fullRow: true,
    },
    {
      key: 'status',
      label: i18next.t('modules.columns.status'),
      type: 'select',
      defaultValue: '正常',
      options: enabledStatusOptions,
      row: 5,
    },
    {
      key: 'remark',
      label: i18next.t('modules.columns.remark'),
      type: 'textarea',
      row: 6,
      fullRow: true,
    },
  ],
  data: [],
  buildOverview: (rows) => buildMasterOverview(rows),
  statusMap,
  rowHighlightStatuses: ['禁用'],
  saveFields: {
    scalar: [
      'projectCode',
      'projectName',
      'projectNameAbbr',
      'projectAddress',
      'projectManager',
      'customerId',
      'customerCode',
      'settlementCompanyId',
      'settlementCompanyName',
      'status',
      'remark',
    ],
  },
}

export const masterProjectPageConfigs: Record<string, ModulePageConfig> = {
  [projectPageConfig.key]: projectPageConfig,
}
