import {
  AccountBookOutlined,
  BankOutlined,
  CarOutlined,
  DatabaseOutlined,
  FileDoneOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  InboxOutlined,
  ProfileOutlined,
  ShopOutlined,
  SwapOutlined,
  TeamOutlined,
} from '@ant-design/icons'
import type { TFunction } from 'i18next'
import type { DashboardSummary } from '@/api/dashboard'
import type { WorkflowSection } from '@/views/dashboard/dashboard-view-types'

export function buildWorkflowSections(
  t: TFunction,
  summary?: DashboardSummary,
): WorkflowSection[] {
  return [
    {
      key: 'master',
      title: t('common.masterData'),
      description: t('common.masterDataDesc'),
      accent: '#0f766e',
      nodes: [
        {
          key: 'material',
          title: t('dashboard.flow.material.title'),
          path: '/material',
          icon: DatabaseOutlined,
          tone: '#1677ff',
          hint: t('dashboard.flow.material.hint'),
          metric: t('dashboard.flow.material.metric', { count: summary?.materialCount ?? 0 }),
        },
        {
          key: 'supplier',
          title: t('dashboard.flow.supplier.title'),
          path: '/supplier',
          icon: ShopOutlined,
          tone: '#52c41a',
          hint: t('dashboard.flow.supplier.hint'),
          metric: t('dashboard.flow.supplier.metric', { count: summary?.supplierCount ?? 0 }),
        },
        {
          key: 'customer',
          title: t('dashboard.flow.customer.title'),
          path: '/customer',
          icon: TeamOutlined,
          tone: '#fa8c16',
          hint: t('dashboard.flow.customer.hint'),
          metric: t('dashboard.flow.customer.metric', { count: summary?.customerCount ?? 0 }),
        },
        {
          key: 'warehouse',
          title: t('dashboard.flow.warehouse.title'),
          path: '/warehouse',
          icon: BankOutlined,
          tone: '#13c2c2',
          hint: t('dashboard.flow.warehouse.hint'),
        },
      ],
    },
    {
      key: 'purchase',
      title: t('common.purchaseChain'),
      description: t('common.purchaseChainDesc'),
      accent: '#2563eb',
      nodes: [
        {
          key: 'purchase-contract',
          title: t('dashboard.flow.purchaseContract.title'),
          path: '/purchase-contract',
          icon: ProfileOutlined,
          tone: '#2563eb',
          hint: t('dashboard.flow.purchaseContract.hint'),
        },
        {
          key: 'purchase-order',
          title: t('dashboard.flow.purchaseOrder.title'),
          path: '/purchase-order',
          icon: ProfileOutlined,
          tone: '#1677ff',
          hint: t('dashboard.flow.purchaseOrder.hint'),
        },
        {
          key: 'purchase-inbound',
          title: t('dashboard.flow.purchaseInbound.title'),
          path: '/purchase-inbound',
          icon: InboxOutlined,
          tone: '#2f54eb',
          hint: t('dashboard.flow.purchaseInbound.hint'),
        },
        {
          key: 'supplier-statement',
          title: t('dashboard.flow.supplierStatement.title'),
          path: '/supplier-statement',
          icon: FileSearchOutlined,
          tone: '#1d39c4',
          hint: t('dashboard.flow.supplierStatement.hint'),
        },
        {
          key: 'payment',
          title: t('dashboard.flow.payment.title'),
          path: '/payment',
          icon: AccountBookOutlined,
          tone: '#10239e',
          hint: t('dashboard.flow.payment.hint'),
        },
      ],
    },
    {
      key: 'sales',
      title: t('common.salesChain'),
      description: t('common.salesChainDesc'),
      accent: '#d97706',
      nodes: [
        {
          key: 'sales-contract',
          title: t('dashboard.flow.salesContract.title'),
          path: '/sales-contract',
          icon: FileDoneOutlined,
          tone: '#fa8c16',
          hint: t('dashboard.flow.salesContract.hint'),
        },
        {
          key: 'sales-order',
          title: t('dashboard.flow.salesOrder.title'),
          path: '/sales-order',
          icon: FileDoneOutlined,
          tone: '#faad14',
          hint: t('dashboard.flow.salesOrder.hint'),
        },
        {
          key: 'sales-outbound',
          title: t('dashboard.flow.salesOutbound.title'),
          path: '/sales-outbound',
          icon: SwapOutlined,
          tone: '#d48806',
          hint: t('dashboard.flow.salesOutbound.hint'),
        },
        {
          key: 'customer-statement',
          title: t('dashboard.flow.customerStatement.title'),
          path: '/customer-statement',
          icon: FileTextOutlined,
          tone: '#ad6800',
          hint: t('dashboard.flow.customerStatement.hint'),
        },
        {
          key: 'receipt',
          title: t('dashboard.flow.receipt.title'),
          path: '/receipt',
          icon: AccountBookOutlined,
          tone: '#874d00',
          hint: t('dashboard.flow.receipt.hint'),
        },
      ],
    },
    {
      key: 'freight',
      title: t('common.logisticsChain'),
      description: t('common.logisticsChainDesc'),
      accent: '#7c3aed',
      nodes: [
        {
          key: 'carrier',
          title: t('dashboard.flow.carrier.title'),
          path: '/carrier',
          icon: CarOutlined,
          tone: '#722ed1',
          hint: t('dashboard.flow.carrier.hint'),
        },
        {
          key: 'freight-bill',
          title: t('dashboard.flow.freightBill.title'),
          path: '/freight-bill',
          icon: CarOutlined,
          tone: '#9254de',
          hint: t('dashboard.flow.freightBill.hint'),
        },
        {
          key: 'freight-statement',
          title: t('dashboard.flow.freightStatement.title'),
          path: '/freight-statement',
          icon: FileSearchOutlined,
          tone: '#531dab',
          hint: t('dashboard.flow.freightStatement.hint'),
        },
      ],
    },
  ]
}
