import i18next from 'i18next'
import {
  statementStatusOptions,
  withDeletedDocumentStatus,
} from '@/constants/module-options'
import {
  getCustomerOptions,
  getCustomerProjectOptions,
  getSettlementCompanyOptions,
} from '@/module-system/core/module-option-resolvers'
import type {
  ModuleItemColumnConfig,
  ModulePageConfig,
} from '@/types/module-page'
import { BILL_STATUS_LABEL, CUSTOMER_NAME_LABEL } from '../shared/filter-labels'
import { SETTLEMENT_COMPANY_LABEL } from '../shared/settlement-company'
import { statusMap } from '../shared/shared'
import { resolveModuleItemColumnConfig } from '../shared/shared-item-column-utils'
import {
  buildCustomerStatementOverview,
  buildCustomerStatementParentFilters,
  mapSalesOrderToCustomerStatementDraft,
  transformSalesOrderItemsToCustomerStatementItems,
  validateCustomerStatementBeforeOpen,
  validateCustomerStatementParentImport,
} from './customer-statement-rules'

// 客户对账单明细列：金额类字段右对齐展示。
const customerStatementItemColumnConfig: ModuleItemColumnConfig = {
  include: [
    'brand',
    'category',
    'material',
    'spec',
    'length',
    'quantity',
    'quantityUnit',
    'pieceWeightTon',
    'weightTon',
    'unitPrice',
    'amount',
  ],
  overrides: {
    brand: { width: 86 },
    category: { width: 72 },
    material: { width: 82 },
    spec: { width: 100 },
    length: { width: 70 },
    quantity: { width: 76 },
    quantityUnit: { width: 76 },
    pieceWeightTon: { width: 92, align: 'right' },
    weightTon: { align: 'right' },
    unitPrice: { width: 88, align: 'right' },
    amount: { width: 100, align: 'right' },
  },
  requiredFieldKeys: [
    'brand',
    'category',
    'material',
    'spec',
    'quantity',
    'pieceWeightTon',
    'weightTon',
    'unitPrice',
    'amount',
  ],
  projections: {
    saveResult: [
      'brand',
      'material',
      'spec',
      'length',
      'quantity',
      'weightTon',
      'unitPrice',
      'amount',
    ],
  },
}
const customerStatementItemColumnOutputs = resolveModuleItemColumnConfig(
  customerStatementItemColumnConfig,
)

export const customerStatementPageConfig: ModulePageConfig = {
  key: 'customer-statement',
  title: i18next.t('modules.pages.customerStatement.customerStatement'),
  kicker: 'Statements',
  description: i18next.t(
    'modules.pages.customerStatement.customerStatementDesc',
  ),
  primaryNoKey: 'statementNo',
  hideKeywordFilter: true,
  actions: [
    {
      key: 'generate_statement',
      label: i18next.t('modules.pages.customerStatement.generateStatement'),
      type: 'primary',
    },
    {
      key: 'view_customer_summary',
      label: i18next.t('modules.pages.customerStatement.viewCustomerSummary'),
      type: 'default',
    },
  ],
  filters: [
    {
      key: 'customerId',
      label: CUSTOMER_NAME_LABEL,
      type: 'select',
      options: getCustomerOptions,
      resetKeysOnChange: ['projectId'],
    },
    {
      key: 'projectId',
      label: i18next.t('modules.pages.customerStatement.project'),
      type: 'select',
      options: getCustomerProjectOptions,
    },
    {
      key: 'settlementCompanyId',
      label: SETTLEMENT_COMPANY_LABEL,
      type: 'select',
      options: getSettlementCompanyOptions,
    },
    {
      key: 'status',
      label: BILL_STATUS_LABEL,
      type: 'select',
      options: withDeletedDocumentStatus(statementStatusOptions),
    },
    {
      key: 'endDate',
      label: i18next.t('modules.pages.customerStatement.period'),
      type: 'dateRange',
      row: 2,
    },
  ],
  columns: [
    {
      title: i18next.t('modules.pages.customerStatement.statementNo'),
      dataIndex: 'statementNo',
      width: 170,
    },
    {
      title: i18next.t('modules.pages.customerStatement.customerCode'),
      dataIndex: 'customerCode',
      width: 130,
    },
    {
      title: i18next.t('modules.pages.customerStatement.customer'),
      dataIndex: 'customerName',
      width: 140,
    },
    {
      title: '关联销售订单',
      dataIndex: 'sourceOrderNos',
      width: 180,
    },
    {
      title: i18next.t('modules.pages.customerStatement.project'),
      dataIndex: 'projectName',
      width: 180,
    },
    {
      title: SETTLEMENT_COMPANY_LABEL,
      dataIndex: 'settlementCompanyName',
      width: 160,
    },
    {
      title: i18next.t('modules.pages.customerStatement.startDate'),
      dataIndex: 'startDate',
      width: 120,
      type: 'date',
    },
    {
      title: i18next.t('modules.pages.customerStatement.endDate'),
      dataIndex: 'endDate',
      width: 120,
      type: 'date',
    },
    {
      title: i18next.t('modules.pages.customerStatement.salesAmount'),
      dataIndex: 'salesAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: i18next.t('modules.pages.customerStatement.receiptAmount'),
      dataIndex: 'receiptAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: i18next.t('modules.pages.customerStatement.closingBalance'),
      dataIndex: 'closingAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: i18next.t('modules.pages.customerStatement.status'),
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
    {
      title: i18next.t('modules.columns.remark'),
      dataIndex: 'remark',
      width: 180,
    },
  ],
  defaultHiddenColumnKeys: ['customerCode', 'remark'],
  detailFields: [
    {
      label: i18next.t('modules.pages.customerStatement.statementNo'),
      key: 'statementNo',
    },
    {
      label: i18next.t('modules.pages.customerStatement.customer'),
      key: 'customerName',
    },
    {
      label: '关联销售订单',
      key: 'sourceOrderNos',
    },
    {
      label: i18next.t('modules.pages.customerStatement.customerCode'),
      key: 'customerCode',
    },
    {
      label: i18next.t('modules.pages.customerStatement.project'),
      key: 'projectName',
    },
    {
      label: SETTLEMENT_COMPANY_LABEL,
      key: 'settlementCompanyName',
    },
    {
      label: i18next.t('modules.pages.customerStatement.startDate'),
      key: 'startDate',
      type: 'date',
    },
    {
      label: i18next.t('modules.pages.customerStatement.endDate'),
      key: 'endDate',
      type: 'date',
    },
    {
      label: i18next.t('modules.pages.customerStatement.salesAmount'),
      key: 'salesAmount',
      type: 'amount',
    },
    {
      label: i18next.t('modules.pages.customerStatement.receiptAmount'),
      key: 'receiptAmount',
      type: 'amount',
    },
    {
      label: i18next.t('modules.pages.customerStatement.closingBalance'),
      key: 'closingAmount',
      type: 'amount',
    },
    {
      label: i18next.t('modules.pages.customerStatement.status'),
      key: 'status',
      type: 'status',
    },
    {
      label: i18next.t('modules.pages.customerStatement.remark'),
      key: 'remark',
    },
  ],
  formFields: [
    {
      key: 'customerId',
      label: i18next.t('modules.pages.customerStatement.customer'),
      type: 'select',
      required: true,
      options: getCustomerOptions,
      row: 1,
    },
    {
      key: 'statementNo',
      label: i18next.t('modules.pages.customerStatement.statementNo'),
      type: 'input',
      required: true,
      disabled: true,
      row: 1,
    },
    {
      key: 'sourceOrderNos',
      label: '关联销售订单',
      type: 'input',
      disabled: true,
      row: 1,
    },
    {
      key: 'customerCode',
      label: i18next.t('modules.pages.customerStatement.customerCode'),
      type: 'input',
      disabled: true,
      row: 1,
    },
    {
      key: 'settlementCompanyId',
      label: SETTLEMENT_COMPANY_LABEL,
      type: 'select',
      options: getSettlementCompanyOptions,
      disabled: true,
      row: 1,
    },
    {
      key: 'projectId',
      label: i18next.t('modules.pages.customerStatement.project'),
      type: 'select',
      required: true,
      options: getCustomerProjectOptions,
      row: 2,
    },
    {
      key: 'startDate',
      label: i18next.t('modules.pages.customerStatement.startDate'),
      type: 'date',
      required: true,
      disabled: true,
      row: 2,
    },
    {
      key: 'endDate',
      label: i18next.t('modules.pages.customerStatement.endDate'),
      type: 'date',
      required: true,
      disabled: true,
      row: 2,
    },
    {
      key: 'salesAmount',
      label: i18next.t('modules.pages.customerStatement.salesAmount'),
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 3,
    },
    {
      key: 'closingAmount',
      label: i18next.t('modules.pages.customerStatement.closingBalance'),
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 3,
    },
    {
      key: 'status',
      label: i18next.t('modules.pages.customerStatement.status'),
      type: 'select',
      defaultValue: '待确认',
      options: statementStatusOptions,
      disabled: true,
      row: 3,
    },
    {
      key: 'remark',
      label: i18next.t('modules.pages.customerStatement.remark'),
      type: 'textarea',
      row: 4,
      fullRow: true,
    },
  ],
  saveFields: {
    scalar: [
      'statementNo',
      'sourceOrderNos',
      'customerId',
      'customerCode',
      'customerName',
      'projectId',
      'projectName',
      'settlementCompanyId',
      'settlementCompanyName',
      'startDate',
      'endDate',
      'salesAmount',
      'receiptAmount',
      'closingAmount',
      'status',
      'remark',
    ],
    lineItem: ['id', 'sourceSalesOrderItemId'],
  },
  parentImport: {
    parentModuleKey: 'sales-order',
    label: '销售订单',
    parentFieldKey: 'sourceOrderNos',
    parentDisplayFieldKey: 'orderNo',
    candidateStatementModuleKey: 'customer-statement',
    buttonText: '选择销售订单生成明细',
    allowMultipleSelection: true,
    buildParentFilters: buildCustomerStatementParentFilters,
    validateBeforeOpen: validateCustomerStatementBeforeOpen,
    mapParentToDraft: mapSalesOrderToCustomerStatementDraft,
    validateParentImport: validateCustomerStatementParentImport,
    transformItems: transformSalesOrderItemsToCustomerStatementItems,
  },
  ...customerStatementItemColumnOutputs,
  data: [],
  buildOverview: buildCustomerStatementOverview,
  statusMap,
  rowHighlightStatuses: ['待确认'],
}
