import i18next from 'i18next'
import {
  buildValueOptions,
  getSupplierOptions,
} from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import { BILL_STATUS_LABEL, SUPPLIER_NAME_LABEL } from '../shared/filter-labels'
import {
  buildFinanceOverview,
  compactInvoiceReceiptItemColumns,
  statusMap,
} from '../shared/shared'

export const invoiceReceiptPageConfig: ModulePageConfig = {
  key: 'invoice-receipt',
  title: i18next.t('modules.pages.invoiceReceipt.invoiceReceipt'),
  kicker: 'Finance',
  description: i18next.t('modules.pages.invoiceReceipt.invoiceReceiptDesc'),
  primaryNoKey: 'receiveNo',
  actions: [
    {
      key: 'create_invoice_receipt',
      label: i18next.t('modules.pages.invoiceReceipt.createInvoiceReceipt'),
      type: 'primary',
    },
  ],
  filters: [
    {
      key: 'supplierName',
      label: SUPPLIER_NAME_LABEL,
      type: 'select',
      options: getSupplierOptions,
    },
    {
      key: 'status',
      label: BILL_STATUS_LABEL,
      type: 'select',
      options: buildValueOptions('草稿', '已收票'),
    },
    {
      key: 'invoiceDate',
      label: i18next.t('modules.pages.invoiceReceipt.invoiceDate'),
      type: 'dateRange',
    },
  ],
  columns: [
    {
      title: i18next.t('modules.pages.invoiceReceipt.receiveNo'),
      dataIndex: 'receiveNo',
      width: 170,
    },
    {
      title: i18next.t('modules.pages.invoiceReceipt.relatedPurchaseOrder'),
      dataIndex: 'sourcePurchaseOrderNos',
      width: 180,
    },
    {
      title: i18next.t('modules.pages.invoiceReceipt.invoiceNo'),
      dataIndex: 'invoiceNo',
      width: 150,
    },
    {
      title: i18next.t('modules.pages.invoiceReceipt.supplier'),
      dataIndex: 'supplierName',
      width: 150,
    },
    {
      title: i18next.t('modules.pages.invoiceReceipt.invoiceTitle'),
      dataIndex: 'invoiceTitle',
      width: 170,
    },
    {
      title: '结算主体',
      dataIndex: 'settlementCompanyName',
      width: 160,
    },
    {
      title: i18next.t('modules.pages.invoiceReceipt.invoiceDate'),
      dataIndex: 'invoiceDate',
      width: 120,
      type: 'date',
    },
    {
      title: i18next.t('modules.pages.invoiceReceipt.invoiceType'),
      dataIndex: 'invoiceType',
      width: 120,
    },
    {
      title: i18next.t('modules.pages.invoiceReceipt.amount'),
      dataIndex: 'amount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: i18next.t('modules.pages.invoiceReceipt.taxAmount'),
      dataIndex: 'taxAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: i18next.t('modules.pages.invoiceReceipt.status'),
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
    {
      title: i18next.t('modules.pages.invoiceReceipt.operator'),
      dataIndex: 'operatorName',
      width: 120,
    },
    {
      title: i18next.t('modules.pages.invoiceReceipt.remark'),
      dataIndex: 'remark',
      width: 180,
    },
  ],
  defaultHiddenColumnKeys: [
    'sourcePurchaseOrderNos',
    'invoiceTitle',
    'taxAmount',
    'operatorName',
    'remark',
  ],
  detailFields: [
    {
      label: i18next.t('modules.pages.invoiceReceipt.receiveNo'),
      key: 'receiveNo',
    },
    {
      label: i18next.t('modules.pages.invoiceReceipt.relatedPurchaseOrder'),
      key: 'sourcePurchaseOrderNos',
    },
    {
      label: i18next.t('modules.pages.invoiceReceipt.invoiceNo'),
      key: 'invoiceNo',
    },
    {
      label: i18next.t('modules.pages.invoiceReceipt.supplier'),
      key: 'supplierName',
    },
    {
      label: i18next.t('modules.pages.invoiceReceipt.invoiceTitle'),
      key: 'invoiceTitle',
    },
    {
      label: i18next.t('modules.pages.invoiceReceipt.invoiceDate'),
      key: 'invoiceDate',
      type: 'date',
    },
    {
      label: i18next.t('modules.pages.invoiceReceipt.invoiceType'),
      key: 'invoiceType',
    },
    {
      label: i18next.t('modules.pages.invoiceReceipt.amount'),
      key: 'amount',
      type: 'amount',
    },
    {
      label: i18next.t('modules.pages.invoiceReceipt.taxAmount'),
      key: 'taxAmount',
      type: 'amount',
    },
    {
      label: i18next.t('modules.pages.invoiceReceipt.status'),
      key: 'status',
      type: 'status',
    },
    {
      label: i18next.t('modules.pages.invoiceReceipt.operator'),
      key: 'operatorName',
    },
    { label: i18next.t('modules.pages.invoiceReceipt.remark'), key: 'remark' },
  ],
  formFields: [
    {
      key: 'receiveNo',
      label: i18next.t('modules.pages.invoiceReceipt.receiveNo'),
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'sourcePurchaseOrderNos',
      label: i18next.t('modules.pages.invoiceReceipt.relatedPurchaseOrder'),
      type: 'input',
      disabled: true,
      placeholder: i18next.t(
        'modules.pages.invoiceReceipt.importFromPurchaseOrders',
      ),
      row: 1,
    },
    {
      key: 'invoiceNo',
      label: i18next.t('modules.pages.invoiceReceipt.invoiceNo'),
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'supplierName',
      label: i18next.t('modules.pages.invoiceReceipt.supplier'),
      type: 'select',
      required: true,
      options: getSupplierOptions,
      row: 1,
    },
    {
      key: 'invoiceTitle',
      label: i18next.t('modules.pages.invoiceReceipt.invoiceTitle'),
      type: 'input',
      required: true,
      row: 2,
    },
    {
      key: 'invoiceDate',
      label: i18next.t('modules.pages.invoiceReceipt.invoiceDate'),
      type: 'date',
      required: true,
      row: 2,
    },
    {
      key: 'invoiceType',
      label: i18next.t('modules.pages.invoiceReceipt.invoiceType'),
      type: 'select',
      required: true,
      options: buildValueOptions('增值税专票', '增值税普票'),
      row: 2,
    },
    {
      key: 'amount',
      label: i18next.t('modules.pages.invoiceReceipt.amount'),
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 2,
    },
    {
      key: 'taxRate',
      label: i18next.t('modules.pages.invoiceReceipt.taxRate'),
      type: 'number',
      min: 0,
      precision: 4,
      defaultValue: 0,
      disabled: true,
      row: 3,
    },
    {
      key: 'taxAmount',
      label: i18next.t('modules.pages.invoiceReceipt.taxAmount'),
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 3,
    },
    {
      key: 'status',
      label: i18next.t('modules.pages.invoiceReceipt.status'),
      type: 'select',
      defaultValue: '草稿',
      options: buildValueOptions('草稿', '已收票'),
      row: 3,
    },
    {
      key: 'operatorName',
      label: i18next.t('modules.pages.invoiceReceipt.operator'),
      type: 'input',
      required: true,
      row: 3,
    },
    {
      key: 'remark',
      label: i18next.t('modules.pages.invoiceReceipt.remark'),
      type: 'textarea',
      row: 4,
      fullRow: true,
    },
  ],
  parentImport: {
    parentModuleKey: 'purchase-order',
    label: i18next.t('modules.pages.invoiceReceipt.parentPurchaseOrder'),
    parentFieldKey: 'sourcePurchaseOrderNos',
    parentDisplayFieldKey: 'orderNo',
    buttonText: i18next.t(
      'modules.pages.invoiceReceipt.importPurchaseOrderItems',
    ),
    mapParentToDraft: (parentRecord) => ({
      supplierCode: parentRecord.supplierCode || '',
      supplierName: parentRecord.supplierName || '',
      settlementCompanyId: parentRecord.settlementCompanyId,
      settlementCompanyName: parentRecord.settlementCompanyName || '',
      invoiceTitle: parentRecord.settlementCompanyName || '',
    }),
    transformItems: (parentRecord) =>
      Array.isArray(parentRecord.items)
        ? parentRecord.items.map((item, index) => ({
            ...item,
            id: `invoice-receipt-item-${parentRecord.id}-${index + 1}`,
            sourceNo: parentRecord.orderNo || '',
            sourcePurchaseOrderItemId: item.id,
            _maxImportWeightTon: item.weightTon,
            _maxImportAmount: item.amount,
            maxImportQuantity: item.quantity,
            quantity: item.quantity,
          }))
        : [],
  },
  itemColumns: compactInvoiceReceiptItemColumns,
  saveFields: {
    scalar: [
      'receiveNo',
      'invoiceNo',
      'sourcePurchaseOrderNos',
      'supplierCode',
      'supplierName',
      'invoiceTitle',
      'invoiceDate',
      'invoiceType',
      'amount',
      'taxAmount',
      'status',
      'operatorName',
      'remark',
    ],
    lineItem: [
      'sourceNo',
      'sourcePurchaseOrderItemId',
      'materialCode',
      'brand',
      'category',
      'material',
      'spec',
      'length',
      'unit',
      'warehouseName',
      'batchNo',
      'quantity',
      'quantityUnit',
      'pieceWeightTon',
      'piecesPerBundle',
      'weightTon',
      'unitPrice',
      'amount',
    ],
  },
  data: [],
  buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
  statusMap,
  rowHighlightStatuses: ['草稿'],
}
