import { describe, expect, it, vi } from 'vitest'

vi.mock('i18next', () => ({
  default: { t: (key: string) => key },
}))

vi.mock('@/constants/module-options', () => ({
  getCarrierOptions: vi.fn(() => [{ label: '承运商A', value: '承运商A' }]),
  getCustomerOptions: vi.fn(() => [{ label: '客户A', value: '客户A' }]),
  getSettlementCompanyOptions: vi.fn(() => [
    { label: '主体A', value: '9', companyName: '主体A' },
  ]),
  getSupplierOptions: vi.fn(() => [{ label: '供应商A', value: '供应商A' }]),
}))

import {
  getCarrierOptions,
  getCustomerOptions,
  getSettlementCompanyOptions,
  getSupplierOptions,
} from '@/constants/module-options'
import { ledgerAdjustmentPageConfig } from './ledger-adjustment-page'

describe('ledgerAdjustmentPageConfig', () => {
  it('has correct key and primary number field', () => {
    expect(ledgerAdjustmentPageConfig.key).toBe('ledger-adjustment')
    expect(ledgerAdjustmentPageConfig.primaryNoKey).toBe('adjustmentNo')
  })

  it('defines ledger adjustment filters', () => {
    expect(
      ledgerAdjustmentPageConfig.filters?.map((field) => field.key),
    ).toEqual([
      'direction',
      'counterpartyType',
      'settlementCompanyId',
      'status',
      'adjustmentDate',
    ])
  })

  it('shows counterparty code and settlement company in the list and details', () => {
    const columnKeys = ledgerAdjustmentPageConfig.columns.map(
      (column) => column.dataIndex,
    )
    const detailKeys = ledgerAdjustmentPageConfig.detailFields.map(
      (field) => field.key,
    )

    expect(columnKeys).toContain('counterpartyCode')
    expect(columnKeys).toContain('settlementCompanyName')
    expect(detailKeys).toContain('settlementCompanyName')
  })

  it('keeps ledger adjustment scalar save fields', () => {
    expect(ledgerAdjustmentPageConfig.saveFields?.scalar).toEqual([
      'adjustmentNo',
      'direction',
      'counterpartyType',
      'counterpartyCode',
      'counterpartyName',
      'settlementCompanyId',
      'settlementCompanyName',
      'projectId',
      'projectName',
      'adjustmentDate',
      'amount',
      'adjustmentType',
      'effect',
      'status',
      'operatorName',
      'remark',
    ])
  })

  it('builds finance overview from amount', () => {
    const overview = ledgerAdjustmentPageConfig.buildOverview?.([
      { amount: 100 },
      { amount: 20 },
    ])

    expect(Array.isArray(overview)).toBe(true)
  })

  it('optimizes ledger adjustment editor inputs', () => {
    const fields = Object.fromEntries(
      (ledgerAdjustmentPageConfig.formFields || []).map((field) => [
        field.key,
        field,
      ]),
    )

    expect(fields.adjustmentNo.disabled).toBe(true)
    expect(fields.adjustmentNo.placeholder).toBe(
      'modules.pages.ledgerAdjustment.autoGeneratedPlaceholder',
    )
    expect(fields.direction.defaultValue).toBe('应收')
    expect(fields.direction.allowClear).toBe(false)
    expect(fields.counterpartyType.defaultValue).toBe('客户')
    expect(fields.counterpartyType.allowClear).toBe(false)
    expect(fields.counterpartyName.type).toBe('select')
    expect(fields.counterpartyName.allowClear).toBe(false)
    expect(fields.settlementCompanyId).toEqual(
      expect.objectContaining({
        type: 'select',
        required: true,
        allowClear: false,
        options: getSettlementCompanyOptions,
      }),
    )
    expect(fields.adjustmentDate.dateFormat).toBe('YYYY-MM-DD')
    expect(fields.adjustmentDate.showTime).toBe(false)
    expect(fields.adjustmentDate.allowClear).toBe(false)
    expect(fields.amount.defaultValue).toBeUndefined()
    expect(fields.amount.step).toBe(0.01)
    expect(fields.amount.controls).toBe(false)
    expect(fields.adjustmentType.defaultValue).toBe('其他调整')
    expect(fields.effect.defaultValue).toBe('减少余额')
    expect(fields.status.allowClear).toBe(false)
    expect(fields.operatorName.disabled).toBe(true)
    expect(fields.remark.maxLength).toBe(500)
    expect(fields.remark.showCount).toBe(true)
  })

  it('resolves counterparty options by counterparty type', () => {
    const counterpartyName = ledgerAdjustmentPageConfig.formFields?.find(
      (field) => field.key === 'counterpartyName',
    )
    expect(typeof counterpartyName?.options).toBe('function')

    const resolveOptions = counterpartyName!.options as (form?: any) => any[]
    expect(resolveOptions({ counterpartyType: '客户' })).toEqual([
      { label: '客户A', value: '客户A' },
    ])
    expect(getCustomerOptions).toHaveBeenCalled()

    expect(resolveOptions({ counterpartyType: '供应商' })).toEqual([
      { label: '供应商A', value: '供应商A' },
    ])
    expect(getSupplierOptions).toHaveBeenCalled()

    expect(resolveOptions({ counterpartyType: '物流商' })).toEqual([
      { label: '承运商A', value: '承运商A' },
    ])
    expect(getCarrierOptions).toHaveBeenCalled()
  })
})
