/**
 * 比价 demo 静态 mock 数据（取自 2026-09-09 下午杭州行情真实解密结果）。
 * 后续接入真实 API 时由 GET /api/v2.0/material-price-matches 提供。
 */

export type PriceCompareRow = {
  id: string
  brand: string
  factory: string
  breed: '螺纹钢' | '盘螺'
  material: string
  spec: number
  matchedSpec: string
  singleSpecPrice: boolean
  length: '9米' | '12米' | '-'
  netPrice: number
}

export const DEMO_QUOTE_DATE = '2026-09-09'
export const DEMO_PERIOD = '下午'

export const PERIOD_OPTIONS = [
  { label: '上午', value: '上午' },
  { label: '中午', value: '中午' },
  { label: '下午', value: '下午' },
]

export const BREED_OPTIONS = [
  { label: '全部品类', value: '全部' },
  { label: '螺纹钢', value: '螺纹钢' },
  { label: '盘螺', value: '盘螺' },
]

export const SPEC_OPTIONS = [6, 8, 10, 12, 14, 16, 18, 20, 22, 25, 28, 32]

export const LENGTH_OPTIONS = [
  { label: '全部长度', value: '全部' },
  { label: '9米', value: '9米' },
  { label: '12米', value: '12米' },
  { label: '盘螺', value: '-' },
]

export const PRICE_COMPARE_ROWS: PriceCompareRow[] = [
  {
    id: '1',
    brand: '中天',
    factory: '中天',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 12,
    matchedSpec: 'Φ12-14',
    singleSpecPrice: false,
    length: '9米',
    netPrice: 3280,
  },
  {
    id: '2',
    brand: '中天',
    factory: '中天',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 12,
    matchedSpec: 'Φ12-14',
    singleSpecPrice: false,
    length: '12米',
    netPrice: 3310,
  },
  {
    id: '3',
    brand: '中天',
    factory: '中天',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 16,
    matchedSpec: 'Φ16-25',
    singleSpecPrice: false,
    length: '9米',
    netPrice: 3240,
  },
  {
    id: '4',
    brand: '中天',
    factory: '中天',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 20,
    matchedSpec: 'Φ20',
    singleSpecPrice: false,
    length: '9米',
    netPrice: 3260,
  },
  {
    id: '5',
    brand: '中天',
    factory: '中天',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 25,
    matchedSpec: 'Φ16-25',
    singleSpecPrice: true,
    length: '12米',
    netPrice: 3300,
  },
  {
    id: '6',
    brand: '中天',
    factory: '中天',
    breed: '盘螺',
    material: 'HRB400E',
    spec: 8,
    matchedSpec: 'Φ8-10',
    singleSpecPrice: false,
    length: '-',
    netPrice: 3510,
  },
  {
    id: '7',
    brand: '中天',
    factory: '中天',
    breed: '盘螺',
    material: 'HRB400E',
    spec: 10,
    matchedSpec: 'Φ8-10',
    singleSpecPrice: true,
    length: '-',
    netPrice: 3560,
  },
  {
    id: '8',
    brand: '万泰',
    factory: '浙江万泰',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 14,
    matchedSpec: 'Φ14',
    singleSpecPrice: false,
    length: '9米',
    netPrice: 3210,
  },
  {
    id: '9',
    brand: '万泰',
    factory: '浙江万泰',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 14,
    matchedSpec: 'Φ14',
    singleSpecPrice: false,
    length: '12米',
    netPrice: 3240,
  },
  {
    id: '10',
    brand: '万泰',
    factory: '浙江万泰',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 18,
    matchedSpec: 'Φ16-25',
    singleSpecPrice: false,
    length: '9米',
    netPrice: 3230,
  },
  {
    id: '11',
    brand: '万泰',
    factory: '浙江万泰',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 22,
    matchedSpec: 'Φ16-25',
    singleSpecPrice: false,
    length: '12米',
    netPrice: 3280,
  },
  {
    id: '12',
    brand: '中新',
    factory: '中新钢铁',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 16,
    matchedSpec: 'Φ16',
    singleSpecPrice: false,
    length: '9米',
    netPrice: 3170,
  },
  {
    id: '13',
    brand: '中新',
    factory: '中新钢铁',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 16,
    matchedSpec: 'Φ16',
    singleSpecPrice: false,
    length: '12米',
    netPrice: 3200,
  },
  {
    id: '14',
    brand: '中杭',
    factory: '今胜中杭',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 18,
    matchedSpec: 'Φ18',
    singleSpecPrice: false,
    length: '9米',
    netPrice: 3190,
  },
  {
    id: '15',
    brand: '中杭',
    factory: '今胜中杭',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 20,
    matchedSpec: 'Φ20',
    singleSpecPrice: false,
    length: '12米',
    netPrice: 3250,
  },
  {
    id: '16',
    brand: '芜湖富鑫',
    factory: '安徽富鑫',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 12,
    matchedSpec: 'Φ12-14',
    singleSpecPrice: false,
    length: '9米',
    netPrice: 3150,
  },
  {
    id: '17',
    brand: '芜湖富鑫',
    factory: '安徽富鑫',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 14,
    matchedSpec: 'Φ12-14',
    singleSpecPrice: false,
    length: '12米',
    netPrice: 3190,
  },
  {
    id: '18',
    brand: '江苏镔鑫',
    factory: '江苏镔鑫',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 25,
    matchedSpec: 'Φ25',
    singleSpecPrice: false,
    length: '9米',
    netPrice: 3220,
  },
  {
    id: '19',
    brand: '永钢',
    factory: '永钢',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 20,
    matchedSpec: 'Φ20',
    singleSpecPrice: false,
    length: '9米',
    netPrice: 3300,
  },
  {
    id: '20',
    brand: '永钢',
    factory: '永钢',
    breed: '螺纹钢',
    material: 'HRB400E',
    spec: 28,
    matchedSpec: 'Φ28-32',
    singleSpecPrice: false,
    length: '12米',
    netPrice: 3340,
  },
  {
    id: '21',
    brand: '萍钢',
    factory: '萍钢',
    breed: '盘螺',
    material: 'HRB400E',
    spec: 8,
    matchedSpec: 'Φ8-10',
    singleSpecPrice: false,
    length: '-',
    netPrice: 3470,
  },
  {
    id: '22',
    brand: '新梅鹿',
    factory: '隆鑫/新梅鹿',
    breed: '盘螺',
    material: 'HRB400E',
    spec: 10,
    matchedSpec: 'Φ8-10',
    singleSpecPrice: false,
    length: '-',
    netPrice: 3490,
  },
]

export const BRAND_OPTIONS: string[] = [
  ...new Set(PRICE_COMPARE_ROWS.map((row) => row.brand)),
]
