import type {
  ModuleColumnDefinition,
  ModuleLineItem,
  ModuleOverviewItem,
  ModulePageConfig,
  ModuleRecord,
  ModuleStatusMeta,
} from '@/types/module-page'

function formatInteger(value: number) {
  return String(value)
}

function formatAmount(value: number) {
  return value.toFixed(2)
}

function formatWeight(value: number) {
  return value.toFixed(3)
}

function sumBy(rows: ModuleRecord[], key: string) {
  return rows.reduce((sum, row) => sum + Number(row[key] || 0), 0)
}

function buildAmountWeightOverview(
  rows: ModuleRecord[],
  amountKey: string,
  weightKey = 'totalWeight',
): ModuleOverviewItem[] {
  return [
    { label: '记录数', value: formatInteger(rows.length) },
    { label: '吨位合计', value: formatWeight(sumBy(rows, weightKey)) },
    { label: '金额合计', value: formatAmount(sumBy(rows, amountKey)) },
  ]
}

function buildStatementOverview(
  rows: ModuleRecord[],
  businessKey: string,
  paidKey: string,
  balanceKey: string,
): ModuleOverviewItem[] {
  return [
    { label: '对账单数', value: formatInteger(rows.length) },
    { label: '本期金额', value: formatAmount(sumBy(rows, businessKey)) },
    { label: '已结金额', value: formatAmount(sumBy(rows, paidKey)) },
    { label: '余额', value: formatAmount(sumBy(rows, balanceKey)) },
  ]
}

function buildFinanceOverview(
  rows: ModuleRecord[],
  amountKey: string,
): ModuleOverviewItem[] {
  return [
    { label: '单据数', value: formatInteger(rows.length) },
    { label: '金额合计', value: formatAmount(sumBy(rows, amountKey)) },
  ]
}

function buildMasterOverview(
  rows: ModuleRecord[],
  activeKey = 'status',
  activeValue = '正常',
): ModuleOverviewItem[] {
  return [
    { label: '主数据数', value: formatInteger(rows.length) },
    { label: '正常数', value: formatInteger(rows.filter((row) => row[activeKey] === activeValue).length) },
  ]
}

const materialInfoColumns: ModuleColumnDefinition[] = [
  { title: '商品编码', dataIndex: 'materialCode', width: 140 },
  { title: '品牌', dataIndex: 'brand', width: 110 },
  { title: '类别', dataIndex: 'category', width: 100 },
  { title: '材质', dataIndex: 'material', width: 120 },
  { title: '规格', dataIndex: 'spec', width: 100 },
  { title: '长度', dataIndex: 'length', width: 100 },
  { title: '单位', dataIndex: 'unit', width: 80 },
  { title: '件重/吨', dataIndex: 'pieceWeightTon', width: 110, align: 'right', type: 'weight' },
  { title: '每件支数', dataIndex: 'piecesPerBundle', width: 110, align: 'right', type: 'count' },
]

const orderItemColumns: ModuleColumnDefinition[] = [
  ...materialInfoColumns.slice(0, 7),
  { title: '数量', dataIndex: 'quantity', width: 100, align: 'right', type: 'count' },
  ...materialInfoColumns.slice(7),
  { title: '吨位', dataIndex: 'weightTon', width: 100, align: 'right', type: 'weight' },
  { title: '单价', dataIndex: 'unitPrice', width: 110, align: 'right', type: 'amount' },
  { title: '金额', dataIndex: 'amount', width: 110, align: 'right', type: 'amount' },
]

function applyCompactItemLayout(
  columns: ModuleColumnDefinition[],
  widthMap: Record<string, number>,
  hiddenKeys: string[] = [],
) {
  const hiddenKeySet = new Set(hiddenKeys)
  return columns
    .filter((column) => !hiddenKeySet.has(column.dataIndex))
    .map((column) => (widthMap[column.dataIndex] ? { ...column, width: widthMap[column.dataIndex] } : column))
}

const compactTradeItemWidthMap: Record<string, number> = {
  materialCode: 170,
  brand: 80,
  category: 64,
  material: 96,
  spec: 80,
  length: 80,
  unit: 80,
  quantity: 80,
  pieceWeightTon: 80,
  weightTon: 96,
  unitPrice: 96,
  amount: 96,
}

const compactFreightItemWidthMap: Record<string, number> = {
  sourceNo: 160,
  customerName: 120,
  projectName: 160,
  materialCode: 170,
  materialName: 120,
  brand: 80,
  category: 64,
  material: 96,
  spec: 80,
  length: 80,
  quantity: 80,
  pieceWeightTon: 80,
  weightTon: 96,
  warehouseName: 96,
  batchNo: 120,
}

const compactOrderItemColumns = applyCompactItemLayout(
  orderItemColumns,
  compactTradeItemWidthMap,
  ['piecesPerBundle'],
)

const freightItemColumns: ModuleColumnDefinition[] = [
  { title: '出库单号', dataIndex: 'sourceNo', width: 160 },
  { title: '客户', dataIndex: 'customerName', width: 140 },
  { title: '项目', dataIndex: 'projectName', width: 180 },
  { title: '商品编码', dataIndex: 'materialCode', width: 140 },
  { title: '商品名称', dataIndex: 'materialName', width: 140 },
  { title: '品牌', dataIndex: 'brand', width: 110 },
  { title: '类别', dataIndex: 'category', width: 100 },
  { title: '材质', dataIndex: 'material', width: 120 },
  { title: '规格', dataIndex: 'spec', width: 100 },
  { title: '长度', dataIndex: 'length', width: 100 },
  { title: '数量', dataIndex: 'quantity', width: 100, align: 'right', type: 'count' },
  { title: '件重/吨', dataIndex: 'pieceWeightTon', width: 110, align: 'right', type: 'weight' },
  { title: '每件支数', dataIndex: 'piecesPerBundle', width: 110, align: 'right', type: 'count' },
  { title: '批号', dataIndex: 'batchNo', width: 140 },
  { title: '吨位', dataIndex: 'weightTon', width: 100, align: 'right', type: 'weight' },
  { title: '仓库', dataIndex: 'warehouseName', width: 120 },
]

const compactFreightItemColumns = applyCompactItemLayout(
  freightItemColumns,
  compactFreightItemWidthMap,
  ['piecesPerBundle'],
)

const statusMap: Record<string, ModuleStatusMeta> = {
  草稿: { text: '草稿', color: 'default' },
  完成采购: { text: '完成采购', color: 'success' },
  完成入库: { text: '完成入库', color: 'success' },
  完成销售: { text: '完成销售', color: 'success' },
  价格核准: { text: '价格核准', color: 'success' },
  待核准: { text: '待核准', color: 'warning' },
  已核准: { text: '已核准', color: 'success' },
  未审核: { text: '未审核', color: 'warning' },
  已审核: { text: '已审核', color: 'success' },
  部分入库: { text: '部分入库', color: 'processing' },
  部分出库: { text: '部分出库', color: 'processing' },
  已完成: { text: '已完成', color: 'success' },
  已送达: { text: '已送达', color: 'success' },
  未送达: { text: '未送达', color: 'default' },
  待确认: { text: '待确认', color: 'warning' },
  已确认: { text: '已确认', color: 'success' },
  待审核: { text: '待审核', color: 'warning' },
  已签署: { text: '已签署', color: 'success' },
  未签署: { text: '未签署', color: 'default' },
  已收款: { text: '已收款', color: 'success' },
  已付款: { text: '已付款', color: 'success' },
  部分结清: { text: '部分结清', color: 'processing' },
  执行中: { text: '执行中', color: 'processing' },
  已归档: { text: '已归档', color: 'success' },
  正常: { text: '正常', color: 'success' },
  禁用: { text: '禁用', color: 'warning' },
}

const actionSet = [
  { label: '新增', type: 'primary' as const },
  { label: '导出', type: 'default' as const },
]

function cloneRecord<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T
}

function buildLineItemId(prefix: string, index: number) {
  return `${prefix}-${Date.now()}-${index + 1}`
}

function cloneLineItems(items: unknown, prefix: string): ModuleLineItem[] {
  if (!Array.isArray(items)) {
    return []
  }

  return cloneRecord(items).map((item: ModuleLineItem, index: number) => ({
    ...item,
    id: buildLineItemId(prefix, index),
  }))
}

function transformFreightItems(parentRecord: ModuleRecord): ModuleLineItem[] {
  return cloneLineItems(parentRecord.items, 'freight-item').map((item, index) => ({
    id: item.id || buildLineItemId('freight-item', index),
    sourceNo: parentRecord.outboundNo || '',
    customerName: parentRecord.customerName || '',
    projectName: parentRecord.projectName || '',
    materialCode: item.materialCode || '',
    materialName: item.materialName || '',
    brand: item.brand || '',
    category: item.category || '',
    material: item.material || '',
    spec: item.spec || '',
    length: item.length || '',
    pieceWeightTon: item.pieceWeightTon || 0,
    piecesPerBundle: item.piecesPerBundle || 0,
    batchNo: `${parentRecord.outboundNo || 'OUT'}-${String(index + 1).padStart(2, '0')}`,
    quantity: item.quantity || 0,
    weightTon: item.weightTon || 0,
    warehouseName: parentRecord.warehouseName || '',
  }))
}

export const businessPageConfigs: Record<string, ModulePageConfig> = {
  materials: {
    key: 'materials',
    title: '商品资料',
    kicker: 'Master Data',
    description: '根据前面沉淀的商品字段生成主数据页面，先用 RESTful mock API 驱动列表，后续再接真实商品接口。',
    primaryNoKey: 'materialCode',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '商品编码 / 品牌 / 规格' },
      { key: 'category', label: '类别', type: 'select', options: [
        { label: '螺纹钢', value: '螺纹钢' },
        { label: '盘螺', value: '盘螺' },
        { label: '线材', value: '线材' },
      ] },
      { key: 'material', label: '材质', type: 'select', options: [
        { label: 'HRB400', value: 'HRB400' },
        { label: 'HRB500', value: 'HRB500' },
      ] },
    ],
    columns: [
      { title: '商品编码', dataIndex: 'materialCode', width: 150 },
      { title: '品牌', dataIndex: 'brand', width: 120 },
      { title: '材质', dataIndex: 'material', width: 120 },
      { title: '类别', dataIndex: 'category', width: 110 },
      { title: '规格', dataIndex: 'spec', width: 100 },
      { title: '长度', dataIndex: 'length', width: 100 },
      { title: '单位', dataIndex: 'unit', width: 90 },
      { title: '件重/吨', dataIndex: 'pieceWeightTon', width: 110, align: 'right', type: 'weight' },
      { title: '每件支数', dataIndex: 'piecesPerBundle', width: 110, align: 'right', type: 'count' },
      { title: '单价', dataIndex: 'unitPrice', width: 100, align: 'right', type: 'amount' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '商品编码', key: 'materialCode' },
      { label: '品牌', key: 'brand' },
      { label: '材质', key: 'material' },
      { label: '类别', key: 'category' },
      { label: '规格', key: 'spec' },
      { label: '长度', key: 'length' },
      { label: '单位', key: 'unit' },
      { label: '件重/吨', key: 'pieceWeightTon', type: 'weight' },
      { label: '每件支数', key: 'piecesPerBundle', type: 'count' },
      { label: '单价', key: 'unitPrice', type: 'amount' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'materialCode', label: '商品编码', type: 'input', required: true },
      { key: 'brand', label: '品牌', type: 'input', required: true },
      { key: 'material', label: '材质', type: 'select', required: true, options: [
        { label: 'HRB400', value: 'HRB400' },
        { label: 'HRB500', value: 'HRB500' },
      ] },
      { key: 'category', label: '类别', type: 'select', required: true, options: [
        { label: '螺纹钢', value: '螺纹钢' },
        { label: '盘螺', value: '盘螺' },
        { label: '线材', value: '线材' },
      ] },
      { key: 'spec', label: '规格', type: 'input', required: true },
      { key: 'length', label: '长度', type: 'input', required: true },
      { key: 'unit', label: '单位', type: 'input', required: true },
      { key: 'pieceWeightTon', label: '件重/吨', type: 'number', required: true, min: 0, precision: 3, defaultValue: 0 },
      { key: 'piecesPerBundle', label: '每件支数', type: 'number', required: true, min: 0, precision: 0, defaultValue: 0 },
      { key: 'unitPrice', label: '单价', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '商品数', value: formatInteger(rows.length) },
      { label: '理算品类', value: formatInteger(rows.filter((row) => row.category === '螺纹钢').length) },
      { label: '过磅品类', value: formatInteger(rows.filter((row) => row.category !== '螺纹钢').length) },
    ],
  },
  suppliers: {
    key: 'suppliers',
    title: '供应商资料',
    kicker: 'Master Data',
    description: '供应商主数据统一维护基础档案、联系人和合作状态，供采购与对账页面复用。',
    primaryNoKey: 'supplierCode',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '供应商编码 / 名称 / 联系人' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
    ],
    columns: [
      { title: '供应商编码', dataIndex: 'supplierCode', width: 140 },
      { title: '供应商名称', dataIndex: 'supplierName', width: 180 },
      { title: '联系人', dataIndex: 'contactName', width: 110 },
      { title: '联系电话', dataIndex: 'contactPhone', width: 140 },
      { title: '所在城市', dataIndex: 'city', width: 120 },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '供应商编码', key: 'supplierCode' },
      { label: '供应商名称', key: 'supplierName' },
      { label: '联系人', key: 'contactName' },
      { label: '联系电话', key: 'contactPhone' },
      { label: '所在城市', key: 'city' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'supplierCode', label: '供应商编码', type: 'input', required: true },
      { key: 'supplierName', label: '供应商名称', type: 'input', required: true },
      { key: 'contactName', label: '联系人', type: 'input', required: true },
      { key: 'contactPhone', label: '联系电话', type: 'input', required: true },
      { key: 'city', label: '所在城市', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  customers: {
    key: 'customers',
    title: '客户资料',
    kicker: 'Master Data',
    description: '客户主数据统一维护客户档案、项目偏好、结算方式和合作状态，供销售与对账页面复用。',
    primaryNoKey: 'customerCode',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '客户编码 / 名称 / 联系人' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
    ],
    columns: [
      { title: '客户编码', dataIndex: 'customerCode', width: 140 },
      { title: '客户名称', dataIndex: 'customerName', width: 180 },
      { title: '联系人', dataIndex: 'contactName', width: 110 },
      { title: '联系电话', dataIndex: 'contactPhone', width: 140 },
      { title: '所在城市', dataIndex: 'city', width: 120 },
      { title: '结算方式', dataIndex: 'settlementMode', width: 110 },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '客户编码', key: 'customerCode' },
      { label: '客户名称', key: 'customerName' },
      { label: '联系人', key: 'contactName' },
      { label: '联系电话', key: 'contactPhone' },
      { label: '所在城市', key: 'city' },
      { label: '结算方式', key: 'settlementMode' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'customerCode', label: '客户编码', type: 'input', required: true },
      { key: 'customerName', label: '客户名称', type: 'input', required: true },
      { key: 'contactName', label: '联系人', type: 'input', required: true },
      { key: 'contactPhone', label: '联系电话', type: 'input', required: true },
      { key: 'city', label: '所在城市', type: 'input', required: true },
      { key: 'settlementMode', label: '结算方式', type: 'select', required: true, options: [
        { label: '现结', value: '现结' },
        { label: '月结', value: '月结' },
        { label: '授信', value: '授信' },
      ] },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  carriers: {
    key: 'carriers',
    title: '物流方资料',
    kicker: 'Master Data',
    description: '物流方主数据统一维护承运商档案、车型和合作状态，供物流单与物流对账复用。',
    primaryNoKey: 'carrierCode',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '物流方编码 / 名称 / 联系人' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
    ],
    columns: [
      { title: '物流方编码', dataIndex: 'carrierCode', width: 140 },
      { title: '物流方名称', dataIndex: 'carrierName', width: 180 },
      { title: '联系人', dataIndex: 'contactName', width: 110 },
      { title: '联系电话', dataIndex: 'contactPhone', width: 140 },
      { title: '常用车型', dataIndex: 'vehicleType', width: 120 },
      { title: '计费模式', dataIndex: 'priceMode', width: 100, align: 'center' },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '物流方编码', key: 'carrierCode' },
      { label: '物流方名称', key: 'carrierName' },
      { label: '联系人', key: 'contactName' },
      { label: '联系电话', key: 'contactPhone' },
      { label: '常用车型', key: 'vehicleType' },
      { label: '计费模式', key: 'priceMode' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'carrierCode', label: '物流方编码', type: 'input', required: true },
      { key: 'carrierName', label: '物流方名称', type: 'input', required: true },
      { key: 'contactName', label: '联系人', type: 'input', required: true },
      { key: 'contactPhone', label: '联系电话', type: 'input', required: true },
      { key: 'vehicleType', label: '常用车型', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  warehouses: {
    key: 'warehouses',
    title: '仓库资料',
    kicker: 'Master Data',
    description: '仓库主数据统一维护仓库编码、仓库名称、仓库类型、联系人和启用状态，供采购入库、销售出库和物流单页面复用。',
    primaryNoKey: 'warehouseCode',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '仓库编码 / 名称 / 联系人' },
      { key: 'warehouseType', label: '仓库类型', type: 'select', options: [
        { label: '自有仓', value: '自有仓' },
        { label: '合作仓', value: '合作仓' },
        { label: '中转仓', value: '中转仓' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
    ],
    columns: [
      { title: '仓库编码', dataIndex: 'warehouseCode', width: 140 },
      { title: '仓库名称', dataIndex: 'warehouseName', width: 160 },
      { title: '仓库类型', dataIndex: 'warehouseType', width: 110 },
      { title: '联系人', dataIndex: 'contactName', width: 110 },
      { title: '联系电话', dataIndex: 'contactPhone', width: 140 },
      { title: '仓库地址', dataIndex: 'address', width: 240 },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '仓库编码', key: 'warehouseCode' },
      { label: '仓库名称', key: 'warehouseName' },
      { label: '仓库类型', key: 'warehouseType' },
      { label: '联系人', key: 'contactName' },
      { label: '联系电话', key: 'contactPhone' },
      { label: '仓库地址', key: 'address' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'warehouseCode', label: '仓库编码', type: 'input', required: true },
      { key: 'warehouseName', label: '仓库名称', type: 'input', required: true },
      { key: 'warehouseType', label: '仓库类型', type: 'select', required: true, options: [
        { label: '自有仓', value: '自有仓' },
        { label: '合作仓', value: '合作仓' },
        { label: '中转仓', value: '中转仓' },
      ] },
      { key: 'contactName', label: '联系人', type: 'input', required: true },
      { key: 'contactPhone', label: '联系电话', type: 'input', required: true },
      { key: 'address', label: '仓库地址', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  'purchase-orders': {
    key: 'purchase-orders',
    title: '采购订单',
    kicker: 'Purchase',
    description: '采购订单按文档字段展示，先交付标准列表、筛选、概览和明细，页面数据通过 RESTful API 返回。',
    primaryNoKey: 'orderNo',
    hidePageHeader: true,
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '单据编号', type: 'input', placeholder: '输入采购订单号' },
      { key: 'supplierName', label: '供应商', type: 'select', options: [
        { label: '江苏沙钢', value: '江苏沙钢' },
        { label: '中天钢铁', value: '中天钢铁' },
        { label: '永锋钢铁', value: '永锋钢铁' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '已审核', value: '已审核' },
        { label: '完成采购', value: '完成采购' },
      ] },
      { key: 'orderDate', label: '订单日期', type: 'dateRange' },
    ],
    columns: [
      { title: '订单编号', dataIndex: 'orderNo', width: 160 },
      { title: '供应商', dataIndex: 'supplierName', width: 140 },
      { title: '采购员', dataIndex: 'buyerName', width: 110 },
      { title: '订单日期', dataIndex: 'orderDate', width: 120, type: 'date' },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 120 },
    ],
    detailFields: [
      { label: '订单编号', key: 'orderNo' },
      { label: '供应商', key: 'supplierName' },
      { label: '订单日期', key: 'orderDate', type: 'date' },
      { label: '采购员', key: 'buyerName' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'orderNo', label: '订单编号', type: 'input', required: true },
      { key: 'supplierName', label: '供应商', type: 'select', required: true, options: [
        { label: '江苏沙钢', value: '江苏沙钢' },
        { label: '中天钢铁', value: '中天钢铁' },
        { label: '永锋钢铁', value: '永锋钢铁' },
      ] },
      { key: 'orderDate', label: '订单日期', type: 'date', required: true },
      { key: 'remark', label: '备注', type: 'input' },
    ],
    itemColumns: compactOrderItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'purchase-inbounds': {
    key: 'purchase-inbounds',
    title: '采购入库',
    kicker: 'Purchase',
    description: '采购入库页面承接采购订单，展示入库仓库、批号、吨位和金额，适合作为后续库存和供应商对账入口。',
    primaryNoKey: 'inboundNo',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '入库单号', type: 'input', placeholder: '输入采购入库单号' },
      { key: 'supplierName', label: '供应商', type: 'select', options: [
        { label: '江苏沙钢', value: '江苏沙钢' },
        { label: '中天钢铁', value: '中天钢铁' },
        { label: '永锋钢铁', value: '永锋钢铁' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '已审核', value: '已审核' },
        { label: '完成入库', value: '完成入库' },
      ] },
      { key: 'inboundDate', label: '入库日期', type: 'dateRange' },
    ],
    columns: [
      { title: '入库单号', dataIndex: 'inboundNo', width: 160 },
      { title: '关联订单', dataIndex: 'purchaseOrderNo', width: 160 },
      { title: '供应商', dataIndex: 'supplierName', width: 140 },
      { title: '仓库', dataIndex: 'warehouseName', width: 120 },
      { title: '入库日期', dataIndex: 'inboundDate', width: 120, type: 'date' },
      { title: '结算方式', dataIndex: 'settlementMode', width: 110 },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '入库单号', key: 'inboundNo' },
      { label: '关联订单', key: 'purchaseOrderNo' },
      { label: '供应商', key: 'supplierName' },
      { label: '仓库', key: 'warehouseName' },
      { label: '入库日期', key: 'inboundDate', type: 'date' },
      { label: '结算方式', key: 'settlementMode' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'inboundNo', label: '入库单号', type: 'input', required: true },
      { key: 'purchaseOrderNo', label: '关联订单', type: 'input', disabled: true, placeholder: '通过上级单据导入' },
      { key: 'supplierName', label: '供应商', type: 'select', required: true, options: [
        { label: '江苏沙钢', value: '江苏沙钢' },
        { label: '中天钢铁', value: '中天钢铁' },
        { label: '永锋钢铁', value: '永锋钢铁' },
      ] },
      { key: 'warehouseName', label: '仓库', type: 'select', required: true, options: [
        { label: '一号库', value: '一号库' },
        { label: '二号库', value: '二号库' },
      ] },
      { key: 'inboundDate', label: '入库日期', type: 'date', required: true },
      { key: 'settlementMode', label: '结算方式', type: 'select', required: true, options: [
        { label: '理算', value: '理算' },
        { label: '过磅', value: '过磅' },
      ] },
      { key: 'remark', label: '备注', type: 'input' },
    ],
    parentImport: {
      parentModuleKey: 'purchase-orders',
      label: '上级采购订单',
      parentFieldKey: 'purchaseOrderNo',
      parentDisplayFieldKey: 'orderNo',
      buttonText: '导入采购订单明细',
      enforceUniqueRelation: true,
      mapParentToDraft: (parentRecord) => ({
        supplierName: parentRecord.supplierName || '',
      }),
      transformItems: (parentRecord) => cloneLineItems(parentRecord.items, 'purchase-inbound-item'),
    },
    itemColumns: compactOrderItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'sales-orders': {
    key: 'sales-orders',
    title: '销售订单',
    kicker: 'Sales',
    description: '销售订单围绕客户、项目和商品明细展开，页面默认展示完整业务字段，保持录入和查看口径一致。',
    primaryNoKey: 'orderNo',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '订单编号', type: 'input', placeholder: '输入销售订单号' },
      { key: 'customerName', label: '客户', type: 'select', options: [
        { label: '中建八局', value: '中建八局' },
        { label: '上海城建', value: '上海城建' },
        { label: '中铁建工', value: '中铁建工' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '已审核', value: '已审核' },
        { label: '完成销售', value: '完成销售' },
      ] },
      { key: 'orderDate', label: '订单日期', type: 'dateRange' },
    ],
    columns: [
      { title: '订单编号', dataIndex: 'orderNo', width: 160 },
      { title: '关联入库单', dataIndex: 'purchaseInboundNo', width: 180 },
      { title: '客户', dataIndex: 'customerName', width: 140 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '销售员', dataIndex: 'salesName', width: 110 },
      { title: '订单日期', dataIndex: 'orderDate', width: 120, type: 'date' },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '订单编号', key: 'orderNo' },
      { label: '关联入库单', key: 'purchaseInboundNo' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '销售员', key: 'salesName' },
      { label: '订单日期', key: 'orderDate', type: 'date' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'orderNo', label: '订单编号', type: 'input', required: true },
      { key: 'purchaseInboundNo', label: '关联入库单', type: 'input', disabled: true, placeholder: '通过采购入库导入，可追加多个单号' },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: [
        { label: '中建八局', value: '中建八局' },
        { label: '上海城建', value: '上海城建' },
        { label: '中铁建工', value: '中铁建工' },
      ] },
      { key: 'projectName', label: '项目', type: 'input', required: true },
      { key: 'orderDate', label: '订单日期', type: 'date', required: true },
      { key: 'salesName', label: '销售员', type: 'input', required: true },
      { key: 'remark', label: '备注', type: 'input' },
    ],
    parentImport: {
      parentModuleKey: 'purchase-inbounds',
      label: '上级采购入库单',
      parentFieldKey: 'purchaseInboundNo',
      parentDisplayFieldKey: 'inboundNo',
      buttonText: '导入采购入库明细',
      enforceUniqueRelation: true,
      transformItems: (parentRecord) => cloneLineItems(parentRecord.items, 'sales-order-item'),
    },
    itemColumns: compactOrderItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'sales-outbounds': {
    key: 'sales-outbounds',
    title: '销售出库',
    kicker: 'Sales',
    description: '销售出库页承担发货和库存扣减，销售订单完成价格核准后会回写本单状态，物流单和客户对账继续沿此单据下游流转。',
    primaryNoKey: 'outboundNo',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '出库单号', type: 'input', placeholder: '输入销售出库单号' },
      { key: 'customerName', label: '客户', type: 'select', options: [
        { label: '中建八局', value: '中建八局' },
        { label: '上海城建', value: '上海城建' },
        { label: '中铁建工', value: '中铁建工' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '已审核', value: '已审核' },
        { label: '价格核准', value: '价格核准' },
      ] },
      { key: 'outboundDate', label: '出库日期', type: 'dateRange' },
    ],
    columns: [
      { title: '出库单号', dataIndex: 'outboundNo', width: 160 },
      { title: '关联订单', dataIndex: 'salesOrderNo', width: 160 },
      { title: '客户', dataIndex: 'customerName', width: 140 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '仓库', dataIndex: 'warehouseName', width: 120 },
      { title: '出库日期', dataIndex: 'outboundDate', width: 120, type: 'date' },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '出库单号', key: 'outboundNo' },
      { label: '关联订单', key: 'salesOrderNo' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '仓库', key: 'warehouseName' },
      { label: '出库日期', key: 'outboundDate', type: 'date' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'outboundNo', label: '出库单号', type: 'input', required: true },
      { key: 'salesOrderNo', label: '关联订单', type: 'input', disabled: true, placeholder: '通过上级单据导入' },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: [
        { label: '中建八局', value: '中建八局' },
        { label: '上海城建', value: '上海城建' },
        { label: '中铁建工', value: '中铁建工' },
      ] },
      { key: 'projectName', label: '项目', type: 'input', required: true },
      { key: 'warehouseName', label: '仓库', type: 'select', required: true, options: [
        { label: '一号库', value: '一号库' },
        { label: '二号库', value: '二号库' },
      ] },
      { key: 'outboundDate', label: '出库日期', type: 'date', required: true },
      { key: 'remark', label: '备注', type: 'input' },
    ],
    parentImport: {
      parentModuleKey: 'sales-orders',
      label: '上级销售订单',
      parentFieldKey: 'salesOrderNo',
      parentDisplayFieldKey: 'orderNo',
      buttonText: '导入销售订单明细',
      enforceUniqueRelation: true,
      mapParentToDraft: (parentRecord) => ({
        customerName: parentRecord.customerName || '',
        projectName: parentRecord.projectName || '',
      }),
      transformItems: (parentRecord) => cloneLineItems(parentRecord.items, 'sales-outbound-item'),
    },
    itemColumns: compactOrderItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'freight-bills': {
    key: 'freight-bills',
    title: '物流单',
    kicker: 'Freight',
    description: '物流单页面按现版逻辑建立在销售出库之上，支持关联出库单、自动计算总重量和总运费，并继续流向物流对账。',
    primaryNoKey: 'billNo',
    actions: [
      { label: '新增物流单', type: 'primary' },
      { label: '标记送达', type: 'default' },
    ],
    filters: [
      { key: 'keyword', label: '物流单号', type: 'input', placeholder: '输入物流单号' },
      { key: 'carrierName', label: '物流商', type: 'select', options: [
        { label: '中外运华东', value: '中外运华东' },
        { label: '申通大件', value: '申通大件' },
        { label: '德邦钢材专线', value: '德邦钢材专线' },
      ] },
      { key: 'status', label: '审核状态', type: 'select', options: [
        { label: '未审核', value: '未审核' },
        { label: '已审核', value: '已审核' },
      ] },
      { key: 'billTime', label: '单据日期', type: 'dateRange' },
    ],
    columns: [
      { title: '物流单号', dataIndex: 'billNo', width: 160 },
      { title: '物流商', dataIndex: 'carrierName', width: 140 },
      { title: '客户', dataIndex: 'customerName', width: 140 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '单据日期', dataIndex: 'billTime', width: 120, type: 'date' },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '单价', dataIndex: 'unitPrice', width: 100, align: 'right', type: 'amount' },
      { title: '总运费', dataIndex: 'totalFreight', width: 110, align: 'right', type: 'amount' },
      { title: '审核状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '送达状态', dataIndex: 'deliveryStatus', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '物流单号', key: 'billNo' },
      { label: '关联出库单', key: 'outboundNo' },
      { label: '物流商', key: 'carrierName' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '单据日期', key: 'billTime', type: 'date' },
      { label: '单价', key: 'unitPrice', type: 'amount' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总运费', key: 'totalFreight', type: 'amount' },
      { label: '审核状态', key: 'status', type: 'status' },
      { label: '送达状态', key: 'deliveryStatus', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'billNo', label: '物流单号', type: 'input', required: true },
      { key: 'outboundNo', label: '关联出库单', type: 'input', disabled: true, placeholder: '通过上级单据导入' },
      { key: 'carrierName', label: '物流商', type: 'select', required: true, options: [
        { label: '中外运华东', value: '中外运华东' },
        { label: '申通大件', value: '申通大件' },
        { label: '德邦钢材专线', value: '德邦钢材专线' },
      ] },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: [
        { label: '中建八局', value: '中建八局' },
        { label: '上海城建', value: '上海城建' },
        { label: '中铁建工', value: '中铁建工' },
      ] },
      { key: 'projectName', label: '项目', type: 'input', required: true },
      { key: 'billTime', label: '单据日期', type: 'date', required: true },
      { key: 'unitPrice', label: '单价', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'status', label: '审核状态', type: 'select', defaultValue: '未审核', options: [
        { label: '未审核', value: '未审核' },
        { label: '已审核', value: '已审核' },
      ] },
      { key: 'deliveryStatus', label: '送达状态', type: 'select', defaultValue: '未送达', options: [
        { label: '未送达', value: '未送达' },
        { label: '已送达', value: '已送达' },
      ] },
      { key: 'remark', label: '备注', type: 'input' },
    ],
    parentImport: {
      parentModuleKey: 'sales-outbounds',
      label: '上级销售出库单',
      parentFieldKey: 'outboundNo',
      parentDisplayFieldKey: 'outboundNo',
      buttonText: '导入销售出库明细',
      mapParentToDraft: (parentRecord) => ({
        customerName: parentRecord.customerName || '',
        projectName: parentRecord.projectName || '',
      }),
      transformItems: transformFreightItems,
    },
    itemColumns: compactFreightItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalFreight'),
    statusMap,
    rowHighlightStatuses: ['未审核', '未送达'],
  },
  'purchase-contracts': {
    key: 'purchase-contracts',
    title: '采购合同',
    kicker: 'Contracts',
    description: '采购合同按供应商、签约日期、执行周期和商品明细统一管理，沿用通用单据页风格，先以 mock 数据驱动列表与编辑。',
    primaryNoKey: 'contractNo',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '合同编号', type: 'input', placeholder: '输入采购合同号' },
      { key: 'supplierName', label: '供应商', type: 'select', options: [
        { label: '江苏沙钢', value: '江苏沙钢' },
        { label: '中天钢铁', value: '中天钢铁' },
        { label: '永锋钢铁', value: '永锋钢铁' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '执行中', value: '执行中' },
        { label: '已签署', value: '已签署' },
        { label: '已归档', value: '已归档' },
      ] },
      { key: 'signDate', label: '签订日期', type: 'dateRange' },
    ],
    columns: [
      { title: '合同编号', dataIndex: 'contractNo', width: 170 },
      { title: '供应商', dataIndex: 'supplierName', width: 150 },
      { title: '签订日期', dataIndex: 'signDate', width: 120, type: 'date' },
      { title: '生效日期', dataIndex: 'effectiveDate', width: 120, type: 'date' },
      { title: '截止日期', dataIndex: 'expireDate', width: 120, type: 'date' },
      { title: '采购员', dataIndex: 'buyerName', width: 110 },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '合同编号', key: 'contractNo' },
      { label: '供应商', key: 'supplierName' },
      { label: '签订日期', key: 'signDate', type: 'date' },
      { label: '生效日期', key: 'effectiveDate', type: 'date' },
      { label: '截止日期', key: 'expireDate', type: 'date' },
      { label: '采购员', key: 'buyerName' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'contractNo', label: '合同编号', type: 'input', required: true },
      { key: 'supplierName', label: '供应商', type: 'select', required: true, options: [
        { label: '江苏沙钢', value: '江苏沙钢' },
        { label: '中天钢铁', value: '中天钢铁' },
        { label: '永锋钢铁', value: '永锋钢铁' },
      ] },
      { key: 'signDate', label: '签订日期', type: 'date', required: true },
      { key: 'effectiveDate', label: '生效日期', type: 'date', required: true },
      { key: 'expireDate', label: '截止日期', type: 'date', required: true },
      { key: 'buyerName', label: '采购员', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '草稿', options: [
        { label: '草稿', value: '草稿' },
        { label: '执行中', value: '执行中' },
        { label: '已签署', value: '已签署' },
        { label: '已归档', value: '已归档' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    itemColumns: compactOrderItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'sales-contracts': {
    key: 'sales-contracts',
    title: '销售合同',
    kicker: 'Contracts',
    description: '销售合同围绕客户、项目、签约周期和商品明细管理，沿用通用业务页样式，方便后续继续接订单关联或打印。',
    primaryNoKey: 'contractNo',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '合同编号', type: 'input', placeholder: '输入销售合同号' },
      { key: 'customerName', label: '客户', type: 'select', options: [
        { label: '中建八局', value: '中建八局' },
        { label: '上海城建', value: '上海城建' },
        { label: '中铁建工', value: '中铁建工' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '执行中', value: '执行中' },
        { label: '已签署', value: '已签署' },
        { label: '已归档', value: '已归档' },
      ] },
      { key: 'signDate', label: '签订日期', type: 'dateRange' },
    ],
    columns: [
      { title: '合同编号', dataIndex: 'contractNo', width: 170 },
      { title: '客户', dataIndex: 'customerName', width: 150 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '签订日期', dataIndex: 'signDate', width: 120, type: 'date' },
      { title: '生效日期', dataIndex: 'effectiveDate', width: 120, type: 'date' },
      { title: '截止日期', dataIndex: 'expireDate', width: 120, type: 'date' },
      { title: '销售员', dataIndex: 'salesName', width: 110 },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '合同编号', key: 'contractNo' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '签订日期', key: 'signDate', type: 'date' },
      { label: '生效日期', key: 'effectiveDate', type: 'date' },
      { label: '截止日期', key: 'expireDate', type: 'date' },
      { label: '销售员', key: 'salesName' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'contractNo', label: '合同编号', type: 'input', required: true },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: [
        { label: '中建八局', value: '中建八局' },
        { label: '上海城建', value: '上海城建' },
        { label: '中铁建工', value: '中铁建工' },
      ] },
      { key: 'projectName', label: '项目', type: 'input', required: true },
      { key: 'signDate', label: '签订日期', type: 'date', required: true },
      { key: 'effectiveDate', label: '生效日期', type: 'date', required: true },
      { key: 'expireDate', label: '截止日期', type: 'date', required: true },
      { key: 'salesName', label: '销售员', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '草稿', options: [
        { label: '草稿', value: '草稿' },
        { label: '执行中', value: '执行中' },
        { label: '已签署', value: '已签署' },
        { label: '已归档', value: '已归档' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    itemColumns: compactOrderItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'inventory-report': {
    key: 'inventory-report',
    title: '商品库存报表',
    kicker: 'Reports',
    description: '库存报表按商品编码、材质、类别、规格、长度、仓库、批号展示结存结果，便于先确认前端字段和查询交互。',
    actions: [{ label: '导出', type: 'primary' }],
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '商品编码 / 品牌 / 规格' },
      { key: 'warehouseName', label: '仓库', type: 'select', options: [
        { label: '一号库', value: '一号库' },
        { label: '二号库', value: '二号库' },
      ] },
      { key: 'category', label: '类别', type: 'select', options: [
        { label: '螺纹钢', value: '螺纹钢' },
        { label: '盘螺', value: '盘螺' },
        { label: '线材', value: '线材' },
      ] },
    ],
    columns: [
      { title: '商品编码', dataIndex: 'materialCode', width: 150 },
      { title: '品牌', dataIndex: 'brand', width: 120 },
      { title: '材质', dataIndex: 'material', width: 120 },
      { title: '类别', dataIndex: 'category', width: 110 },
      { title: '规格', dataIndex: 'spec', width: 100 },
      { title: '长度', dataIndex: 'length', width: 100 },
      { title: '仓库', dataIndex: 'warehouseName', width: 110 },
      { title: '批号', dataIndex: 'batchNo', width: 140 },
      { title: '数量', dataIndex: 'quantity', width: 100, align: 'right', type: 'count' },
      { title: '结存吨位', dataIndex: 'weightTon', width: 110, align: 'right', type: 'weight' },
    ],
    detailFields: [
      { label: '商品编码', key: 'materialCode' },
      { label: '品牌', key: 'brand' },
      { label: '材质', key: 'material' },
      { label: '类别', key: 'category' },
      { label: '规格', key: 'spec' },
      { label: '长度', key: 'length' },
      { label: '仓库', key: 'warehouseName' },
      { label: '批号', key: 'batchNo' },
      { label: '数量', key: 'quantity', type: 'count' },
      { label: '结存吨位', key: 'weightTon', type: 'weight' },
      { label: '单位', key: 'unit' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '库存记录', value: formatInteger(rows.length) },
      { label: '结存吨位', value: formatWeight(sumBy(rows, 'weightTon')) },
    ],
  },
  'io-report': {
    key: 'io-report',
    title: '出入库报表',
    kicker: 'Reports',
    description: '出入库报表用于查看业务流水，当前先把查询区、流水表格和明细字段统一成 AG Grid 列表。',
    actions: [{ label: '导出', type: 'primary' }],
    filters: [
      { key: 'keyword', label: '来源单号', type: 'input', placeholder: '输入来源单号' },
      { key: 'businessType', label: '业务类型', type: 'select', options: [
        { label: '采购入库', value: '采购入库' },
        { label: '销售出库', value: '销售出库' },
      ] },
      { key: 'businessDate', label: '业务日期', type: 'dateRange' },
    ],
    columns: [
      { title: '业务日期', dataIndex: 'businessDate', width: 120, type: 'date' },
      { title: '业务类型', dataIndex: 'businessType', width: 120 },
      { title: '来源单号', dataIndex: 'sourceNo', width: 160 },
      { title: '商品编码', dataIndex: 'materialCode', width: 140 },
      { title: '规格', dataIndex: 'spec', width: 100 },
      { title: '仓库', dataIndex: 'warehouseName', width: 110 },
      { title: '批号', dataIndex: 'batchNo', width: 140 },
      { title: '入库数量', dataIndex: 'inQuantity', width: 100, align: 'right', type: 'count' },
      { title: '出库数量', dataIndex: 'outQuantity', width: 100, align: 'right', type: 'count' },
      { title: '入库吨位', dataIndex: 'inWeightTon', width: 110, align: 'right', type: 'weight' },
      { title: '出库吨位', dataIndex: 'outWeightTon', width: 110, align: 'right', type: 'weight' },
    ],
    detailFields: [
      { label: '业务日期', key: 'businessDate', type: 'date' },
      { label: '业务类型', key: 'businessType' },
      { label: '来源单号', key: 'sourceNo' },
      { label: '商品编码', key: 'materialCode' },
      { label: '规格', key: 'spec' },
      { label: '仓库', key: 'warehouseName' },
      { label: '批号', key: 'batchNo' },
      { label: '入库数量', key: 'inQuantity', type: 'count' },
      { label: '出库数量', key: 'outQuantity', type: 'count' },
      { label: '入库吨位', key: 'inWeightTon', type: 'weight' },
      { label: '出库吨位', key: 'outWeightTon', type: 'weight' },
      { label: '备注', key: 'remark' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '流水数', value: formatInteger(rows.length) },
      { label: '入库吨位', value: formatWeight(sumBy(rows, 'inWeightTon')) },
      { label: '出库吨位', value: formatWeight(sumBy(rows, 'outWeightTon')) },
    ],
  },
  'supplier-statements': {
    key: 'supplier-statements',
    title: '供应商对账单',
    kicker: 'Statements',
    description: '供应商对账单用于汇总采购与付款，当前页面优先确认对账口径和字段展示，后续再接核销动作。',
    primaryNoKey: 'statementNo',
    actions: [{ label: '生成对账单', type: 'primary' }],
    filters: [
      { key: 'supplierName', label: '供应商', type: 'select', options: [
        { label: '江苏沙钢', value: '江苏沙钢' },
        { label: '中天钢铁', value: '中天钢铁' },
        { label: '永锋钢铁', value: '永锋钢铁' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '待确认', value: '待确认' },
        { label: '已确认', value: '已确认' },
      ] },
      { key: 'endDate', label: '账期', type: 'dateRange' },
    ],
    columns: [
      { title: '对账单号', dataIndex: 'statementNo', width: 170 },
      { title: '供应商', dataIndex: 'supplierName', width: 140 },
      { title: '开始日期', dataIndex: 'startDate', width: 120, type: 'date' },
      { title: '结束日期', dataIndex: 'endDate', width: 120, type: 'date' },
      { title: '采购金额', dataIndex: 'purchaseAmount', width: 110, align: 'right', type: 'amount' },
      { title: '付款金额', dataIndex: 'paymentAmount', width: 110, align: 'right', type: 'amount' },
      { title: '期末余额', dataIndex: 'closingAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '对账单号', key: 'statementNo' },
      { label: '供应商', key: 'supplierName' },
      { label: '开始日期', key: 'startDate', type: 'date' },
      { label: '结束日期', key: 'endDate', type: 'date' },
      { label: '采购金额', key: 'purchaseAmount', type: 'amount' },
      { label: '付款金额', key: 'paymentAmount', type: 'amount' },
      { label: '期末余额', key: 'closingAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'statementNo', label: '对账单号', type: 'input', required: true },
      { key: 'supplierName', label: '供应商', type: 'select', required: true, options: [
        { label: '江苏沙钢', value: '江苏沙钢' },
        { label: '中天钢铁', value: '中天钢铁' },
        { label: '永锋钢铁', value: '永锋钢铁' },
      ] },
      { key: 'startDate', label: '开始日期', type: 'date', required: true },
      { key: 'endDate', label: '结束日期', type: 'date', required: true },
      { key: 'purchaseAmount', label: '采购金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'paymentAmount', label: '付款金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'closingAmount', label: '期末余额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'status', label: '状态', type: 'select', defaultValue: '待确认', options: [
        { label: '待确认', value: '待确认' },
        { label: '已确认', value: '已确认' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildStatementOverview(rows, 'purchaseAmount', 'paymentAmount', 'closingAmount'),
    statusMap,
    rowHighlightStatuses: ['待确认'],
  },
  'customer-statements': {
    key: 'customer-statements',
    title: '客户对账单',
    kicker: 'Statements',
    description: '客户对账单按已完成销售的销售订单口径组织，价格核准已并入销售订单，销售出库仅保留回写状态。',
    primaryNoKey: 'statementNo',
    actions: [{ label: '生成对账单', type: 'primary' }],
    filters: [
      { key: 'customerName', label: '客户', type: 'select', options: [
        { label: '中建八局', value: '中建八局' },
        { label: '上海城建', value: '上海城建' },
        { label: '中铁建工', value: '中铁建工' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '待确认', value: '待确认' },
        { label: '已确认', value: '已确认' },
      ] },
      { key: 'endDate', label: '账期', type: 'dateRange' },
    ],
    columns: [
      { title: '对账单号', dataIndex: 'statementNo', width: 170 },
      { title: '客户', dataIndex: 'customerName', width: 140 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '开始日期', dataIndex: 'startDate', width: 120, type: 'date' },
      { title: '结束日期', dataIndex: 'endDate', width: 120, type: 'date' },
      { title: '销售金额', dataIndex: 'salesAmount', width: 110, align: 'right', type: 'amount' },
      { title: '收款金额', dataIndex: 'receiptAmount', width: 110, align: 'right', type: 'amount' },
      { title: '期末余额', dataIndex: 'closingAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '对账单号', key: 'statementNo' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '开始日期', key: 'startDate', type: 'date' },
      { label: '结束日期', key: 'endDate', type: 'date' },
      { label: '销售金额', key: 'salesAmount', type: 'amount' },
      { label: '收款金额', key: 'receiptAmount', type: 'amount' },
      { label: '期末余额', key: 'closingAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'statementNo', label: '对账单号', type: 'input', required: true },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: [
        { label: '中建八局', value: '中建八局' },
        { label: '上海城建', value: '上海城建' },
        { label: '中铁建工', value: '中铁建工' },
      ] },
      { key: 'projectName', label: '项目', type: 'input', required: true },
      { key: 'startDate', label: '开始日期', type: 'date', required: true },
      { key: 'endDate', label: '结束日期', type: 'date', required: true },
      { key: 'salesAmount', label: '销售金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'receiptAmount', label: '收款金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'closingAmount', label: '期末余额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'status', label: '状态', type: 'select', defaultValue: '待确认', options: [
        { label: '待确认', value: '待确认' },
        { label: '已确认', value: '已确认' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildStatementOverview(rows, 'salesAmount', 'receiptAmount', 'closingAmount'),
    statusMap,
    rowHighlightStatuses: ['待确认'],
  },
  'freight-statements': {
    key: 'freight-statements',
    title: '物流对账单',
    kicker: 'Statements',
    description: '物流对账单和运费对账汇总拆开处理，这里展示正式物流对账单列表，用于审核、签署、附件和付款累计。',
    primaryNoKey: 'statementNo',
    actions: [
      { label: '生成物流对账单', type: 'primary' },
      { label: '查看运费对账汇总', type: 'default' },
    ],
    filters: [
      { key: 'carrierName', label: '物流商', type: 'select', options: [
        { label: '中外运华东', value: '中外运华东' },
        { label: '申通大件', value: '申通大件' },
        { label: '德邦钢材专线', value: '德邦钢材专线' },
      ] },
      { key: 'status', label: '审核状态', type: 'select', options: [
        { label: '待审核', value: '待审核' },
        { label: '已审核', value: '已审核' },
      ] },
      { key: 'signStatus', label: '签署状态', type: 'select', options: [
        { label: '未签署', value: '未签署' },
        { label: '已签署', value: '已签署' },
      ] },
      { key: 'endDate', label: '账期', type: 'dateRange' },
    ],
    columns: [
      { title: '对账单号', dataIndex: 'statementNo', width: 170 },
      { title: '物流商', dataIndex: 'carrierName', width: 150 },
      { title: '开始日期', dataIndex: 'startDate', width: 120, type: 'date' },
      { title: '结束日期', dataIndex: 'endDate', width: 120, type: 'date' },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总运费', dataIndex: 'totalFreight', width: 110, align: 'right', type: 'amount' },
      { title: '已付金额', dataIndex: 'paidAmount', width: 110, align: 'right', type: 'amount' },
      { title: '审核状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '签署状态', dataIndex: 'signStatus', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '对账单号', key: 'statementNo' },
      { label: '物流商', key: 'carrierName' },
      { label: '开始日期', key: 'startDate', type: 'date' },
      { label: '结束日期', key: 'endDate', type: 'date' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总运费', key: 'totalFreight', type: 'amount' },
      { label: '已付金额', key: 'paidAmount', type: 'amount' },
      { label: '审核状态', key: 'status', type: 'status' },
      { label: '签署状态', key: 'signStatus', type: 'status' },
      { label: '附件', key: 'attachment' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'statementNo', label: '对账单号', type: 'input', required: true },
      { key: 'carrierName', label: '物流商', type: 'select', required: true, options: [
        { label: '中外运华东', value: '中外运华东' },
        { label: '申通大件', value: '申通大件' },
        { label: '德邦钢材专线', value: '德邦钢材专线' },
      ] },
      { key: 'startDate', label: '开始日期', type: 'date', required: true },
      { key: 'endDate', label: '结束日期', type: 'date', required: true },
      { key: 'totalWeight', label: '总吨位', type: 'number', required: true, min: 0, precision: 3, defaultValue: 0 },
      { key: 'totalFreight', label: '总运费', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'paidAmount', label: '已付金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'status', label: '审核状态', type: 'select', defaultValue: '待审核', options: [
        { label: '待审核', value: '待审核' },
        { label: '已审核', value: '已审核' },
      ] },
      { key: 'signStatus', label: '签署状态', type: 'select', defaultValue: '未签署', options: [
        { label: '未签署', value: '未签署' },
        { label: '已签署', value: '已签署' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    itemColumns: freightItemColumns,
    data: [],
    buildOverview: (rows) => buildStatementOverview(rows, 'totalFreight', 'paidAmount', 'unpaidAmount'),
    statusMap,
    rowHighlightStatuses: ['待审核', '未签署'],
  },
  receipts: {
    key: 'receipts',
    title: '收款单',
    kicker: 'Finance',
    description: '收款单页面用于承接客户回款，当前重点确认单据字段、状态和列表交互，不先接核销明细。',
    primaryNoKey: 'receiptNo',
    actions: [{ label: '新增收款单', type: 'primary' }],
    filters: [
      { key: 'customerName', label: '客户', type: 'select', options: [
        { label: '中建八局', value: '中建八局' },
        { label: '上海城建', value: '上海城建' },
        { label: '中铁建工', value: '中铁建工' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '已收款', value: '已收款' },
      ] },
      { key: 'receiptDate', label: '收款日期', type: 'dateRange' },
    ],
    columns: [
      { title: '收款单号', dataIndex: 'receiptNo', width: 170 },
      { title: '客户', dataIndex: 'customerName', width: 140 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '收款日期', dataIndex: 'receiptDate', width: 120, type: 'date' },
      { title: '收款方式', dataIndex: 'payType', width: 120 },
      { title: '金额', dataIndex: 'amount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '收款单号', key: 'receiptNo' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '收款日期', key: 'receiptDate', type: 'date' },
      { label: '收款方式', key: 'payType' },
      { label: '金额', key: 'amount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '经办人', key: 'operatorName' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'receiptNo', label: '收款单号', type: 'input', required: true },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: [
        { label: '中建八局', value: '中建八局' },
        { label: '上海城建', value: '上海城建' },
        { label: '中铁建工', value: '中铁建工' },
      ] },
      { key: 'projectName', label: '项目', type: 'input', required: true },
      { key: 'receiptDate', label: '收款日期', type: 'date', required: true },
      { key: 'payType', label: '收款方式', type: 'select', required: true, options: [
        { label: '银行转账', value: '银行转账' },
        { label: '银行承兑', value: '银行承兑' },
        { label: '承兑汇票', value: '承兑汇票' },
        { label: '现金', value: '现金' },
      ] },
      { key: 'amount', label: '金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'status', label: '状态', type: 'select', defaultValue: '草稿', options: [
        { label: '草稿', value: '草稿' },
        { label: '已收款', value: '已收款' },
      ] },
      { key: 'operatorName', label: '经办人', type: 'input', required: true },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  payments: {
    key: 'payments',
    title: '付款单',
    kicker: 'Finance',
    description: '付款单统一承接供应商付款和物流付款，页面先以业务类型、往来单位、金额和状态为主。',
    primaryNoKey: 'paymentNo',
    actions: [{ label: '新增付款单', type: 'primary' }],
    filters: [
      { key: 'businessType', label: '业务类型', type: 'select', options: [
        { label: '供应商', value: '供应商' },
        { label: '物流商', value: '物流商' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '已付款', value: '已付款' },
      ] },
      { key: 'paymentDate', label: '付款日期', type: 'dateRange' },
    ],
    columns: [
      { title: '付款单号', dataIndex: 'paymentNo', width: 170 },
      { title: '业务类型', dataIndex: 'businessType', width: 110 },
      { title: '往来单位', dataIndex: 'counterpartyName', width: 160 },
      { title: '付款日期', dataIndex: 'paymentDate', width: 120, type: 'date' },
      { title: '付款方式', dataIndex: 'payType', width: 120 },
      { title: '金额', dataIndex: 'amount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '付款单号', key: 'paymentNo' },
      { label: '业务类型', key: 'businessType' },
      { label: '往来单位', key: 'counterpartyName' },
      { label: '付款日期', key: 'paymentDate', type: 'date' },
      { label: '付款方式', key: 'payType' },
      { label: '金额', key: 'amount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '经办人', key: 'operatorName' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'paymentNo', label: '付款单号', type: 'input', required: true },
      { key: 'businessType', label: '业务类型', type: 'select', required: true, options: [
        { label: '供应商', value: '供应商' },
        { label: '物流商', value: '物流商' },
      ] },
      { key: 'counterpartyName', label: '往来单位', type: 'input', required: true },
      { key: 'paymentDate', label: '付款日期', type: 'date', required: true },
      { key: 'payType', label: '付款方式', type: 'select', required: true, options: [
        { label: '银行转账', value: '银行转账' },
        { label: '银行承兑', value: '银行承兑' },
        { label: '现金', value: '现金' },
      ] },
      { key: 'amount', label: '金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'status', label: '状态', type: 'select', defaultValue: '草稿', options: [
        { label: '草稿', value: '草稿' },
        { label: '已付款', value: '已付款' },
      ] },
      { key: 'operatorName', label: '经办人', type: 'input', required: true },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'receivables-payables': {
    key: 'receivables-payables',
    title: '应收应付',
    kicker: 'Finance',
    description: '应收应付页面先按客户、供应商、物流商统一展示余额结果，后续再叠加核销和账龄分析。',
    actions: [{ label: '导出余额表', type: 'primary' }],
    filters: [
      { key: 'direction', label: '方向', type: 'select', options: [
        { label: '应收', value: '应收' },
        { label: '应付', value: '应付' },
      ] },
      { key: 'counterpartyType', label: '往来类型', type: 'select', options: [
        { label: '客户', value: '客户' },
        { label: '供应商', value: '供应商' },
        { label: '物流商', value: '物流商' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
    ],
    columns: [
      { title: '方向', dataIndex: 'direction', width: 100 },
      { title: '往来类型', dataIndex: 'counterpartyType', width: 110 },
      { title: '往来单位', dataIndex: 'counterpartyName', width: 160 },
      { title: '期初余额', dataIndex: 'openingAmount', width: 110, align: 'right', type: 'amount' },
      { title: '本期发生', dataIndex: 'currentAmount', width: 110, align: 'right', type: 'amount' },
      { title: '本期结算', dataIndex: 'settledAmount', width: 110, align: 'right', type: 'amount' },
      { title: '期末余额', dataIndex: 'balanceAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '方向', key: 'direction' },
      { label: '往来类型', key: 'counterpartyType' },
      { label: '往来单位', key: 'counterpartyName' },
      { label: '期初余额', key: 'openingAmount', type: 'amount' },
      { label: '本期发生', key: 'currentAmount', type: 'amount' },
      { label: '本期结算', key: 'settledAmount', type: 'amount' },
      { label: '期末余额', key: 'balanceAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '往来单位数', value: formatInteger(rows.length) },
      { label: '应收余额', value: formatAmount(sumBy(rows.filter((row) => row.direction === '应收'), 'balanceAmount')) },
      { label: '应付余额', value: formatAmount(sumBy(rows.filter((row) => row.direction === '应付'), 'balanceAmount')) },
    ],
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  'general-settings': {
    key: 'general-settings',
    title: '通用设置',
    kicker: 'System',
    description: '通用设置当前集中维护全局单号规则，覆盖采购、销售、物流、合同、对账与收付款单据的编号前缀和流水规则。',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '配置编码 / 单据名称 / 前缀' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
    ],
    columns: [
      { title: '配置编码', dataIndex: 'settingCode', width: 150 },
      { title: '配置名称', dataIndex: 'settingName', width: 180 },
      { title: '单据名称', dataIndex: 'billName', width: 140 },
      { title: '前缀', dataIndex: 'prefix', width: 90 },
      { title: '日期规则', dataIndex: 'dateRule', width: 120 },
      { title: '流水位数', dataIndex: 'serialLength', width: 100, align: 'right', type: 'count' },
      { title: '重置规则', dataIndex: 'resetRule', width: 110 },
      { title: '示例单号', dataIndex: 'sampleNo', width: 170 },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 220 },
    ],
    detailFields: [
      { label: '配置编码', key: 'settingCode' },
      { label: '配置名称', key: 'settingName' },
      { label: '单据名称', key: 'billName' },
      { label: '前缀', key: 'prefix' },
      { label: '日期规则', key: 'dateRule' },
      { label: '流水位数', key: 'serialLength', type: 'count' },
      { label: '重置规则', key: 'resetRule' },
      { label: '示例单号', key: 'sampleNo' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'settingCode', label: '配置编码', type: 'input', required: true },
      { key: 'settingName', label: '配置名称', type: 'input', required: true },
      { key: 'billName', label: '单据名称', type: 'input', required: true },
      { key: 'prefix', label: '前缀', type: 'input', required: true },
      { key: 'dateRule', label: '日期规则', type: 'select', required: true, options: [
        { label: 'YYYY', value: 'YYYY' },
        { label: 'YYYYMM', value: 'YYYYMM' },
      ] },
      { key: 'serialLength', label: '流水位数', type: 'number', required: true, min: 1, precision: 0, defaultValue: 6 },
      { key: 'resetRule', label: '重置规则', type: 'select', required: true, options: [
        { label: '按年重置', value: '按年重置' },
        { label: '按月重置', value: '按月重置' },
        { label: '永不重置', value: '永不重置' },
      ] },
      { key: 'sampleNo', label: '示例单号', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '规则数', value: formatInteger(rows.length) },
      { label: '启用规则', value: formatInteger(rows.filter((row) => row.status === '正常').length) },
    ],
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  'permission-management': {
    key: 'permission-management',
    title: '权限管理',
    kicker: 'System',
    description: '权限管理用于维护菜单、按钮和数据范围权限编码，先以 mock 数据确认字段结构和维护交互。',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '权限编码 / 名称 / 模块' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
    ],
    columns: [
      { title: '权限编码', dataIndex: 'permissionCode', width: 150 },
      { title: '权限名称', dataIndex: 'permissionName', width: 180 },
      { title: '模块', dataIndex: 'moduleName', width: 140 },
      { title: '权限类型', dataIndex: 'permissionType', width: 110 },
      { title: '动作', dataIndex: 'actionName', width: 120 },
      { title: '数据范围', dataIndex: 'scopeName', width: 120 },
      { title: '资源标识', dataIndex: 'resourceKey', width: 180 },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 220 },
    ],
    detailFields: [
      { label: '权限编码', key: 'permissionCode' },
      { label: '权限名称', key: 'permissionName' },
      { label: '模块', key: 'moduleName' },
      { label: '权限类型', key: 'permissionType' },
      { label: '动作', key: 'actionName' },
      { label: '数据范围', key: 'scopeName' },
      { label: '资源标识', key: 'resourceKey' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'permissionCode', label: '权限编码', type: 'input', required: true },
      { key: 'permissionName', label: '权限名称', type: 'input', required: true },
      { key: 'moduleName', label: '模块', type: 'input', required: true },
      { key: 'permissionType', label: '权限类型', type: 'select', required: true, options: [
        { label: '菜单权限', value: '菜单权限' },
        { label: '按钮权限', value: '按钮权限' },
        { label: '数据权限', value: '数据权限' },
      ] },
      { key: 'actionName', label: '动作', type: 'select', required: true, options: [
        { label: '查看', value: '查看' },
        { label: '新增', value: '新增' },
        { label: '编辑', value: '编辑' },
        { label: '删除', value: '删除' },
        { label: '审核', value: '审核' },
        { label: '导出', value: '导出' },
        { label: '打印', value: '打印' },
      ] },
      { key: 'scopeName', label: '数据范围', type: 'select', required: true, options: [
        { label: '全部数据', value: '全部数据' },
        { label: '本部门', value: '本部门' },
        { label: '本人', value: '本人' },
        { label: '自定义范围', value: '自定义范围' },
      ] },
      { key: 'resourceKey', label: '资源标识', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  'user-accounts': {
    key: 'user-accounts',
    title: '用户账户',
    kicker: 'System',
    description: '用户账户页面维护登录账号、角色、联系方式和启用状态，供后续权限和审计链路复用。',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '登录账号 / 用户姓名 / 手机号' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
    ],
    columns: [
      { title: '登录账号', dataIndex: 'loginName', width: 140 },
      { title: '用户姓名', dataIndex: 'userName', width: 140 },
      { title: '手机号', dataIndex: 'mobile', width: 140 },
      { title: '所属角色', dataIndex: 'roleNames', width: 220 },
      { title: '数据范围', dataIndex: 'dataScope', width: 120 },
      { title: '权限摘要', dataIndex: 'permissionSummary', width: 220 },
      { title: '最近登录', dataIndex: 'lastLoginDate', width: 120, type: 'date' },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '登录账号', key: 'loginName' },
      { label: '用户姓名', key: 'userName' },
      { label: '手机号', key: 'mobile' },
      { label: '所属角色', key: 'roleNames' },
      { label: '数据范围', key: 'dataScope' },
      { label: '权限摘要', key: 'permissionSummary' },
      { label: '最近登录', key: 'lastLoginDate', type: 'date' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'loginName', label: '登录账号', type: 'input', required: true },
      { key: 'userName', label: '用户姓名', type: 'input', required: true },
      { key: 'mobile', label: '手机号', type: 'input', required: true },
      { key: 'roleNames', label: '所属角色', type: 'multiSelect', required: true, options: [
        { label: '系统管理员', value: '系统管理员' },
        { label: '采购主管', value: '采购主管' },
        { label: '销售经理', value: '销售经理' },
        { label: '财务专员', value: '财务专员' },
        { label: '仓库主管', value: '仓库主管' },
      ] },
      { key: 'dataScope', label: '数据范围', type: 'select', required: true, options: [
        { label: '全部数据', value: '全部数据' },
        { label: '本部门', value: '本部门' },
        { label: '本人', value: '本人' },
      ] },
      { key: 'permissionSummary', label: '权限摘要', type: 'textarea', disabled: true },
      { key: 'lastLoginDate', label: '最近登录', type: 'date', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  'role-settings': {
    key: 'role-settings',
    title: '角色设置',
    kicker: 'System',
    description: '角色设置统一定义岗位角色、数据范围和当前绑定人数，方便权限分配和后续组织调整。',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '角色编码 / 角色名称 / 角色类型' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
    ],
    columns: [
      { title: '角色编码', dataIndex: 'roleCode', width: 140 },
      { title: '角色名称', dataIndex: 'roleName', width: 160 },
      { title: '角色类型', dataIndex: 'roleType', width: 120 },
      { title: '数据范围', dataIndex: 'dataScope', width: 120 },
      { title: '权限项', dataIndex: 'permissionCount', width: 90, align: 'right', type: 'count' },
      { title: '权限摘要', dataIndex: 'permissionSummary', width: 240 },
      { title: '绑定人数', dataIndex: 'userCount', width: 100, align: 'right', type: 'count' },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 220 },
    ],
    detailFields: [
      { label: '角色编码', key: 'roleCode' },
      { label: '角色名称', key: 'roleName' },
      { label: '角色类型', key: 'roleType' },
      { label: '数据范围', key: 'dataScope' },
      { label: '权限项', key: 'permissionCount', type: 'count' },
      { label: '权限摘要', key: 'permissionSummary' },
      { label: '绑定人数', key: 'userCount', type: 'count' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'roleCode', label: '角色编码', type: 'input', required: true },
      { key: 'roleName', label: '角色名称', type: 'input', required: true },
      { key: 'roleType', label: '角色类型', type: 'select', required: true, options: [
        { label: '系统角色', value: '系统角色' },
        { label: '业务角色', value: '业务角色' },
        { label: '财务角色', value: '财务角色' },
      ] },
      { key: 'dataScope', label: '数据范围', type: 'select', required: true, options: [
        { label: '全部数据', value: '全部数据' },
        { label: '本部门', value: '本部门' },
        { label: '本人', value: '本人' },
        { label: '自定义范围', value: '自定义范围' },
      ] },
      { key: 'permissionCodes', label: '绑定权限', type: 'multiSelect', required: true, options: [
        { label: '采购订单查看', value: 'PURCHASE_ORDER_VIEW' },
        { label: '采购入库编辑', value: 'PURCHASE_INBOUND_EDIT' },
        { label: '销售订单审核', value: 'SALES_ORDER_AUDIT' },
        { label: '付款单删除', value: 'FINANCE_PAYMENT_DELETE' },
        { label: '合同管理查看', value: 'CONTRACT_VIEW' },
        { label: '系统设置维护', value: 'SYSTEM_SETTING_EDIT' },
      ] },
      { key: 'permissionSummary', label: '权限摘要', type: 'textarea', disabled: true },
      { key: 'userCount', label: '绑定人数', type: 'number', required: true, min: 0, precision: 0, defaultValue: 0 },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: [
        { label: '正常', value: '正常' },
        { label: '禁用', value: '禁用' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  'ops-support': {
    key: 'ops-support',
    title: '运维支持',
    kicker: 'System',
    description: '运维支持页面汇总系统问题、处理人、优先级和当前处理状态，先按工单模式用 mock 数据交付维护页。',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '工单编号 / 问题类型 / 提交人' },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '待确认', value: '待确认' },
        { label: '执行中', value: '执行中' },
        { label: '已完成', value: '已完成' },
      ] },
    ],
    columns: [
      { title: '工单编号', dataIndex: 'ticketNo', width: 150 },
      { title: '问题类型', dataIndex: 'issueType', width: 140 },
      { title: '优先级', dataIndex: 'priorityLevel', width: 100 },
      { title: '提交人', dataIndex: 'submitterName', width: 120 },
      { title: '处理人', dataIndex: 'handlerName', width: 120 },
      { title: '提交日期', dataIndex: 'submitDate', width: 120, type: 'date' },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 220 },
    ],
    detailFields: [
      { label: '工单编号', key: 'ticketNo' },
      { label: '问题类型', key: 'issueType' },
      { label: '优先级', key: 'priorityLevel' },
      { label: '提交人', key: 'submitterName' },
      { label: '处理人', key: 'handlerName' },
      { label: '提交日期', key: 'submitDate', type: 'date' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'ticketNo', label: '工单编号', type: 'input', required: true },
      { key: 'issueType', label: '问题类型', type: 'select', required: true, options: [
        { label: '账号权限', value: '账号权限' },
        { label: '打印模板', value: '打印模板' },
        { label: '接口联调', value: '接口联调' },
        { label: '系统部署', value: '系统部署' },
      ] },
      { key: 'priorityLevel', label: '优先级', type: 'select', required: true, options: [
        { label: '高', value: '高' },
        { label: '中', value: '中' },
        { label: '低', value: '低' },
      ] },
      { key: 'submitterName', label: '提交人', type: 'input', required: true },
      { key: 'handlerName', label: '处理人', type: 'input', required: true },
      { key: 'submitDate', label: '提交日期', type: 'date', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '待确认', options: [
        { label: '待确认', value: '待确认' },
        { label: '执行中', value: '执行中' },
        { label: '已完成', value: '已完成' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '工单数', value: formatInteger(rows.length) },
      { label: '待确认', value: formatInteger(rows.filter((row) => row.status === '待确认').length) },
      { label: '执行中', value: formatInteger(rows.filter((row) => row.status === '执行中').length) },
    ],
    statusMap,
    rowHighlightStatuses: ['待确认', '执行中'],
  },
}
