import type { ModuleFilterDefinition } from '@/types/module-page'

interface ModuleSaveFieldSchema {
  scalar?: string[]
  lineItem?: string[]
  chargeItem?: string[]
  computed?: string[]
}

interface ModulePageSchema {
  filters?: ModuleFilterDefinition[]
  saveFields?: ModuleSaveFieldSchema
}

const productKeywordFilter: ModuleFilterDefinition = {
  key: 'productKeyword',
  label: '商品信息',
  type: 'input',
}

const modulePageSchemaMap: Record<string, ModulePageSchema> = {
  'purchase-order': {
    filters: [
      {
        key: 'keyword',
        label: '订单编号',
        type: 'input',
      },
      {
        key: 'supplierId',
        label: '供应商名称',
        type: 'select',
      },
      {
        key: 'settlementCompanyId',
        label: '结算主体',
        type: 'select',
      },
      {
        key: 'status',
        label: '单据状态',
        type: 'select',
      },
      { key: 'orderDate', label: '订单日期', type: 'dateRange' },
    ],
    saveFields: {
      scalar: [
        'orderNo',
        'supplierId',
        'supplierCode',
        'supplierName',
        'settlementCompanyId',
        'orderDate',
        'buyerName',
        'status',
        'remark',
      ],
      chargeItem: [
        'id',
        'chargeName',
        'materialId',
        'amount',
        'unit',
        'remark',
      ],
      lineItem: [
        'materialId',
        'materialCode',
        'brand',
        'category',
        'material',
        'spec',
        'length',
        'unit',
        'warehouseId',
        'warehouseName',
        'batchNo',
        'quantity',
        'quantityUnit',
        'pieceWeightTon',
        'piecesPerBundle',
        'weightTon',
        'unitPrice',
        'amount',
      ],
    },
  },
  'purchase-inbound': {
    filters: [
      {
        key: 'keyword',
        label: '入库单号',
        type: 'input',
      },
      {
        key: 'supplierId',
        label: '供应商名称',
        type: 'select',
      },
      {
        key: 'settlementCompanyId',
        label: '结算主体',
        type: 'select',
      },
      {
        key: 'status',
        label: '单据状态',
        type: 'select',
      },
      { key: 'inboundDate', label: '入库日期', type: 'dateRange' },
    ],
    saveFields: {
      scalar: [
        'inboundNo',
        'purchaseOrderNo',
        'supplierId',
        'supplierCode',
        'supplierName',
        'inboundDate',
        'status',
        'remark',
      ],
      lineItem: [
        'sourcePurchaseOrderItemId',
        'materialId',
        'materialCode',
        'brand',
        'category',
        'material',
        'spec',
        'length',
        'unit',
        'warehouseId',
        'warehouseName',
        'settlementMode',
        'batchNo',
        'quantity',
        'quantityUnit',
        'pieceWeightTon',
        'piecesPerBundle',
        'weightTon',
        'weighWeightTon',
        'weightAdjustmentTon',
        'weightAdjustmentAmount',
        'unitPrice',
        'amount',
      ],
    },
  },
  'sales-order': {
    filters: [
      {
        key: 'keyword',
        label: '订单编号',
        type: 'input',
      },
      productKeywordFilter,
      { key: 'status', label: '单据状态', type: 'select' },
      { key: 'deliveryDate', label: '送货日期', type: 'dateRange' },
      { key: 'customerId', label: '客户名称', type: 'select' },
      { key: 'projectId', label: '项目名称', type: 'select' },
      { key: 'settlementCompanyId', label: '结算主体', type: 'select' },
    ],
    saveFields: {
      scalar: [
        'orderNo',
        'purchaseInboundNo',
        'purchaseOrderNo',
        'customerId',
        'customerCode',
        'customerName',
        'projectId',
        'projectName',
        'settlementCompanyId',
        'settlementCompanyName',
        'deliveryDate',
        'salesName',
        'status',
        'remark',
      ],
      chargeItem: [
        'id',
        'chargeName',
        'materialId',
        'amount',
        'unit',
        'remark',
      ],
      lineItem: [
        'sourceInboundItemId',
        'sourcePurchaseOrderItemId',
        'materialId',
        'materialCode',
        'brand',
        'category',
        'material',
        'spec',
        'length',
        'unit',
        'warehouseId',
        'warehouseName',
        'batchNo',
        'quantity',
        'quantityUnit',
        'pieceWeightTon',
        'piecesPerBundle',
        'weightTon',
        'unitPrice',
        'amount',
      ],
    },
  },
  'sales-outbound': {
    filters: [
      {
        key: 'keyword',
        label: '出库单号',
        type: 'input',
      },
      productKeywordFilter,
      { key: 'status', label: '单据状态', type: 'select' },
      { key: 'outboundDate', label: '出库日期', type: 'dateRange' },
      { key: 'customerId', label: '客户名称', type: 'select' },
      { key: 'projectId', label: '项目名称', type: 'select' },
      { key: 'settlementCompanyId', label: '结算主体', type: 'select' },
    ],
    saveFields: {
      scalar: [
        'outboundNo',
        'salesOrderNo',
        'customerId',
        'customerName',
        'projectId',
        'projectName',
        'warehouseName',
        'outboundDate',
        'status',
        'remark',
      ],
      lineItem: [
        'id',
        'sourceSalesOrderItemId',
        'quantity',
        'quantityUnit',
        'pieceWeightTon',
        'piecesPerBundle',
        'unitPrice',
        'warehouseId',
        'warehouseName',
      ],
    },
  },
  'freight-bill': {
    filters: [
      {
        key: 'keyword',
        label: '物流单号',
        type: 'input',
      },
      { key: 'carrierId', label: '物流商', type: 'select' },
      { key: 'settlementCompanyId', label: '结算主体', type: 'select' },
      { key: 'status', label: '单据状态', type: 'select' },
      { key: 'billTime', label: '单据日期', type: 'dateRange' },
    ],
    saveFields: {
      scalar: [
        'billNo',
        'carrierId',
        'carrierCode',
        'carrierName',
        'settlementCompanyId',
        'settlementCompanyName',
        'vehiclePlate',
        'billTime',
        'unitPrice',
        'status',
        'remark',
      ],
      chargeItem: [
        'id',
        'chargeName',
        'materialId',
        'amount',
        'unit',
        'remark',
      ],
      lineItem: ['id', 'sourceSalesOrderItemId'],
    },
  },
  receipt: {
    saveFields: {
      scalar: [
        'receiptNo',
        'counterpartyType',
        'counterpartyId',
        'counterpartyCode',
        'counterpartyName',
        'receiptPurpose',
        'customerId',
        'customerCode',
        'customerName',
        'projectId',
        'projectName',
        'settlementCompanyId',
        'settlementCompanyName',
        'receiptDate',
        'payType',
        'amount',
        'status',
        'operatorName',
        'remark',
      ],
    },
  },
  payment: {
    saveFields: {
      scalar: [
        'paymentNo',
        'counterpartyType',
        'counterpartyId',
        'paymentPurpose',
        'counterpartyCode',
        'counterpartyName',
        'settlementCompanyId',
        'settlementCompanyName',
        'paymentDate',
        'payType',
        'amount',
        'status',
        'operatorName',
        'remark',
      ],
    },
  },
  'customer-statement': {
    filters: [
      { key: 'customerId', label: '客户名称', type: 'select' },
      { key: 'projectId', label: '项目名称', type: 'select' },
      { key: 'settlementCompanyId', label: '结算主体', type: 'select' },
      { key: 'status', label: '单据状态', type: 'select' },
      { key: 'endDate', label: '对账期间', type: 'dateRange' },
    ],
    saveFields: {
      scalar: [
        'statementNo',
        'sourceOrderNos',
        'customerId',
        'customerCode',
        'customerName',
        'projectId',
        'projectName',
        'settlementCompanyId',
        'settlementCompanyName',
        'startDate',
        'endDate',
        'salesAmount',
        'receiptAmount',
        'closingAmount',
        'status',
        'remark',
      ],
      lineItem: ['id', 'sourceSalesOrderItemId'],
    },
  },
  'freight-statement': {
    filters: [
      { key: 'carrierId', label: '物流商', type: 'select' },
      { key: 'settlementCompanyId', label: '结算主体', type: 'select' },
      { key: 'status', label: '审核状态', type: 'select' },
      { key: 'endDate', label: '对账期间', type: 'dateRange' },
    ],
    saveFields: {
      scalar: [
        'statementNo',
        'carrierId',
        'carrierCode',
        'carrierName',
        'settlementCompanyId',
        'settlementCompanyName',
        'startDate',
        'endDate',
        'totalWeight',
        'totalFreight',
        'paidAmount',
        'unpaidAmount',
        'status',
        'attachment',
        'remark',
      ],
      lineItem: ['id', 'sourceFreightBillId', 'sourceFreightBillItemId'],
    },
  },
}

export function getModulePageSchema(moduleKey: string) {
  return modulePageSchemaMap[moduleKey]
}
