import i18next from 'i18next'
import type { AppPageDefinition } from '@/config/page-registry-types'

export const financePageDefinitions: AppPageDefinition[] = [
  {
    key: 'customer-statement',
    title: i18next.t('pages.customer-statement'),
    menuKey: '/customer-statement',
    view: 'business-grid',
    icon: 'FileTextOutlined',
    menuParent: 'statements',
    moduleKey: 'customer-statement',
    searchable: true,
  },
  {
    key: 'freight-statement',
    title: i18next.t('pages.freight-statement'),
    menuKey: '/freight-statement',
    view: 'business-grid',
    icon: 'FileSyncOutlined',
    menuParent: 'statements',
    moduleKey: 'freight-statement',
    searchable: true,
  },
  {
    key: 'finance-overview',
    title: i18next.t('pages.finance-overview'),
    menuKey: '/finance-overview',
    view: 'finance-overview',
    icon: 'CalculatorOutlined',
    menuParent: 'finance',
  },
  {
    key: 'receipt',
    title: i18next.t('pages.receipt'),
    menuKey: '/receipt',
    view: 'business-grid',
    icon: 'AccountBookOutlined',
    menuParent: 'finance',
    moduleKey: 'receipt',
    searchable: true,
  },
  {
    key: 'payment',
    title: i18next.t('pages.payment'),
    menuKey: '/payment',
    view: 'business-grid',
    icon: 'CreditCardOutlined',
    menuParent: 'finance',
    moduleKey: 'payment',
    searchable: true,
  },
  {
    key: 'cash-ledger',
    title: i18next.t('pages.cash-ledger'),
    menuKey: '/cash-ledger',
    view: 'cash-ledger',
    icon: 'AccountBookOutlined',
    menuParent: 'finance',
    hiddenInMenu: true,
    activeMenuKey: '/finance-overview',
  },
]
