import type { AppPageDefinition } from '@/config/page-registry-types'

export const operationPageDefinitions: AppPageDefinition[] = [
  {
    key: 'purchase-order',
    title: '采购订单',
    menuKey: '/purchase-order',
    view: 'business-grid',
    icon: 'ProfileOutlined',
    menuParent: 'purchase',
    moduleKey: 'purchase-order',
    searchable: true,
  },
  {
    key: 'purchase-inbound',
    title: '采购入库',
    menuKey: '/purchase-inbound',
    view: 'business-grid',
    icon: 'InboxOutlined',
    menuParent: 'purchase',
    moduleKey: 'purchase-inbound',
    searchable: true,
  },
  {
    key: 'sales-order',
    title: '销售订单',
    menuKey: '/sales-order',
    view: 'business-grid',
    icon: 'FileDoneOutlined',
    menuParent: 'sales',
    moduleKey: 'sales-order',
    searchable: true,
  },
  {
    key: 'sales-outbound',
    title: '销售出库',
    menuKey: '/sales-outbound',
    view: 'business-grid',
    icon: 'SwapOutlined',
    menuParent: 'sales',
    moduleKey: 'sales-outbound',
    searchable: true,
  },
  {
    key: 'freight-bill',
    title: '物流单',
    menuKey: '/freight-bill',
    view: 'business-grid',
    icon: 'CarOutlined',
    menuParent: 'freight',
    moduleKey: 'freight-bill',
    searchable: true,
  },
  {
    key: 'inventory-report',
    title: '商品库存报表',
    menuKey: '/inventory-report',
    view: 'business-grid',
    icon: 'BarChartOutlined',
    menuParent: 'reports',
    moduleKey: 'inventory-report',
  },
  {
    key: 'io-report',
    title: '出入库报表',
    menuKey: '/io-report',
    view: 'business-grid',
    icon: 'SwapOutlined',
    menuParent: 'reports',
    moduleKey: 'io-report',
  },
]
