import type { AppPageDefinition } from '@/config/page-registry-types'

export const systemPageDefinitions: AppPageDefinition[] = [
  {
    key: 'print-template',
    title: '打印模板',
    menuKey: '/print-template',
    view: 'print-template',
    icon: 'PrinterOutlined',
    menuParent: 'system',
    resourceKey: 'print-template',
  },
  {
    key: 'number-rules',
    title: '单号规则',
    menuKey: '/number-rules',
    view: 'number-rules',
    icon: 'ProfileOutlined',
    menuParent: 'system',
    accessResources: ['general-setting'],
  },
  {
    key: 'general-setting',
    title: '通用设置',
    menuKey: '/general-setting',
    view: 'general-setting',
    icon: 'SettingOutlined',
    menuParent: 'system',
    moduleKey: 'general-setting',
    resourceKey: 'general-setting',
  },
  {
    key: 'company-setting',
    title: '公司信息',
    menuKey: '/company-setting',
    view: 'company-setting',
    icon: 'AccountBookOutlined',
    menuParent: 'system',
    moduleKey: 'company-setting',
    resourceKey: 'company-setting',
  },
  {
    key: 'operation-log',
    title: '操作日志',
    menuKey: '/operation-log',
    view: 'business-grid',
    icon: 'FileSearchOutlined',
    menuParent: 'system',
    moduleKey: 'operation-log',
    resourceKey: 'operation-log',
  },
  {
    key: 'department',
    title: '部门管理',
    menuKey: '/department',
    view: 'business-grid',
    icon: 'ApartmentOutlined',
    menuParent: 'system',
    moduleKey: 'department',
    resourceKey: 'department',
  },
  {
    key: 'access-control',
    title: '访问控制',
    menuKey: '/access-control',
    view: 'access-control',
    icon: 'SafetyCertificateOutlined',
    menuParent: 'system',
    accessResources: ['access-control'],
  },
  {
    key: 'session',
    title: '会话管理',
    menuKey: '/session',
    view: 'session',
    icon: 'SafetyCertificateOutlined',
    menuParent: 'system',
    resourceKey: 'session',
  },
  {
    key: 'api-key',
    title: 'API Key 管理',
    menuKey: '/api-key',
    view: 'api-key',
    icon: 'SafetyCertificateOutlined',
    menuParent: 'system',
    resourceKey: 'api-key',
  },
  {
    key: 'security-key',
    title: '安全密钥管理',
    menuKey: '/security-key',
    view: 'security-key',
    icon: 'SafetyCertificateOutlined',
    menuParent: 'system',
    resourceKey: 'security-key',
  },
  {
    key: 'database-backup',
    title: '数据库管理',
    menuKey: '/database',
    view: 'database-backup',
    icon: 'DatabaseOutlined',
    menuParent: 'system',
    resourceKey: 'database',
    accessResources: ['general-setting'],
  },
]
