import type { AppPageDefinition } from '@/config/page-registry-types'

export const financePageDefinitions: AppPageDefinition[] = [
  {
    key: 'customer-statement',
    title: '客户对账单',
    menuKey: '/customer-statement',
    view: 'business-grid',
    icon: 'FileTextOutlined',
    menuParent: 'statements',
    moduleKey: 'customer-statement',
    searchable: true,
  },
  {
    key: 'freight-statement',
    title: '物流对账单',
    menuKey: '/freight-statement',
    view: 'business-grid',
    icon: 'FileSyncOutlined',
    menuParent: 'statements',
    moduleKey: 'freight-statement',
    searchable: true,
  },
  {
    key: 'receipt',
    title: '收款单',
    menuKey: '/receipt',
    view: 'business-grid',
    icon: 'AccountBookOutlined',
    menuParent: 'finance',
    moduleKey: 'receipt',
    searchable: true,
  },
  {
    key: 'payment',
    title: '付款单',
    menuKey: '/payment',
    view: 'business-grid',
    icon: 'CreditCardOutlined',
    menuParent: 'finance',
    moduleKey: 'payment',
    searchable: true,
  },
  {
    key: 'cash-ledger',
    title: '资金流水',
    menuKey: '/cash-ledger',
    view: 'cash-ledger',
    icon: 'AccountBookOutlined',
    menuParent: 'finance',
    resourceKey: 'cash-ledger',
    accessResources: ['cash-ledger'],
  },
]
