// TODO: remove @ts-nocheck — fix AuditOutlined icon type to match AppIconKey
// @ts-nocheck
import type { AppPageDefinition } from '@/config/page-registry-types'

export const financePageDefinitions: AppPageDefinition[] = [
  {
    key: 'supplier-statement',
    title: '供应商对账单',
    menuKey: '/supplier-statement',
    view: 'business-grid',
    icon: 'FileSearchOutlined',
    menuParent: 'statements',
    moduleKey: 'supplier-statement',
    searchable: true,
  },
  {
    key: 'customer-statement',
    title: '客户对账单',
    menuKey: '/customer-statement',
    view: 'business-grid',
    icon: 'FileTextOutlined',
    menuParent: 'statements',
    moduleKey: 'customer-statement',
    searchable: true,
  },
  {
    key: 'freight-statement',
    title: '物流对账单',
    menuKey: '/freight-statement',
    view: 'business-grid',
    icon: 'FileSyncOutlined',
    menuParent: 'statements',
    moduleKey: 'freight-statement',
    searchable: true,
  },
  {
    key: 'receipt',
    title: '收款单',
    menuKey: '/receipt',
    view: 'business-grid',
    icon: 'AccountBookOutlined',
    menuParent: 'finance',
    moduleKey: 'receipt',
    searchable: true,
  },
  {
    key: 'payment',
    title: '付款单',
    menuKey: '/payment',
    view: 'business-grid',
    icon: 'CreditCardOutlined',
    menuParent: 'finance',
    moduleKey: 'payment',
    searchable: true,
  },
  {
    key: 'supplier-refund-receipt',
    title: '供应商退款到账单',
    menuKey: '/supplier-refund-receipt',
    view: 'business-grid',
    icon: 'RollbackOutlined',
    menuParent: 'finance',
    moduleKey: 'supplier-refund-receipt',
    searchable: true,
  },
  {
    key: 'invoice-receipt',
    title: '收票单',
    menuKey: '/invoice-receipt',
    view: 'business-grid',
    icon: 'FileTextOutlined',
    menuParent: 'finance',
    moduleKey: 'invoice-receipt',
    searchable: true,
  },
  {
    key: 'invoice-issue',
    title: '开票单',
    menuKey: '/invoice-issue',
    view: 'business-grid',
    icon: 'FileDoneOutlined',
    menuParent: 'finance',
    moduleKey: 'invoice-issue',
    searchable: true,
  },
  {
    key: 'ledger-adjustment',
    title: '台账调整单',
    menuKey: '/ledger-adjustment',
    view: 'business-grid',
    // @ts-expect-error icon type mismatch
    icon: 'AuditOutlined',
    menuParent: 'finance',
    moduleKey: 'ledger-adjustment',
    searchable: true,
  },
  {
    key: 'pending-invoice-receipt-report',
    title: '未收票报表',
    menuKey: '/pending-invoice-receipt-report',
    view: 'business-grid',
    icon: 'FileSearchOutlined',
    menuParent: 'finance',
    moduleKey: 'pending-invoice-receipt-report',
  },
  {
    key: 'receivable-payable',
    title: '应收应付',
    menuKey: '/receivable-payable',
    view: 'business-grid',
    icon: 'CalculatorOutlined',
    menuParent: 'finance',
    moduleKey: 'receivable-payable',
  },
]
