import type { AppPageDefinition } from '@/config/page-registry-types'

export const operationPageDefinitions: AppPageDefinition[] = [
  {
    key: 'purchase-order',
    titleKey: 'pages.purchase-order',
    menuKey: '/purchase-order',
    view: 'business-grid',
    icon: 'ProfileOutlined',
    menuParent: 'purchase',
    moduleKey: 'purchase-order',
    searchable: true,
  },
  {
    key: 'purchase-inbound',
    titleKey: 'pages.purchase-inbound',
    menuKey: '/purchase-inbound',
    view: 'business-grid',
    icon: 'InboxOutlined',
    menuParent: 'purchase',
    moduleKey: 'purchase-inbound',
    searchable: true,
  },
  {
    key: 'sales-order',
    titleKey: 'pages.sales-order',
    menuKey: '/sales-order',
    view: 'business-grid',
    icon: 'FileDoneOutlined',
    menuParent: 'sales',
    moduleKey: 'sales-order',
    searchable: true,
  },
  {
    key: 'sales-contract',
    titleKey: 'pages.sales-contract',
    menuKey: '/sales-contract',
    view: 'sales-contract',
    icon: 'ProfileOutlined',
    menuParent: 'sales',
  },
  {
    key: 'sales-outbound',
    titleKey: 'pages.sales-outbound',
    menuKey: '/sales-outbound',
    view: 'business-grid',
    icon: 'SwapOutlined',
    menuParent: 'sales',
    moduleKey: 'sales-outbound',
    searchable: true,
  },
  {
    key: 'sales-return',
    titleKey: 'pages.sales-return',
    menuKey: '/sales-return',
    view: 'business-grid',
    icon: 'RollbackOutlined',
    menuParent: 'sales',
    moduleKey: 'sales-return',
    searchable: true,
  },
  {
    key: 'inventory',
    titleKey: 'pages.inventory',
    menuKey: '/inventory',
    view: 'inventory',
    icon: 'DatabaseOutlined',
    menuParent: 'inventory',
  },
  {
    key: 'freight-bill',
    titleKey: 'pages.freight-bill',
    menuKey: '/freight-bill',
    view: 'business-grid',
    icon: 'CarOutlined',
    menuParent: 'freight',
    moduleKey: 'freight-bill',
    searchable: true,
  },
]
