export const FULL_SCAN_PAGE_SIZE = 200
const MAX_CLIENT_FILTER_PAGES = 10
export const MAX_CLIENT_FILTER_ROWS =
  FULL_SCAN_PAGE_SIZE * MAX_CLIENT_FILTER_PAGES
export const SOFT_WARN_ROW_THRESHOLD = 5000
