import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import {
  getSettlementCompanyOptions,
  type SettlementCompanyOption,
} from '@/api/system/company-settings'
import { enabledStatusOptions } from '@/constants/module-options'
import { asString } from '@/utils/type-narrowing'
import { MasterDataListPage } from './MasterDataListPage'
import type { MasterDataPageSpec } from './master-data-types'

function settlementCompanyOptions(): SettlementCompanyOption[] {
  return getSettlementCompanyOptions()
}

function resolveCompanyName(id: unknown): string {
  const normalized = asString(id).trim()
  if (!normalized) {
    return ''
  }
  return (
    settlementCompanyOptions().find(
      (option) => asString(option.value).trim() === normalized,
    )?.companyName ?? ''
  )
}

export function CustomerPage() {
  const { t } = useTranslation()
  const spec = useMemo<MasterDataPageSpec>(() => {
    const companyOptions = settlementCompanyOptions().map((option) => ({
      label: option.companyName,
      value: option.value,
    }))
    return {
      moduleKey: 'customer',
      title: t('modules.pages.customer.title'),
      description: t('modules.pages.customer.description'),
      keywordPlaceholder: t('modules.pages.customer.placeholderKeyword'),
      filters: [
        {
          key: 'status',
          type: 'select',
          placeholder: t('modules.filter.status'),
          options: enabledStatusOptions,
        },
      ],
      columns: [
        {
          key: 'customerCode',
          title: t('modules.pages.customer.colCustomerCode'),
          width: 140,
        },
        {
          key: 'customerName',
          title: t('modules.pages.customer.colCustomerName'),
          width: 180,
        },
        {
          key: 'projectNames',
          title: t('modules.pages.customer.colProjectName'),
          width: 300,
          render: (row) => {
            const value = row.projectNames
            if (Array.isArray(value)) {
              return value.length ? value.join('、') : '-'
            }
            return asString(value).trim() || '-'
          },
        },
        {
          key: 'contactName',
          title: t('modules.pages.customer.colContactName'),
          width: 110,
        },
        {
          key: 'contactPhone',
          title: t('modules.pages.customer.colContactPhone'),
          width: 140,
        },
        {
          key: 'city',
          title: t('modules.pages.customer.colCity'),
          width: 120,
        },
        {
          key: 'settlementMode',
          title: t('modules.pages.customer.colSettlementMode'),
          width: 110,
        },
        {
          key: 'defaultSettlementCompanyName',
          title: t('modules.pages.customer.colDefaultSettlementCompany'),
          width: 180,
        },
        {
          key: 'status',
          title: t('modules.columns.status'),
          width: 100,
          align: 'center',
          status: true,
        },
      ],
      defaultHiddenColumnKeys: ['contactPhone', 'city'],
      detailFields: [
        {
          key: 'customerCode',
          label: t('modules.pages.customer.colCustomerCode'),
        },
        {
          key: 'customerName',
          label: t('modules.pages.customer.colCustomerName'),
        },
        {
          key: 'contactName',
          label: t('modules.pages.customer.colContactName'),
        },
        {
          key: 'contactPhone',
          label: t('modules.pages.customer.colContactPhone'),
        },
        { key: 'city', label: t('modules.pages.customer.colCity') },
        {
          key: 'settlementMode',
          label: t('modules.pages.customer.colSettlementMode'),
        },
        {
          key: 'defaultSettlementCompanyName',
          label: t('modules.pages.customer.colDefaultSettlementCompany'),
        },
        {
          key: 'status',
          label: t('modules.columns.status'),
          status: true,
        },
        { key: 'remark', label: t('modules.columns.remark') },
      ],
      formFields: [
        {
          key: 'customerCode',
          label: t('modules.pages.customer.colCustomerCode'),
          type: 'input',
          disabled: true,
          placeholder: t('modules.editorWorkspace.autoGeneratedPlaceholder'),
        },
        {
          key: 'customerName',
          label: t('modules.pages.customer.colCustomerName'),
          type: 'input',
          required: true,
        },
        {
          key: 'contactName',
          label: t('modules.pages.customer.colContactName'),
          type: 'input',
        },
        {
          key: 'contactPhone',
          label: t('modules.pages.customer.colContactPhone'),
          type: 'input',
        },
        {
          key: 'city',
          label: t('modules.pages.customer.colCity'),
          type: 'input',
        },
        {
          key: 'settlementMode',
          label: t('modules.pages.customer.colSettlementMode'),
          type: 'select',
          options: [
            {
              label: t('modules.pages.customer.settlementCash'),
              value: '现结',
            },
            {
              label: t('modules.pages.customer.settlementMonthly'),
              value: '月结',
            },
            {
              label: t('modules.pages.customer.settlementCredit'),
              value: '授信',
            },
          ],
        },
        {
          key: 'defaultSettlementCompanyId',
          label: t('modules.pages.customer.colDefaultSettlementCompany'),
          type: 'select',
          required: true,
          options: companyOptions,
        },
        {
          key: 'status',
          label: t('modules.columns.status'),
          type: 'select',
          defaultValue: '正常',
          options: enabledStatusOptions,
        },
        {
          key: 'remark',
          label: t('modules.columns.remark'),
          type: 'textarea',
          fullRow: true,
        },
      ],
      rowHighlightStatuses: ['禁用'],
      buildValues: (record) => ({
        customerCode: asString(record?.customerCode),
        customerName: asString(record?.customerName),
        contactName: asString(record?.contactName),
        contactPhone: asString(record?.contactPhone),
        city: asString(record?.city),
        settlementMode: asString(record?.settlementMode),
        defaultSettlementCompanyId: asString(
          record?.defaultSettlementCompanyId,
        ),
        status: asString(record?.status) || '正常',
        remark: asString(record?.remark),
      }),
      buildRecord: (values, base) => ({
        ...(base ?? {}),
        customerCode: asString(values.customerCode),
        customerName: values.customerName,
        contactName: values.contactName ?? '',
        contactPhone: values.contactPhone ?? '',
        city: values.city ?? '',
        settlementMode: values.settlementMode ?? '',
        defaultSettlementCompanyId: values.defaultSettlementCompanyId ?? '',
        defaultSettlementCompanyName: resolveCompanyName(
          values.defaultSettlementCompanyId,
        ),
        status: values.status,
        remark: values.remark ?? '',
      }),
    }
  }, [t])
  return <MasterDataListPage spec={spec} />
}
