import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import { enabledStatusOptions } from '@/constants/module-options'
import { asString } from '@/utils/type-narrowing'
import { MasterDataListPage } from './MasterDataListPage'
import type { MasterDataPageSpec } from './master-data-types'

export function MaterialCategoriesPage() {
  const { t } = useTranslation()
  const spec = useMemo<MasterDataPageSpec>(
    () => ({
      moduleKey: 'material-categories',
      title: t('modules.pages.materialCategories.materialCategory'),
      description: t('modules.pages.materialCategories.categoryDesc'),
      keywordPlaceholder: t(
        'modules.pages.materialCategories.categoryPlaceholder',
      ),
      filters: [
        {
          key: 'status',
          type: 'select',
          placeholder: t('modules.filter.status'),
          options: enabledStatusOptions,
        },
      ],
      columns: [
        {
          key: 'categoryCode',
          title: t('modules.pages.materialCategories.categoryCode'),
          width: 150,
        },
        {
          key: 'categoryName',
          title: t('modules.pages.materialCategories.categoryName'),
          width: 180,
        },
        {
          key: 'sortOrder',
          title: t('modules.pages.materialCategories.sortOrder'),
          width: 80,
          align: 'right',
        },
        {
          key: 'purchaseWeighRequired',
          title: t('modules.pages.materialCategories.purchaseWeigh'),
          width: 100,
          render: (row) =>
            row.purchaseWeighRequired ? t('common.yes') : t('common.no'),
        },
        {
          key: 'status',
          title: t('modules.pages.materialCategories.status'),
          width: 100,
          align: 'center',
          status: true,
        },
        {
          key: 'remark',
          title: t('modules.pages.materialCategories.remark'),
          width: 200,
        },
      ],
      defaultHiddenColumnKeys: ['remark'],
      detailFields: [
        {
          key: 'categoryCode',
          label: t('modules.pages.materialCategories.categoryCode'),
        },
        {
          key: 'categoryName',
          label: t('modules.pages.materialCategories.categoryName'),
        },
        {
          key: 'sortOrder',
          label: t('modules.pages.materialCategories.sortOrder'),
        },
        {
          key: 'purchaseWeighRequired',
          label: t('modules.pages.materialCategories.purchaseWeigh'),
          render: (row) =>
            row.purchaseWeighRequired ? t('common.yes') : t('common.no'),
        },
        {
          key: 'status',
          label: t('modules.pages.materialCategories.status'),
          status: true,
        },
        {
          key: 'remark',
          label: t('modules.pages.materialCategories.remark'),
        },
      ],
      formFields: [
        {
          key: 'categoryCode',
          label: t('modules.pages.materialCategories.categoryCode'),
          type: 'input',
          disabled: true,
          placeholder: t('modules.editorWorkspace.autoGeneratedPlaceholder'),
        },
        {
          key: 'categoryName',
          label: t('modules.pages.materialCategories.categoryName'),
          type: 'input',
          required: true,
        },
        {
          key: 'sortOrder',
          label: t('modules.pages.materialCategories.sortOrder'),
          type: 'number',
          required: true,
          min: 0,
          precision: 0,
          defaultValue: 0,
        },
        {
          key: 'purchaseWeighRequired',
          label: t('modules.pages.materialCategories.purchaseWeigh'),
          type: 'select',
          defaultValue: false,
          options: [
            {
              label: t('modules.pages.materialCategories.required'),
              value: true,
            },
            {
              label: t('modules.pages.materialCategories.notRequired'),
              value: false,
            },
          ],
        },
        {
          key: 'status',
          label: t('modules.pages.materialCategories.status'),
          type: 'select',
          required: true,
          defaultValue: '正常',
          options: enabledStatusOptions,
        },
        {
          key: 'remark',
          label: t('modules.pages.materialCategories.remark'),
          type: 'textarea',
          fullRow: true,
        },
      ],
      rowHighlightStatuses: ['禁用'],
      buildValues: (record) => ({
        categoryCode: asString(record?.categoryCode),
        categoryName: asString(record?.categoryName),
        sortOrder: Number(record?.sortOrder ?? 0),
        purchaseWeighRequired: record?.purchaseWeighRequired === true,
        status: asString(record?.status) || '正常',
        remark: asString(record?.remark),
      }),
      buildRecord: (values, base) => ({
        ...(base ?? {}),
        categoryCode: asString(values.categoryCode),
        categoryName: values.categoryName,
        sortOrder: Number(values.sortOrder ?? 0),
        purchaseWeighRequired: values.purchaseWeighRequired === true,
        status: values.status,
        remark: values.remark ?? '',
      }),
    }),
    [t],
  )
  return <MasterDataListPage spec={spec} />
}
