import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import { enabledStatusOptions } from '@/constants/module-options'
import { asString } from '@/utils/type-narrowing'
import { MasterDataListPage } from './MasterDataListPage'
import type { MasterDataPageSpec } from './master-data-types'

export function SupplierPage() {
  const { t } = useTranslation()
  const spec = useMemo<MasterDataPageSpec>(
    () => ({
      moduleKey: 'supplier',
      primaryNoKey: 'supplierCode',
      title: t('modules.pages.supplier.title'),
      description: t('modules.pages.supplier.description'),
      keywordPlaceholder: t('modules.pages.supplier.placeholderKeyword'),
      filters: [
        {
          key: 'status',
          type: 'select',
          placeholder: t('modules.filter.status'),
          options: enabledStatusOptions,
        },
      ],
      columns: [
        {
          key: 'supplierCode',
          title: t('modules.pages.supplier.colSupplierCode'),
          width: 140,
        },
        {
          key: 'supplierName',
          title: t('modules.pages.supplier.colSupplierName'),
          width: 180,
        },
        {
          key: 'contactName',
          title: t('modules.pages.supplier.colContactName'),
          width: 110,
        },
        {
          key: 'contactPhone',
          title: t('modules.pages.supplier.colContactPhone'),
          width: 140,
        },
        {
          key: 'city',
          title: t('modules.pages.supplier.colCity'),
          width: 120,
        },
        {
          key: 'status',
          title: t('modules.columns.status'),
          width: 100,
          align: 'center',
          status: true,
        },
        {
          key: 'remark',
          title: t('modules.columns.remark'),
          width: 180,
        },
      ],
      defaultHiddenColumnKeys: ['contactPhone', 'city', 'remark'],
      detailFields: [
        {
          key: 'supplierCode',
          label: t('modules.pages.supplier.colSupplierCode'),
        },
        {
          key: 'supplierName',
          label: t('modules.pages.supplier.colSupplierName'),
        },
        {
          key: 'contactName',
          label: t('modules.pages.supplier.colContactName'),
        },
        {
          key: 'contactPhone',
          label: t('modules.pages.supplier.colContactPhone'),
        },
        { key: 'city', label: t('modules.pages.supplier.colCity') },
        {
          key: 'status',
          label: t('modules.columns.status'),
          status: true,
        },
        { key: 'remark', label: t('modules.columns.remark') },
      ],
      formFields: [
        {
          key: 'supplierCode',
          label: t('modules.pages.supplier.colSupplierCode'),
          type: 'input',
          disabled: true,
          placeholder: t('modules.editorWorkspace.autoGeneratedPlaceholder'),
        },
        {
          key: 'supplierName',
          label: t('modules.pages.supplier.colSupplierName'),
          type: 'input',
          required: true,
        },
        {
          key: 'contactName',
          label: t('modules.pages.supplier.colContactName'),
          type: 'input',
        },
        {
          key: 'contactPhone',
          label: t('modules.pages.supplier.colContactPhone'),
          type: 'input',
        },
        {
          key: 'city',
          label: t('modules.pages.supplier.colCity'),
          type: 'input',
        },
        {
          key: 'status',
          label: t('modules.columns.status'),
          type: 'select',
          defaultValue: '正常',
          options: enabledStatusOptions,
        },
        {
          key: 'remark',
          label: t('modules.columns.remark'),
          type: 'textarea',
          fullRow: true,
        },
      ],
      rowHighlightStatuses: ['禁用'],
      buildValues: (record) => ({
        supplierCode: asString(record?.supplierCode),
        supplierName: asString(record?.supplierName),
        contactName: asString(record?.contactName),
        contactPhone: asString(record?.contactPhone),
        city: asString(record?.city),
        status: asString(record?.status) || '正常',
        remark: asString(record?.remark),
      }),
      buildRecord: (values, base) => ({
        ...(base ?? {}),
        supplierCode: asString(values.supplierCode),
        supplierName: values.supplierName,
        contactName: values.contactName ?? '',
        contactPhone: values.contactPhone ?? '',
        city: values.city ?? '',
        status: values.status,
        remark: values.remark ?? '',
      }),
    }),
    [t],
  )
  return <MasterDataListPage spec={spec} />
}
