import type { TFunction } from 'i18next'
import type { ReactNode } from 'react'
import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import { enabledStatusOptions } from '@/constants/module-options'
import { STATUS } from '@/constants/status-constants'
import { useMaterialBrands } from '@/hooks/useMaterialBrands'
import { asString } from '@/utils/type-narrowing'
import { MasterDataListPage } from './MasterDataListPage'
import type { MasterDataPageSpec, MasterOption } from './master-data-types'

const asBrandList = (value: unknown): string[] =>
  Array.isArray(value)
    ? value.flatMap((item) => {
        const brand = asString(item).trim()
        return brand ? [brand] : []
      })
    : []

function formatBrands(value: unknown): ReactNode {
  const brands = asBrandList(value)
  return brands.length ? brands.join('、') : '-'
}

export function buildSupplierSpec(
  t: TFunction,
  brandOptions: MasterOption[],
): MasterDataPageSpec {
  return {
    moduleKey: 'supplier',
    primaryNoKey: 'supplierCode',
    title: t('modules.pages.supplier.title'),
    description: t('modules.pages.supplier.description'),
    keywordPlaceholder: t('modules.pages.supplier.placeholderKeyword'),
    filters: [
      {
        key: 'status',
        type: 'select',
        placeholder: t('modules.filter.status'),
        options: enabledStatusOptions,
      },
    ],
    columns: [
      {
        key: 'supplierCode',
        title: t('modules.pages.supplier.colSupplierCode'),
        width: 140,
      },
      {
        key: 'supplierName',
        title: t('modules.pages.supplier.colSupplierName'),
        width: 180,
      },
      {
        key: 'shortName',
        title: t('modules.pages.supplier.colShortName'),
        width: 120,
      },
      {
        key: 'brands',
        title: t('modules.pages.supplier.colBrands'),
        width: 200,
        render: (row) => formatBrands(row.brands),
      },
      {
        key: 'contactName',
        title: t('modules.pages.supplier.colContactName'),
        width: 110,
      },
      {
        key: 'contactPhone',
        title: t('modules.pages.supplier.colContactPhone'),
        width: 140,
      },
      {
        key: 'city',
        title: t('modules.pages.supplier.colCity'),
        width: 120,
      },
      {
        key: 'status',
        title: t('modules.columns.status'),
        width: 100,
        align: 'center',
        status: true,
      },
      {
        key: 'remark',
        title: t('modules.columns.remark'),
        width: 180,
      },
    ],
    defaultHiddenColumnKeys: ['brands', 'contactPhone', 'city', 'remark'],
    detailFields: [
      {
        key: 'supplierCode',
        label: t('modules.pages.supplier.colSupplierCode'),
      },
      {
        key: 'supplierName',
        label: t('modules.pages.supplier.colSupplierName'),
      },
      {
        key: 'shortName',
        label: t('modules.pages.supplier.colShortName'),
      },
      {
        key: 'brands',
        label: t('modules.pages.supplier.colBrands'),
        render: (row) => formatBrands(row.brands),
      },
      {
        key: 'contactName',
        label: t('modules.pages.supplier.colContactName'),
      },
      {
        key: 'contactPhone',
        label: t('modules.pages.supplier.colContactPhone'),
      },
      { key: 'city', label: t('modules.pages.supplier.colCity') },
      {
        key: 'status',
        label: t('modules.columns.status'),
        status: true,
      },
      { key: 'remark', label: t('modules.columns.remark') },
    ],
    formFields: [
      {
        key: 'supplierCode',
        label: t('modules.pages.supplier.colSupplierCode'),
        type: 'input',
        disabled: true,
        placeholder: t('modules.editorWorkspace.autoGeneratedPlaceholder'),
      },
      {
        key: 'supplierName',
        label: t('modules.pages.supplier.colSupplierName'),
        type: 'input',
        required: true,
      },
      {
        key: 'shortName',
        label: t('modules.pages.supplier.colShortName'),
        type: 'input',
      },
      {
        key: 'brands',
        label: t('modules.pages.supplier.colBrands'),
        type: 'select',
        multiple: true,
        fullRow: true,
        options: brandOptions,
      },
      {
        key: 'contactName',
        label: t('modules.pages.supplier.colContactName'),
        type: 'input',
      },
      {
        key: 'contactPhone',
        label: t('modules.pages.supplier.colContactPhone'),
        type: 'input',
      },
      {
        key: 'city',
        label: t('modules.pages.supplier.colCity'),
        type: 'input',
      },
      {
        key: 'status',
        label: t('modules.columns.status'),
        type: 'select',
        defaultValue: STATUS.NORMAL,
        options: enabledStatusOptions,
      },
      {
        key: 'remark',
        label: t('modules.columns.remark'),
        type: 'textarea',
        fullRow: true,
      },
    ],
    rowHighlightStatuses: [STATUS.DISABLED],
    buildValues: (record) => ({
      supplierCode: asString(record?.supplierCode),
      supplierName: asString(record?.supplierName),
      shortName: asString(record?.shortName),
      brands: asBrandList(record?.brands),
      contactName: asString(record?.contactName),
      contactPhone: asString(record?.contactPhone),
      city: asString(record?.city),
      status: asString(record?.status) || STATUS.NORMAL,
      remark: asString(record?.remark),
    }),
    buildRecord: (values, base) => ({
      ...(base ?? {}),
      supplierCode: asString(values.supplierCode),
      supplierName: values.supplierName,
      shortName: values.shortName ?? '',
      brands: asBrandList(values.brands),
      contactName: values.contactName ?? '',
      contactPhone: values.contactPhone ?? '',
      city: values.city ?? '',
      status: values.status,
      remark: values.remark ?? '',
    }),
  }
}

export function SupplierPage() {
  const { t } = useTranslation()
  const materialBrands = useMaterialBrands()
  const brandOptions = useMemo<MasterOption[]>(
    () => materialBrands.map((brand) => ({ label: brand, value: brand })),
    [materialBrands],
  )
  const spec = useMemo(
    () => buildSupplierSpec(t, brandOptions),
    [t, brandOptions],
  )
  return <MasterDataListPage spec={spec} />
}
