import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import { enabledStatusOptions } from '@/constants/module-options'
import { asString } from '@/utils/type-narrowing'
import { MasterDataListPage } from './MasterDataListPage'
import type { MasterDataPageSpec } from './master-data-types'

const WAREHOUSE_TYPE_OPTIONS = [
  '自营仓',
  '合作仓',
  '中转仓',
  '第三方仓',
] as const

export function WarehousePage() {
  const { t } = useTranslation()
  const spec = useMemo<MasterDataPageSpec>(() => {
    const warehouseTypeOptions = [
      {
        label: t('modules.pages.masterWarehouse.ownWarehouse'),
        value: '自营仓',
      },
      {
        label: t('modules.pages.masterWarehouse.partnerWarehouse'),
        value: '合作仓',
      },
      {
        label: t('modules.pages.masterWarehouse.transitWarehouse'),
        value: '中转仓',
      },
      {
        label: t('modules.pages.masterWarehouse.thirdPartyWarehouse'),
        value: '第三方仓',
      },
    ]
    return {
      moduleKey: 'warehouse',
      title: t('modules.pages.masterWarehouse.warehouseMaster'),
      description: t('modules.pages.masterWarehouse.warehouseDesc'),
      keywordPlaceholder: t(
        'modules.pages.masterWarehouse.warehousePlaceholder',
      ),
      filters: [
        {
          key: 'warehouseType',
          type: 'select',
          placeholder: t('modules.pages.masterWarehouse.warehouseType'),
          options: warehouseTypeOptions,
        },
        {
          key: 'status',
          type: 'select',
          placeholder: t('modules.filter.status'),
          options: enabledStatusOptions,
        },
      ],
      columns: [
        {
          key: 'warehouseCode',
          title: t('modules.pages.masterWarehouse.warehouseCode'),
          width: 140,
        },
        {
          key: 'warehouseName',
          title: t('modules.pages.masterWarehouse.warehouseName'),
          width: 160,
        },
        {
          key: 'warehouseType',
          title: t('modules.pages.masterWarehouse.warehouseType'),
          width: 110,
        },
        {
          key: 'contactName',
          title: t('modules.pages.masterWarehouse.contact'),
          width: 110,
        },
        {
          key: 'contactPhone',
          title: t('modules.pages.masterWarehouse.phone'),
          width: 140,
        },
        {
          key: 'address',
          title: t('modules.pages.masterWarehouse.address'),
          width: 240,
        },
        {
          key: 'status',
          title: t('modules.pages.masterWarehouse.status'),
          width: 100,
          align: 'center',
          status: true,
        },
        {
          key: 'remark',
          title: t('modules.pages.masterWarehouse.remark'),
          width: 180,
        },
      ],
      defaultHiddenColumnKeys: ['contactPhone', 'address', 'remark'],
      detailFields: [
        {
          key: 'warehouseCode',
          label: t('modules.pages.masterWarehouse.warehouseCode'),
        },
        {
          key: 'warehouseName',
          label: t('modules.pages.masterWarehouse.warehouseName'),
        },
        {
          key: 'warehouseType',
          label: t('modules.pages.masterWarehouse.warehouseType'),
        },
        {
          key: 'contactName',
          label: t('modules.pages.masterWarehouse.contact'),
        },
        {
          key: 'contactPhone',
          label: t('modules.pages.masterWarehouse.phone'),
        },
        {
          key: 'address',
          label: t('modules.pages.masterWarehouse.address'),
        },
        {
          key: 'status',
          label: t('modules.pages.masterWarehouse.status'),
          status: true,
        },
        {
          key: 'remark',
          label: t('modules.pages.masterWarehouse.remark'),
        },
      ],
      formFields: [
        {
          key: 'warehouseCode',
          label: t('modules.pages.masterWarehouse.warehouseCode'),
          type: 'input',
          disabled: true,
          placeholder: t('modules.editorWorkspace.autoGeneratedPlaceholder'),
        },
        {
          key: 'warehouseName',
          label: t('modules.pages.masterWarehouse.warehouseName'),
          type: 'input',
          required: true,
        },
        {
          key: 'warehouseType',
          label: t('modules.pages.masterWarehouse.warehouseType'),
          type: 'select',
          required: true,
          options: warehouseTypeOptions,
        },
        {
          key: 'contactName',
          label: t('modules.pages.masterWarehouse.contact'),
          type: 'input',
        },
        {
          key: 'contactPhone',
          label: t('modules.pages.masterWarehouse.phone'),
          type: 'input',
        },
        {
          key: 'address',
          label: t('modules.pages.masterWarehouse.address'),
          type: 'input',
          fullRow: true,
        },
        {
          key: 'status',
          label: t('modules.pages.masterWarehouse.status'),
          type: 'select',
          defaultValue: '正常',
          options: enabledStatusOptions,
        },
        {
          key: 'remark',
          label: t('modules.pages.masterWarehouse.remark'),
          type: 'textarea',
          fullRow: true,
        },
      ],
      rowHighlightStatuses: ['禁用'],
      buildValues: (record) => ({
        warehouseCode: asString(record?.warehouseCode),
        warehouseName: asString(record?.warehouseName),
        warehouseType:
          asString(record?.warehouseType) || WAREHOUSE_TYPE_OPTIONS[0],
        contactName: asString(record?.contactName),
        contactPhone: asString(record?.contactPhone),
        address: asString(record?.address),
        status: asString(record?.status) || '正常',
        remark: asString(record?.remark),
      }),
      buildRecord: (values, base) => ({
        ...(base ?? {}),
        warehouseCode: asString(values.warehouseCode),
        warehouseName: values.warehouseName,
        warehouseType: values.warehouseType,
        contactName: values.contactName ?? '',
        contactPhone: values.contactPhone ?? '',
        address: values.address ?? '',
        status: values.status,
        remark: values.remark ?? '',
      }),
    }
  }, [t])
  return <MasterDataListPage spec={spec} />
}
