import { enabledStatusOptions } from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import { actionSet, buildMasterOverview, statusMap } from './shared'
import { masterStatusFilter } from './shared-filters'

export const carriersPageConfig: ModulePageConfig = {
  key: 'carrier',
  title: '物流方资料',
  kicker: 'Master Data',
  description:
    '物流方主数据统一维护承运商档案、车型和合作状态，供物流单与物流对账复用。',
  primaryNoKey: 'carrierCode',
  actions: actionSet,
  filters: [
    {
      key: 'keyword',
      label: '关键字',
      type: 'input',
      placeholder: '物流方编码 / 名称 / 联系人',
    },
    { ...masterStatusFilter },
  ],
  columns: [
    { title: '物流方编码', dataIndex: 'carrierCode', width: 140 },
    { title: '物流方名称', dataIndex: 'carrierName', width: 180 },
    { title: '联系人', dataIndex: 'contactName', width: 110 },
    { title: '联系电话', dataIndex: 'contactPhone', width: 140 },
    { title: '车牌号', dataIndex: 'vehicleType', width: 120 },
    {
      title: '计费模式',
      dataIndex: 'priceMode',
      width: 100,
      align: 'center',
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      type: 'status',
      align: 'center',
    },
    { title: '备注', dataIndex: 'remark', width: 180 },
  ],
  detailFields: [
    { label: '物流方编码', key: 'carrierCode' },
    { label: '物流方名称', key: 'carrierName' },
    { label: '联系人', key: 'contactName' },
    { label: '联系电话', key: 'contactPhone' },
    { label: '车牌号', key: 'vehiclePlate' },
    { label: '车辆联系人', key: 'vehicleContact' },
    { label: '车辆联系电话', key: 'vehiclePhone' },
    { label: '车牌号2', key: 'vehiclePlate2' },
    { label: '车辆联系人2', key: 'vehicleContact2' },
    { label: '车辆联系电话2', key: 'vehiclePhone2' },
    { label: '车牌号3', key: 'vehiclePlate3' },
    { label: '车辆联系人3', key: 'vehicleContact3' },
    { label: '车辆联系电话3', key: 'vehiclePhone3' },
    { label: '计费模式', key: 'priceMode' },
    { label: '状态', key: 'status', type: 'status' },
    { label: '备注', key: 'remark' },
  ],
  detailColumnCount: 4,
  formFields: [
    {
      key: 'carrierCode',
      label: '物流方编码',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'carrierName',
      label: '物流方名称',
      type: 'input',
      required: true,
      row: 1,
    },
    { key: 'contactName', label: '联系人', type: 'input', row: 1 },
    { key: 'contactPhone', label: '联系电话', type: 'input', row: 1 },
    { key: 'vehiclePlate', label: '车辆1-车牌号', type: 'input', row: 2 },
    { key: 'vehicleContact', label: '车辆1-联系人', type: 'input', row: 2 },
    { key: 'vehiclePhone', label: '车辆1-手机号', type: 'input', row: 2 },
    { key: 'vehicleRemark', label: '车辆1-备注', type: 'input', row: 2 },
    { key: 'vehiclePlate2', label: '车辆2-车牌号', type: 'input', row: 3 },
    { key: 'vehicleContact2', label: '车辆2-联系人', type: 'input', row: 3 },
    { key: 'vehiclePhone2', label: '车辆2-手机号', type: 'input', row: 3 },
    { key: 'vehicleRemark2', label: '车辆2-备注', type: 'input', row: 3 },
    { key: 'vehiclePlate3', label: '车辆3-车牌号', type: 'input', row: 4 },
    { key: 'vehicleContact3', label: '车辆3-联系人', type: 'input', row: 4 },
    { key: 'vehiclePhone3', label: '车辆3-手机号', type: 'input', row: 4 },
    { key: 'vehicleRemark3', label: '车辆3-备注', type: 'input', row: 4 },
    {
      key: 'status',
      label: '状态',
      type: 'select',
      defaultValue: '正常',
      options: enabledStatusOptions,
      row: 5,
    },
    { key: 'remark', label: '备注', type: 'textarea', row: 6, fullRow: true },
  ],
  data: [],
  buildOverview: (rows) => buildMasterOverview(rows),
  statusMap,
  rowHighlightStatuses: ['禁用'],
}
