import {
  customerOptions,
  statementStatusOptions,
} from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import { BILL_STATUS_LABEL, CUSTOMER_NAME_LABEL } from './filter-labels'
import {
  buildStatementOverview,
  compactBatchCustomerStatementItemColumns,
  statusMap,
} from './shared'

export const customerStatementPageConfig: ModulePageConfig = {
  key: 'customer-statement',
  title: '客户对账单',
  kicker: 'Statements',
  description:
    '客户对账单按已完成销售的销售订单明细口径组织，生成后保留来源订单行，便于逐项核对销售数量、单价和金额。',
  primaryNoKey: 'statementNo',
  actions: [
    { key: 'generate_statement', label: '生成对账单', type: 'primary' },
  ],
  filters: [
    {
      key: 'customerName',
      label: CUSTOMER_NAME_LABEL,
      type: 'select',
      options: customerOptions,
    },
    {
      key: 'status',
      label: BILL_STATUS_LABEL,
      type: 'select',
      options: statementStatusOptions,
    },
    { key: 'endDate', label: '账期', type: 'dateRange' },
  ],
  columns: [
    { title: '对账单号', dataIndex: 'statementNo', width: 170 },
    { title: '客户', dataIndex: 'customerName', width: 140 },
    { title: '项目', dataIndex: 'projectName', width: 180 },
    { title: '开始日期', dataIndex: 'startDate', width: 120, type: 'date' },
    { title: '结束日期', dataIndex: 'endDate', width: 120, type: 'date' },
    {
      title: '销售金额',
      dataIndex: 'salesAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '收款金额',
      dataIndex: 'receiptAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '期末余额',
      dataIndex: 'closingAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
  ],
  defaultHiddenColumnKeys: ['projectName', 'receiptAmount'],
  detailFields: [
    { label: '对账单号', key: 'statementNo' },
    { label: '客户', key: 'customerName' },
    { label: '项目', key: 'projectName' },
    { label: '开始日期', key: 'startDate', type: 'date' },
    { label: '结束日期', key: 'endDate', type: 'date' },
    { label: '销售金额', key: 'salesAmount', type: 'amount' },
    { label: '收款金额', key: 'receiptAmount', type: 'amount' },
    { label: '期末余额', key: 'closingAmount', type: 'amount' },
    { label: '状态', key: 'status', type: 'status' },
    { label: '备注', key: 'remark' },
  ],
  formFields: [
    {
      key: 'statementNo',
      label: '对账单号',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'customerName',
      label: '客户',
      type: 'select',
      required: true,
      options: customerOptions,
      row: 1,
    },
    {
      key: 'projectName',
      label: '项目',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'startDate',
      label: '开始日期',
      type: 'date',
      required: true,
      row: 1,
    },
    { key: 'endDate', label: '结束日期', type: 'date', required: true, row: 2 },
    {
      key: 'salesAmount',
      label: '销售金额',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 2,
    },
    {
      key: 'closingAmount',
      label: '期末余额',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 2,
    },
    {
      key: 'status',
      label: '状态',
      type: 'select',
      defaultValue: '待确认',
      options: statementStatusOptions,
      row: 2,
    },
    { key: 'remark', label: '备注', type: 'textarea', row: 3, fullRow: true },
  ],
  saveFields: {
    scalar: [
      'statementNo',
      'sourceOrderNos',
      'customerName',
      'projectName',
      'startDate',
      'endDate',
      'salesAmount',
      'receiptAmount',
      'closingAmount',
      'status',
      'remark',
    ],
    lineItem: [
      'sourceNo',
      'materialCode',
      'brand',
      'category',
      'material',
      'spec',
      'length',
      'unit',
      'batchNo',
      'quantity',
      'quantityUnit',
      'pieceWeightTon',
      'piecesPerBundle',
      'weightTon',
      'unitPrice',
      'amount',
    ],
  },
  itemColumns: compactBatchCustomerStatementItemColumns,
  data: [],
  buildOverview: (rows) =>
    buildStatementOverview(
      rows,
      'salesAmount',
      'receiptAmount',
      'closingAmount',
    ),
  statusMap,
  rowHighlightStatuses: ['待确认'],
}
