import {
  customerOptions,
  statementStatusOptions,
} from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import { BILL_STATUS_LABEL, CUSTOMER_NAME_LABEL } from './filter-labels'
import {
  buildStatementOverview,
  compactBatchCustomerStatementItemColumns,
  statusMap,
} from './shared'
import i18next from 'i18next'

export const customerStatementPageConfig: ModulePageConfig = {
  key: 'customer-statement',
  title: i18next.t('modules.pages.customerStatement.customerStatement'),
  kicker: 'Statements',
  description:
    i18next.t('modules.pages.customerStatement.customerStatementDesc'),
  primaryNoKey: 'statementNo',
  actions: [
    { key: 'generate_statement', label: i18next.t('modules.pages.customerStatement.generateStatement'), type: 'primary' },
  ],
  filters: [
    {
      key: 'customerName',
      label: CUSTOMER_NAME_LABEL,
      type: 'select',
      options: customerOptions,
    },
    {
      key: 'status',
      label: BILL_STATUS_LABEL,
      type: 'select',
      options: statementStatusOptions,
    },
    { key: 'endDate', label: i18next.t('modules.pages.customerStatement.period'), type: 'dateRange' },
  ],
  columns: [
    { title: i18next.t('modules.pages.customerStatement.statementNo'), dataIndex: 'statementNo', width: 170 },
    { title: i18next.t('modules.pages.customerStatement.customer'), dataIndex: 'customerName', width: 140 },
    { title: i18next.t('modules.pages.customerStatement.project'), dataIndex: 'projectName', width: 180 },
    { title: i18next.t('modules.pages.customerStatement.startDate'), dataIndex: 'startDate', width: 120, type: 'date' },
    { title: i18next.t('modules.pages.customerStatement.endDate'), dataIndex: 'endDate', width: 120, type: 'date' },
    {
      title: i18next.t('modules.pages.customerStatement.salesAmount'),
      dataIndex: 'salesAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: i18next.t('modules.pages.customerStatement.receiptAmount'),
      dataIndex: 'receiptAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: i18next.t('modules.pages.customerStatement.closingBalance'),
      dataIndex: 'closingAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: i18next.t('modules.pages.customerStatement.status'),
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
  ],
  defaultHiddenColumnKeys: ['projectName', 'receiptAmount'],
  detailFields: [
    { label: i18next.t('modules.pages.customerStatement.statementNo'), key: 'statementNo' },
    { label: i18next.t('modules.pages.customerStatement.customer'), key: 'customerName' },
    { label: i18next.t('modules.pages.customerStatement.project'), key: 'projectName' },
    { label: i18next.t('modules.pages.customerStatement.startDate'), key: 'startDate', type: 'date' },
    { label: i18next.t('modules.pages.customerStatement.endDate'), key: 'endDate', type: 'date' },
    { label: i18next.t('modules.pages.customerStatement.salesAmount'), key: 'salesAmount', type: 'amount' },
    { label: i18next.t('modules.pages.customerStatement.receiptAmount'), key: 'receiptAmount', type: 'amount' },
    { label: i18next.t('modules.pages.customerStatement.closingBalance'), key: 'closingAmount', type: 'amount' },
    { label: i18next.t('modules.pages.customerStatement.status'), key: 'status', type: 'status' },
    { label: i18next.t('modules.pages.customerStatement.remark'), key: 'remark' },
  ],
  formFields: [
    {
      key: 'statementNo',
      label: i18next.t('modules.pages.customerStatement.statementNo'),
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'customerName',
      label: i18next.t('modules.pages.customerStatement.customer'),
      type: 'select',
      required: true,
      options: customerOptions,
      row: 1,
    },
    {
      key: 'projectName',
      label: i18next.t('modules.pages.customerStatement.project'),
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'startDate',
      label: i18next.t('modules.pages.customerStatement.startDate'),
      type: 'date',
      required: true,
      row: 1,
    },
    { key: 'endDate', label: i18next.t('modules.pages.customerStatement.endDate'), type: 'date', required: true, row: 2 },
    {
      key: 'salesAmount',
      label: i18next.t('modules.pages.customerStatement.salesAmount'),
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 2,
    },
    {
      key: 'closingAmount',
      label: i18next.t('modules.pages.customerStatement.closingBalance'),
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 2,
    },
    {
      key: 'status',
      label: i18next.t('modules.pages.customerStatement.status'),
      type: 'select',
      defaultValue: '待确认',
      options: statementStatusOptions,
      row: 2,
    },
    { key: 'remark', label: i18next.t('modules.pages.customerStatement.remark'), type: 'textarea', row: 3, fullRow: true },
  ],
  saveFields: {
    scalar: [
      'statementNo',
      'sourceOrderNos',
      'customerName',
      'projectName',
      'startDate',
      'endDate',
      'salesAmount',
      'receiptAmount',
      'closingAmount',
      'status',
      'remark',
    ],
    lineItem: [
      'sourceNo',
      'materialCode',
      'brand',
      'category',
      'material',
      'spec',
      'length',
      'unit',
      'batchNo',
      'quantity',
      'quantityUnit',
      'pieceWeightTon',
      'piecesPerBundle',
      'weightTon',
      'unitPrice',
      'amount',
    ],
  },
  itemColumns: compactBatchCustomerStatementItemColumns,
  data: [],
  buildOverview: (rows) =>
    buildStatementOverview(
      rows,
      'salesAmount',
      'receiptAmount',
      'closingAmount',
    ),
  statusMap,
  rowHighlightStatuses: ['待确认'],
}
