import type { ModulePageConfig } from '@/types/module-page'
import {
  buildValueOptions,
  customerOptions,
  getCarrierOptions,
  getMaterialCategoryOptions,
  getCustomerProjectOptions,
  getSupplierOptions,
  statementStatusOptions,
  getWarehouseOptions,
} from '@/constants/module-options'
import {
  buildFinanceOverview,
  buildStatementOverview,
  compactBatchCustomerStatementItemColumns,
  compactBatchSupplierStatementItemColumns,
  compactInvoiceIssueItemColumns,
  compactInvoiceReceiptItemColumns,
  formatAmount,
  formatInteger,
  formatWeight,
  freightItemColumns,
  statusMap,
  sumBy,
} from './shared'

export const financeAndReportPageConfigs: Record<string, ModulePageConfig> = {
  'inventory-report': {
    key: 'inventory-report',
    title: '商品库存报表',
    kicker: 'Reports',
    description: '库存报表按商品编码、材质、类别、规格、长度、仓库、批号展示结存结果，便于先确认前端字段和查询交互。',
    readOnly: true,
    actions: [{ label: '导出', type: 'primary' }],
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '商品编码 / 品牌 / 规格' },
      { key: 'warehouseName', label: '仓库', type: 'select', options: getWarehouseOptions },
      { key: 'category', label: '类别', type: 'select', options: getMaterialCategoryOptions },
    ],
    columns: [
      { title: '商品编码', dataIndex: 'materialCode', width: 150 },
      { title: '品牌', dataIndex: 'brand', width: 120 },
      { title: '材质', dataIndex: 'material', width: 120 },
      { title: '类别', dataIndex: 'category', width: 110 },
      { title: '规格', dataIndex: 'spec', width: 100 },
      { title: '长度', dataIndex: 'length', width: 100 },
      { title: '仓库', dataIndex: 'warehouseName', width: 110 },
      { title: '批号', dataIndex: 'batchNo', width: 140 },
      { title: '数量', dataIndex: 'quantity', width: 100, align: 'right', type: 'count' },
      { title: '数量单位', dataIndex: 'quantityUnit', width: 90 },
      { title: '结存重量（吨）', dataIndex: 'weightTon', width: 124, align: 'right', type: 'weight' },
    ],
    detailFields: [
      { label: '商品编码', key: 'materialCode' },
      { label: '品牌', key: 'brand' },
      { label: '材质', key: 'material' },
      { label: '类别', key: 'category' },
      { label: '规格', key: 'spec' },
      { label: '长度', key: 'length' },
      { label: '仓库', key: 'warehouseName' },
      { label: '批号', key: 'batchNo' },
      { label: '数量', key: 'quantity', type: 'count' },
      { label: '数量单位', key: 'quantityUnit' },
      { label: '结存重量（吨）', key: 'weightTon', type: 'weight' },
      { label: '每件件重（吨）', key: 'pieceWeightTon', type: 'weight' },
      { label: '单位', key: 'unit' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '库存记录', value: formatInteger(rows.length) },
      { label: '结存重量（吨）', value: formatWeight(sumBy(rows, 'weightTon')) },
    ],
  },
  'io-report': {
    key: 'io-report',
    title: '出入库报表',
    kicker: 'Reports',
    description: '出入库报表用于查看业务流水，统一展示查询区、流水表格和明细字段，方便继续接库存与追溯链路。',
    readOnly: true,
    actions: [{ label: '导出', type: 'primary' }],
    filters: [
      { key: 'keyword', label: '来源单号', type: 'input', placeholder: '输入来源单号' },
      { key: 'businessType', label: '业务类型', type: 'select', options: [
        { label: '采购入库', value: '采购入库' },
        { label: '销售出库', value: '销售出库' },
      ] },
      { key: 'businessDate', label: '业务日期', type: 'dateRange' },
    ],
    columns: [
      { title: '业务日期', dataIndex: 'businessDate', width: 120, type: 'date' },
      { title: '业务类型', dataIndex: 'businessType', width: 120 },
      { title: '来源单号', dataIndex: 'sourceNo', width: 160 },
      { title: '商品编码', dataIndex: 'materialCode', width: 140 },
      { title: '品牌', dataIndex: 'brand', width: 110 },
      { title: '规格', dataIndex: 'spec', width: 100 },
      { title: '仓库', dataIndex: 'warehouseName', width: 110 },
      { title: '批号', dataIndex: 'batchNo', width: 140 },
      { title: '入库数量', dataIndex: 'inQuantity', width: 100, align: 'right', type: 'count' },
      { title: '出库数量', dataIndex: 'outQuantity', width: 100, align: 'right', type: 'count' },
      { title: '数量单位', dataIndex: 'quantityUnit', width: 90 },
      { title: '入库重量（吨）', dataIndex: 'inWeightTon', width: 124, align: 'right', type: 'weight' },
      { title: '出库重量（吨）', dataIndex: 'outWeightTon', width: 124, align: 'right', type: 'weight' },
    ],
    detailFields: [
      { label: '业务日期', key: 'businessDate', type: 'date' },
      { label: '业务类型', key: 'businessType' },
      { label: '来源单号', key: 'sourceNo' },
      { label: '商品编码', key: 'materialCode' },
      { label: '品牌', key: 'brand' },
      { label: '规格', key: 'spec' },
      { label: '仓库', key: 'warehouseName' },
      { label: '批号', key: 'batchNo' },
      { label: '入库数量', key: 'inQuantity', type: 'count' },
      { label: '出库数量', key: 'outQuantity', type: 'count' },
      { label: '数量单位', key: 'quantityUnit' },
      { label: '入库重量（吨）', key: 'inWeightTon', type: 'weight' },
      { label: '出库重量（吨）', key: 'outWeightTon', type: 'weight' },
      { label: '备注', key: 'remark' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '流水数', value: formatInteger(rows.length) },
      { label: '入库重量（吨）', value: formatWeight(sumBy(rows, 'inWeightTon')) },
      { label: '出库重量（吨）', value: formatWeight(sumBy(rows, 'outWeightTon')) },
    ],
  },
  'pending-invoice-receipt-report': {
    key: 'pending-invoice-receipt-report',
    title: '未收票报表',
    kicker: 'Finance',
    description: '未收票报表按采购订单明细对比已收票明细，展示尚未收票的剩余重量（吨）与金额，供采购和财务快速追踪到票进度。',
    readOnly: true,
    actions: [{ label: '导出', type: 'primary' }],
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '采购单号 / 供应商 / 商品编码 / 规格' },
      { key: 'supplierName', label: '供应商', type: 'select', options: getSupplierOptions },
      { key: 'orderDate', label: '采购日期', type: 'dateRange' },
    ],
    columns: [
      { title: '采购订单号', dataIndex: 'orderNo', width: 170 },
      { title: '供应商', dataIndex: 'supplierName', width: 150 },
      { title: '开票方抬头', dataIndex: 'invoiceTitle', width: 170 },
      { title: '采购日期', dataIndex: 'orderDate', width: 120, type: 'date' },
      { title: '商品编码', dataIndex: 'materialCode', width: 140 },
      { title: '品牌', dataIndex: 'brand', width: 110 },
      { title: '材质', dataIndex: 'material', width: 110 },
      { title: '类别', dataIndex: 'category', width: 100 },
      { title: '规格', dataIndex: 'spec', width: 100 },
      { title: '长度', dataIndex: 'length', width: 100 },
      { title: '订单数量', dataIndex: 'orderQuantity', width: 100, align: 'right', type: 'count' },
      { title: '数量单位', dataIndex: 'quantityUnit', width: 90 },
      { title: '订单重量（吨）', dataIndex: 'orderWeightTon', width: 124, align: 'right', type: 'weight' },
      { title: '已收票重量（吨）', dataIndex: 'receivedInvoiceWeightTon', width: 136, align: 'right', type: 'weight' },
      { title: '未收票重量（吨）', dataIndex: 'pendingInvoiceWeightTon', width: 136, align: 'right', type: 'weight' },
      { title: '单价', dataIndex: 'unitPrice', width: 100, align: 'right', type: 'amount' },
      { title: '订单金额', dataIndex: 'orderAmount', width: 110, align: 'right', type: 'amount' },
      { title: '已收票金额', dataIndex: 'receivedInvoiceAmount', width: 110, align: 'right', type: 'amount' },
      { title: '未收票金额', dataIndex: 'pendingInvoiceAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '采购订单号', key: 'orderNo' },
      { label: '供应商', key: 'supplierName' },
      { label: '开票方抬头', key: 'invoiceTitle' },
      { label: '采购日期', key: 'orderDate', type: 'date' },
      { label: '商品编码', key: 'materialCode' },
      { label: '品牌', key: 'brand' },
      { label: '材质', key: 'material' },
      { label: '类别', key: 'category' },
      { label: '规格', key: 'spec' },
      { label: '长度', key: 'length' },
      { label: '订单数量', key: 'orderQuantity', type: 'count' },
      { label: '数量单位', key: 'quantityUnit' },
      { label: '订单重量（吨）', key: 'orderWeightTon', type: 'weight' },
      { label: '已收票重量（吨）', key: 'receivedInvoiceWeightTon', type: 'weight' },
      { label: '未收票重量（吨）', key: 'pendingInvoiceWeightTon', type: 'weight' },
      { label: '单价', key: 'unitPrice', type: 'amount' },
      { label: '订单金额', key: 'orderAmount', type: 'amount' },
      { label: '已收票金额', key: 'receivedInvoiceAmount', type: 'amount' },
      { label: '未收票金额', key: 'pendingInvoiceAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '待跟进明细', value: formatInteger(rows.length) },
      { label: '未收票重量（吨）', value: formatWeight(sumBy(rows, 'pendingInvoiceWeightTon')) },
      { label: '未收票金额', value: formatAmount(sumBy(rows, 'pendingInvoiceAmount')) },
    ],
    statusMap,
    rowHighlightStatuses: ['未收票'],
  },
  'supplier-statements': {
    key: 'supplier-statements',
    title: '供应商对账单',
    kicker: 'Statements',
    description: '供应商对账单按已审核采购入库明细口径组织，生成后保留来源入库行，便于逐项核对采购数量、单价和金额。',
    primaryNoKey: 'statementNo',
    actions: [{ label: '生成对账单', type: 'primary' }],
    filters: [
      { key: 'supplierName', label: '供应商', type: 'select', options: getSupplierOptions },
      { key: 'status', label: '状态', type: 'select', options: statementStatusOptions },
      { key: 'endDate', label: '账期', type: 'dateRange' },
    ],
    columns: [
      { title: '对账单号', dataIndex: 'statementNo', width: 170 },
      { title: '供应商', dataIndex: 'supplierName', width: 140 },
      { title: '开始日期', dataIndex: 'startDate', width: 120, type: 'date' },
      { title: '结束日期', dataIndex: 'endDate', width: 120, type: 'date' },
      { title: '采购金额', dataIndex: 'purchaseAmount', width: 110, align: 'right', type: 'amount' },
      { title: '付款金额', dataIndex: 'paymentAmount', width: 110, align: 'right', type: 'amount' },
      { title: '期末余额', dataIndex: 'closingAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '对账单号', key: 'statementNo' },
      { label: '供应商', key: 'supplierName' },
      { label: '开始日期', key: 'startDate', type: 'date' },
      { label: '结束日期', key: 'endDate', type: 'date' },
      { label: '采购金额', key: 'purchaseAmount', type: 'amount' },
      { label: '付款金额', key: 'paymentAmount', type: 'amount' },
      { label: '期末余额', key: 'closingAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'statementNo', label: '对账单号', type: 'input', required: true },
      { key: 'supplierName', label: '供应商', type: 'select', required: true, options: getSupplierOptions },
      { key: 'startDate', label: '开始日期', type: 'date', required: true },
      { key: 'endDate', label: '结束日期', type: 'date', required: true },
      { key: 'purchaseAmount', label: '采购金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0, disabled: true },
      { key: 'closingAmount', label: '期末余额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0, disabled: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '待确认', options: statementStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    saveFields: {
      scalar: ['statementNo', 'sourceInboundNos', 'supplierName', 'startDate', 'endDate', 'purchaseAmount', 'paymentAmount', 'closingAmount', 'status', 'remark'],
    },
    itemColumns: compactBatchSupplierStatementItemColumns,
    data: [],
    buildOverview: (rows) => buildStatementOverview(rows, 'purchaseAmount', 'paymentAmount', 'closingAmount'),
    statusMap,
    rowHighlightStatuses: ['待确认'],
  },
  'customer-statements': {
    key: 'customer-statements',
    title: '客户对账单',
    kicker: 'Statements',
    description: '客户对账单按已完成销售的销售订单明细口径组织，生成后保留来源订单行，便于逐项核对销售数量、单价和金额。',
    primaryNoKey: 'statementNo',
    actions: [{ label: '生成对账单', type: 'primary' }],
    filters: [
      { key: 'customerName', label: '客户', type: 'select', options: customerOptions },
      { key: 'status', label: '状态', type: 'select', options: statementStatusOptions },
      { key: 'endDate', label: '账期', type: 'dateRange' },
    ],
    columns: [
      { title: '对账单号', dataIndex: 'statementNo', width: 170 },
      { title: '客户', dataIndex: 'customerName', width: 140 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '开始日期', dataIndex: 'startDate', width: 120, type: 'date' },
      { title: '结束日期', dataIndex: 'endDate', width: 120, type: 'date' },
      { title: '销售金额', dataIndex: 'salesAmount', width: 110, align: 'right', type: 'amount' },
      { title: '收款金额', dataIndex: 'receiptAmount', width: 110, align: 'right', type: 'amount' },
      { title: '期末余额', dataIndex: 'closingAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '对账单号', key: 'statementNo' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '开始日期', key: 'startDate', type: 'date' },
      { label: '结束日期', key: 'endDate', type: 'date' },
      { label: '销售金额', key: 'salesAmount', type: 'amount' },
      { label: '收款金额', key: 'receiptAmount', type: 'amount' },
      { label: '期末余额', key: 'closingAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'statementNo', label: '对账单号', type: 'input', required: true },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: customerOptions },
      { key: 'projectName', label: '项目', type: 'input', required: true },
      { key: 'startDate', label: '开始日期', type: 'date', required: true },
      { key: 'endDate', label: '结束日期', type: 'date', required: true },
      { key: 'salesAmount', label: '销售金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0, disabled: true },
      { key: 'closingAmount', label: '期末余额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0, disabled: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '待确认', options: statementStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    saveFields: {
      scalar: ['statementNo', 'sourceOrderNos', 'customerName', 'projectName', 'startDate', 'endDate', 'salesAmount', 'receiptAmount', 'closingAmount', 'status', 'remark'],
    },
    itemColumns: compactBatchCustomerStatementItemColumns,
    data: [],
    buildOverview: (rows) => buildStatementOverview(rows, 'salesAmount', 'receiptAmount', 'closingAmount'),
    statusMap,
    rowHighlightStatuses: ['待确认'],
  },
  'freight-statements': {
    key: 'freight-statements',
    title: '物流对账单',
    kicker: 'Statements',
    description: '物流对账单和运费对账汇总拆开处理，这里展示正式物流对账单列表，用于审核、签署、附件和付款累计。',
    primaryNoKey: 'statementNo',
    actions: [
      { label: '生成物流对账单', type: 'primary' },
      { label: '查看运费对账汇总', type: 'default' },
    ],
    filters: [
      { key: 'carrierName', label: '物流商', type: 'select', options: getCarrierOptions },
      { key: 'status', label: '审核状态', type: 'select', options: [
        { label: '待审核', value: '待审核' },
        { label: '已审核', value: '已审核' },
      ] },
      { key: 'signStatus', label: '签署状态', type: 'select', options: [
        { label: '未签署', value: '未签署' },
        { label: '已签署', value: '已签署' },
      ] },
      { key: 'endDate', label: '账期', type: 'dateRange' },
    ],
    columns: [
      { title: '对账单号', dataIndex: 'statementNo', width: 170 },
      { title: '物流商', dataIndex: 'carrierName', width: 150 },
      { title: '开始日期', dataIndex: 'startDate', width: 120, type: 'date' },
      { title: '结束日期', dataIndex: 'endDate', width: 120, type: 'date' },
      { title: '总重量（吨）', dataIndex: 'totalWeight', width: 116, align: 'right', type: 'weight' },
      { title: '总运费', dataIndex: 'totalFreight', width: 110, align: 'right', type: 'amount' },
      { title: '已付金额', dataIndex: 'paidAmount', width: 110, align: 'right', type: 'amount' },
      { title: '审核状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '签署状态', dataIndex: 'signStatus', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '对账单号', key: 'statementNo' },
      { label: '物流商', key: 'carrierName' },
      { label: '开始日期', key: 'startDate', type: 'date' },
      { label: '结束日期', key: 'endDate', type: 'date' },
      { label: '总重量（吨）', key: 'totalWeight', type: 'weight' },
      { label: '总运费', key: 'totalFreight', type: 'amount' },
      { label: '已付金额', key: 'paidAmount', type: 'amount' },
      { label: '审核状态', key: 'status', type: 'status' },
      { label: '签署状态', key: 'signStatus', type: 'status' },
      { label: '附件', key: 'attachment' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'statementNo', label: '对账单号', type: 'input', required: true },
      { key: 'carrierName', label: '物流商', type: 'select', required: true, options: getCarrierOptions },
      { key: 'startDate', label: '开始日期', type: 'date', required: true },
      { key: 'endDate', label: '结束日期', type: 'date', required: true },
      { key: 'totalWeight', label: '总重量（吨）', type: 'number', required: true, min: 0, precision: 3, defaultValue: 0 },
      { key: 'totalFreight', label: '总运费', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'status', label: '审核状态', type: 'select', defaultValue: '待审核', options: [
        { label: '待审核', value: '待审核' },
        { label: '已审核', value: '已审核' },
      ] },
      { key: 'signStatus', label: '签署状态', type: 'select', defaultValue: '未签署', options: [
        { label: '未签署', value: '未签署' },
        { label: '已签署', value: '已签署' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    itemColumns: freightItemColumns,
    data: [],
    buildOverview: (rows) => buildStatementOverview(rows, 'totalFreight', 'paidAmount', 'unpaidAmount'),
    statusMap,
    rowHighlightStatuses: ['待审核', '未签署'],
  },
  receipts: {
    key: 'receipts',
    title: '收款单',
    kicker: 'Finance',
    description: '收款单用于登记客户回款，支持先录收款、后做对账单核销；未核销金额保留在收款单本身，已核销金额通过明细逐笔落账。',
    primaryNoKey: 'receiptNo',
    actions: [{ label: '新增收款单', type: 'primary' }],
    filters: [
      { key: 'customerName', label: '客户', type: 'select', options: customerOptions },
      { key: 'projectName', label: '项目', type: 'select', options: getCustomerProjectOptions, row: 2 },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '已收款', value: '已收款' },
      ] },
      { key: 'receiptDate', label: '收款日期', type: 'dateRange' },
    ],
    columns: [
      { title: '收款单号', dataIndex: 'receiptNo', width: 170 },
      { title: '客户', dataIndex: 'customerName', width: 140 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '收款日期', dataIndex: 'receiptDate', width: 120, type: 'date' },
      { title: '收款方式', dataIndex: 'payType', width: 120 },
      { title: '金额', dataIndex: 'amount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '收款单号', key: 'receiptNo' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '收款日期', key: 'receiptDate', type: 'date' },
      { label: '收款方式', key: 'payType' },
      { label: '经办人', key: 'operatorName' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'receiptNo', label: '收款单号', type: 'input', required: true },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: customerOptions },
      { key: 'projectName', label: '项目', type: 'select', required: true, options: getCustomerProjectOptions },
      { key: 'receiptDate', label: '收款日期', type: 'date', required: true },
      { key: 'payType', label: '收款方式', type: 'select', required: true, options: [
        { label: '银行转账', value: '银行转账' },
        { label: '银行承兑', value: '银行承兑' },
        { label: '承兑汇票', value: '承兑汇票' },
        { label: '现金', value: '现金' },
      ] },
      { key: 'operatorName', label: '经办人', type: 'input', required: true },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    saveFields: {
      scalar: ['receiptNo', 'customerName', 'projectName', 'sourceStatementId', 'receiptDate', 'payType', 'amount', 'status', 'operatorName', 'remark'],
      lineItem: ['sourceStatementId', 'allocatedAmount'],
    },
    itemColumns: [
      { title: '关联对账单', dataIndex: 'sourceStatementId', width: 180, required: true },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '对账单余额', dataIndex: 'statementBalanceAmount', width: 130, align: 'right', type: 'amount' },
      { title: '核销金额', dataIndex: 'allocatedAmount', width: 120, align: 'right', type: 'amount', required: true },
    ],
    data: [],
    buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  payments: {
    key: 'payments',
    title: '付款单',
    kicker: 'Finance',
    description: '付款单统一承接供应商付款和物流付款，支持先登记付款，再按对账单逐笔核销，避免单头必须绑定单张对账单。',
    primaryNoKey: 'paymentNo',
    actions: [{ label: '新增付款单', type: 'primary' }],
    filters: [
      { key: 'businessType', label: '业务类型', type: 'select', options: [
        { label: '供应商', value: '供应商' },
        { label: '物流商', value: '物流商' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '已付款', value: '已付款' },
      ] },
      { key: 'paymentDate', label: '付款日期', type: 'dateRange' },
    ],
    columns: [
      { title: '付款单号', dataIndex: 'paymentNo', width: 170 },
      { title: '业务类型', dataIndex: 'businessType', width: 110 },
      { title: '往来单位', dataIndex: 'counterpartyName', width: 160 },
      { title: '付款日期', dataIndex: 'paymentDate', width: 120, type: 'date' },
      { title: '付款方式', dataIndex: 'payType', width: 120 },
      { title: '金额', dataIndex: 'amount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '付款单号', key: 'paymentNo' },
      { label: '业务类型', key: 'businessType' },
      { label: '往来单位', key: 'counterpartyName' },
      { label: '付款日期', key: 'paymentDate', type: 'date' },
      { label: '付款方式', key: 'payType' },
      { label: '金额', key: 'amount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '经办人', key: 'operatorName' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'paymentNo', label: '付款单号', type: 'input', required: true },
      { key: 'businessType', label: '业务类型', type: 'select', required: true, options: [
        { label: '供应商', value: '供应商' },
        { label: '物流商', value: '物流商' },
      ] },
      { key: 'counterpartyName', label: '往来单位', type: 'input', required: true },
      { key: 'paymentDate', label: '付款日期', type: 'date', required: true },
      { key: 'payType', label: '付款方式', type: 'select', required: true, options: [
        { label: '银行转账', value: '银行转账' },
        { label: '银行承兑', value: '银行承兑' },
        { label: '现金', value: '现金' },
      ] },
      { key: 'amount', label: '金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'status', label: '状态', type: 'select', defaultValue: '草稿', options: [
        { label: '草稿', value: '草稿' },
        { label: '已付款', value: '已付款' },
      ] },
      { key: 'operatorName', label: '经办人', type: 'input', required: true },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    saveFields: {
      scalar: ['paymentNo', 'businessType', 'counterpartyName', 'sourceStatementId', 'paymentDate', 'payType', 'amount', 'status', 'operatorName', 'remark'],
      lineItem: ['sourceStatementId', 'allocatedAmount'],
    },
    itemColumns: [
      { title: '关联对账单', dataIndex: 'sourceStatementId', width: 240, required: true },
      { title: '对账单余额', dataIndex: 'statementBalanceAmount', width: 130, align: 'right', type: 'amount' },
      { title: '核销金额', dataIndex: 'allocatedAmount', width: 120, align: 'right', type: 'amount', required: true },
    ],
    data: [],
    buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'invoice-receipts': {
    key: 'invoice-receipts',
    title: '收票单',
    kicker: 'Finance',
    description: '收票单用于登记供应商发票到票情况，表头维护票号与税额，明细支持从采购订单勾选导入并逐行核对金额。',
    primaryNoKey: 'receiveNo',
    actions: [{ label: '新增收票单', type: 'primary' }],
    filters: [
      { key: 'supplierName', label: '供应商', type: 'select', options: getSupplierOptions },
      { key: 'status', label: '状态', type: 'select', options: buildValueOptions('草稿', '已收票') },
      { key: 'invoiceDate', label: '发票日期', type: 'dateRange' },
    ],
    columns: [
      { title: '收票单号', dataIndex: 'receiveNo', width: 170 },
      { title: '关联采购订单', dataIndex: 'sourcePurchaseOrderNos', width: 180 },
      { title: '发票号码', dataIndex: 'invoiceNo', width: 150 },
      { title: '供应商', dataIndex: 'supplierName', width: 150 },
      { title: '开票方抬头', dataIndex: 'invoiceTitle', width: 170 },
      { title: '发票日期', dataIndex: 'invoiceDate', width: 120, type: 'date' },
      { title: '票种', dataIndex: 'invoiceType', width: 120 },
      { title: '金额', dataIndex: 'amount', width: 110, align: 'right', type: 'amount' },
      { title: '税额', dataIndex: 'taxAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '收票单号', key: 'receiveNo' },
      { label: '关联采购订单', key: 'sourcePurchaseOrderNos' },
      { label: '发票号码', key: 'invoiceNo' },
      { label: '供应商', key: 'supplierName' },
      { label: '开票方抬头', key: 'invoiceTitle' },
      { label: '发票日期', key: 'invoiceDate', type: 'date' },
      { label: '票种', key: 'invoiceType' },
      { label: '金额', key: 'amount', type: 'amount' },
      { label: '税额', key: 'taxAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '经办人', key: 'operatorName' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'receiveNo', label: '收票单号', type: 'input', required: true },
      { key: 'sourcePurchaseOrderNos', label: '关联采购订单', type: 'input', disabled: true, placeholder: '通过采购订单明细导入，可追加多个单号' },
      { key: 'invoiceNo', label: '发票号码', type: 'input', required: true },
      { key: 'supplierName', label: '供应商', type: 'select', required: true, options: getSupplierOptions },
      { key: 'invoiceTitle', label: '开票方抬头', type: 'input', required: true },
      { key: 'invoiceDate', label: '发票日期', type: 'date', required: true },
      { key: 'invoiceType', label: '票种', type: 'select', required: true, options: buildValueOptions('增值税专票', '增值税普票') },
      { key: 'amount', label: '金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0, disabled: true },
      { key: 'taxRate', label: '税率', type: 'number', min: 0, precision: 4, defaultValue: 0, disabled: true },
      { key: 'taxAmount', label: '税额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0, disabled: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '草稿', options: buildValueOptions('草稿', '已收票') },
      { key: 'operatorName', label: '经办人', type: 'input', required: true },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    parentImport: {
      parentModuleKey: 'purchase-orders',
      label: '上级采购订单',
      parentFieldKey: 'sourcePurchaseOrderNos',
      parentDisplayFieldKey: 'orderNo',
      buttonText: '导入采购订单明细',
      mapParentToDraft: (parentRecord) => ({
        supplierName: parentRecord.supplierName || '',
        invoiceTitle: parentRecord.supplierName || '',
      }),
      transformItems: (parentRecord) => Array.isArray(parentRecord.items)
        ? parentRecord.items.map((item, index) => ({
            ...item,
            id: `invoice-receipt-item-${parentRecord.id}-${index + 1}`,
            sourceNo: parentRecord.orderNo || '',
            sourcePurchaseOrderItemId: item.id,
            _maxImportWeightTon: item.weightTon,
            _maxImportAmount: item.amount,
            maxImportQuantity: item.quantity,
            quantity: item.quantity,
          }))
        : [],
    },
    itemColumns: compactInvoiceReceiptItemColumns,
    data: [],
    buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'invoice-issues': {
    key: 'invoice-issues',
    title: '开票单',
    kicker: 'Finance',
    description: '开票单用于登记客户开票记录，表头由用户填写，明细支持按销售订单勾选导入并自动汇总开票金额。',
    primaryNoKey: 'issueNo',
    actions: [{ label: '新增开票单', type: 'primary' }],
    filters: [
      { key: 'customerName', label: '客户', type: 'select', options: customerOptions },
      { key: 'status', label: '状态', type: 'select', options: buildValueOptions('草稿', '已开票') },
      { key: 'invoiceDate', label: '发票日期', type: 'dateRange' },
    ],
    columns: [
      { title: '开票单号', dataIndex: 'issueNo', width: 170 },
      { title: '关联销售订单', dataIndex: 'sourceSalesOrderNos', width: 180 },
      { title: '发票号码', dataIndex: 'invoiceNo', width: 150 },
      { title: '客户', dataIndex: 'customerName', width: 150 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '发票日期', dataIndex: 'invoiceDate', width: 120, type: 'date' },
      { title: '票种', dataIndex: 'invoiceType', width: 120 },
      { title: '金额', dataIndex: 'amount', width: 110, align: 'right', type: 'amount' },
      { title: '税额', dataIndex: 'taxAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '开票单号', key: 'issueNo' },
      { label: '关联销售订单', key: 'sourceSalesOrderNos' },
      { label: '发票号码', key: 'invoiceNo' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '发票日期', key: 'invoiceDate', type: 'date' },
      { label: '票种', key: 'invoiceType' },
      { label: '金额', key: 'amount', type: 'amount' },
      { label: '税额', key: 'taxAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '经办人', key: 'operatorName' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'issueNo', label: '开票单号', type: 'input', required: true },
      { key: 'sourceSalesOrderNos', label: '关联销售订单', type: 'input', disabled: true, placeholder: '通过销售订单明细导入，可追加多个单号' },
      { key: 'invoiceNo', label: '发票号码', type: 'input', required: true },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: customerOptions },
      { key: 'projectName', label: '项目', type: 'input', required: true },
      { key: 'invoiceDate', label: '发票日期', type: 'date', required: true },
      { key: 'invoiceType', label: '票种', type: 'select', required: true, options: buildValueOptions('增值税专票', '增值税普票') },
      { key: 'targetAmount', label: '开票总金额', type: 'number', min: 0, precision: 2, defaultValue: 0 },
      { key: 'amount', label: '金额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0, disabled: true },
      { key: 'taxRate', label: '税率', type: 'number', min: 0, precision: 4, defaultValue: 0, disabled: true },
      { key: 'taxAmount', label: '税额', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0, disabled: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '草稿', options: buildValueOptions('草稿', '已开票') },
      { key: 'operatorName', label: '经办人', type: 'input', required: true },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    parentImport: {
      parentModuleKey: 'sales-orders',
      label: '上级销售订单',
      parentFieldKey: 'sourceSalesOrderNos',
      parentDisplayFieldKey: 'orderNo',
      buttonText: '导入销售订单明细',
      mapParentToDraft: (parentRecord) => ({
        customerName: parentRecord.customerName || '',
        projectName: parentRecord.projectName || '',
      }),
      transformItems: (parentRecord) => Array.isArray(parentRecord.items)
        ? parentRecord.items.map((item, index) => ({
            ...item,
            id: `invoice-issue-item-${parentRecord.id}-${index + 1}`,
            sourceNo: parentRecord.orderNo || '',
            sourceSalesOrderItemId: item.id,
            _maxImportWeightTon: item.weightTon,
            _maxImportAmount: item.amount,
            maxImportQuantity: item.quantity,
          }))
        : [],
    },
    itemColumns: compactInvoiceIssueItemColumns,
    data: [],
    buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'receivables-payables': {
    key: 'receivables-payables',
    title: '应收应付',
    kicker: 'Finance',
    description: '应收应付页面先按客户、供应商、物流商统一展示余额结果，后续再叠加核销和账龄分析。',
    readOnly: true,
    actions: [{ label: '导出余额表', type: 'primary' }],
    filters: [
      { key: 'direction', label: '方向', type: 'select', options: [
        { label: '应收', value: '应收' },
        { label: '应付', value: '应付' },
      ] },
      { key: 'counterpartyType', label: '往来类型', type: 'select', options: [
        { label: '客户', value: '客户' },
        { label: '供应商', value: '供应商' },
        { label: '物流商', value: '物流商' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: buildValueOptions('待确认', '已确认', '待审核', '已审核') },
    ],
    columns: [
      { title: '方向', dataIndex: 'direction', width: 100 },
      { title: '往来类型', dataIndex: 'counterpartyType', width: 110 },
      { title: '往来单位', dataIndex: 'counterpartyName', width: 160 },
      { title: '客户', dataIndex: 'customerName', width: 140 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '期初余额', dataIndex: 'openingAmount', width: 110, align: 'right', type: 'amount' },
      { title: '本期发生', dataIndex: 'currentAmount', width: 110, align: 'right', type: 'amount' },
      { title: '本期结算', dataIndex: 'settledAmount', width: 110, align: 'right', type: 'amount' },
      { title: '期末余额', dataIndex: 'balanceAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '方向', key: 'direction' },
      { label: '往来类型', key: 'counterpartyType' },
      { label: '往来单位', key: 'counterpartyName' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '期初余额', key: 'openingAmount', type: 'amount' },
      { label: '本期发生', key: 'currentAmount', type: 'amount' },
      { label: '本期结算', key: 'settledAmount', type: 'amount' },
      { label: '期末余额', key: 'balanceAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '往来单位数', value: formatInteger(rows.length) },
      { label: '应收余额', value: formatAmount(sumBy(rows.filter((row) => row.direction === '应收'), 'balanceAmount')) },
      { label: '应付余额', value: formatAmount(sumBy(rows.filter((row) => row.direction === '应付'), 'balanceAmount')) },
    ],
    statusMap,
    rowHighlightStatuses: ['待确认', '待审核'],
  },
}
