import { getCarrierOptions } from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import {
  AUDIT_STATUS_LABEL,
  CARRIER_NAME_LABEL,
  SIGN_STATUS_LABEL,
} from './filter-labels'
import { buildStatementOverview, freightItemColumns, statusMap } from './shared'
import i18next from 'i18next'

export const freightStatementPageConfig: ModulePageConfig = {
  key: 'freight-statement',
  title: i18next.t('modules.pages.freightStatement.freightStatement'),
  kicker: 'Statements',
  description:
    i18next.t('modules.pages.freightStatement.freightStatementDesc'),
  primaryNoKey: 'statementNo',
  actions: [
    {
      key: 'generate_freight_statement',
      label: i18next.t('modules.pages.freightStatement.generateFreightStatement'),
      type: 'primary',
    },
    {
      key: 'view_freight_summary',
      label: i18next.t('modules.pages.freightStatement.viewFreightSummary'),
      type: 'default',
    },
  ],
  filters: [
    {
      key: 'carrierName',
      label: CARRIER_NAME_LABEL,
      type: 'select',
      options: getCarrierOptions,
    },
    {
      key: 'status',
      label: AUDIT_STATUS_LABEL,
      type: 'select',
      options: [
        { label: i18next.t('modules.pages.freightStatement.pendingAudit'), value: '待审核' },
        { label: i18next.t('modules.pages.freightStatement.audited'), value: '已审核' },
      ],
    },
    {
      key: 'signStatus',
      label: SIGN_STATUS_LABEL,
      type: 'select',
      options: [
        { label: i18next.t('modules.pages.freightStatement.unsigned'), value: '未签署' },
        { label: i18next.t('modules.pages.freightStatement.signed'), value: '已签署' },
      ],
    },
    { key: 'endDate', label: i18next.t('modules.pages.freightStatement.period'), type: 'dateRange' },
  ],
  columns: [
    { title: i18next.t('modules.pages.freightStatement.statementNo'), dataIndex: 'statementNo', width: 170 },
    { title: i18next.t('modules.pages.freightStatement.carrier'), dataIndex: 'carrierName', width: 150 },
    { title: i18next.t('modules.pages.freightStatement.startDate'), dataIndex: 'startDate', width: 120, type: 'date' },
    { title: i18next.t('modules.pages.freightStatement.endDate'), dataIndex: 'endDate', width: 120, type: 'date' },
    {
      title: i18next.t('modules.pages.freightStatement.totalWeight'),
      dataIndex: 'totalWeight',
      width: 116,
      align: 'right',
      type: 'weight',
    },
    {
      title: i18next.t('modules.pages.freightStatement.totalFreight'),
      dataIndex: 'totalFreight',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: i18next.t('modules.pages.freightStatement.paidAmount'),
      dataIndex: 'paidAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: i18next.t('modules.pages.freightStatement.auditStatus'),
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
    {
      title: i18next.t('modules.pages.freightStatement.signStatus'),
      dataIndex: 'signStatus',
      width: 110,
      type: 'status',
      align: 'center',
    },
  ],
  defaultHiddenColumnKeys: ['paidAmount'],
  detailFields: [
    { label: i18next.t('modules.pages.freightStatement.statementNo'), key: 'statementNo' },
    { label: i18next.t('modules.pages.freightStatement.carrier'), key: 'carrierName' },
    { label: i18next.t('modules.pages.freightStatement.startDate'), key: 'startDate', type: 'date' },
    { label: i18next.t('modules.pages.freightStatement.endDate'), key: 'endDate', type: 'date' },
    { label: i18next.t('modules.pages.freightStatement.totalWeight'), key: 'totalWeight', type: 'weight' },
    { label: i18next.t('modules.pages.freightStatement.totalFreight'), key: 'totalFreight', type: 'amount' },
    { label: i18next.t('modules.pages.freightStatement.paidAmount'), key: 'paidAmount', type: 'amount' },
    { label: i18next.t('modules.pages.freightStatement.auditStatus'), key: 'status', type: 'status' },
    { label: i18next.t('modules.pages.freightStatement.signStatus'), key: 'signStatus', type: 'status' },
    { label: i18next.t('modules.pages.freightStatement.attachment'), key: 'attachment' },
    { label: i18next.t('modules.pages.freightStatement.remark'), key: 'remark' },
  ],
  formFields: [
    {
      key: 'statementNo',
      label: i18next.t('modules.pages.freightStatement.statementNo'),
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'carrierName',
      label: i18next.t('modules.pages.freightStatement.carrier'),
      type: 'select',
      required: true,
      options: getCarrierOptions,
      row: 1,
    },
    {
      key: 'startDate',
      label: i18next.t('modules.pages.freightStatement.startDate'),
      type: 'date',
      required: true,
      row: 1,
    },
    { key: 'endDate', label: i18next.t('modules.pages.freightStatement.endDate'), type: 'date', required: true, row: 1 },
    {
      key: 'totalWeight',
      label: i18next.t('modules.pages.freightStatement.totalWeight'),
      type: 'number',
      required: true,
      min: 0,
      precision: 3,
      defaultValue: 0,
      row: 2,
    },
    {
      key: 'totalFreight',
      label: i18next.t('modules.pages.freightStatement.totalFreight'),
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      row: 2,
    },
    {
      key: 'status',
      label: i18next.t('modules.pages.freightStatement.auditStatus'),
      type: 'select',
      defaultValue: '待审核',
      options: [
        { label: i18next.t('modules.pages.freightStatement.pendingAudit'), value: '待审核' },
        { label: i18next.t('modules.pages.freightStatement.audited'), value: '已审核' },
      ],
      row: 2,
    },
    {
      key: 'signStatus',
      label: i18next.t('modules.pages.freightStatement.signStatus'),
      type: 'select',
      defaultValue: '未签署',
      options: [
        { label: i18next.t('modules.pages.freightStatement.unsigned'), value: '未签署' },
        { label: i18next.t('modules.pages.freightStatement.signed'), value: '已签署' },
      ],
      row: 2,
    },
    { key: 'remark', label: i18next.t('modules.pages.freightStatement.remark'), type: 'textarea', row: 3, fullRow: true },
  ],
  saveFields: {
    scalar: [
      'statementNo',
      'sourceBillNos',
      'carrierName',
      'startDate',
      'endDate',
      'totalWeight',
      'totalFreight',
      'paidAmount',
      'unpaidAmount',
      'status',
      'signStatus',
      'attachment',
      'remark',
    ],
    lineItem: [
      'sourceNo',
      'customerName',
      'projectName',
      'materialCode',
      'materialName',
      'brand',
      'category',
      'material',
      'spec',
      'length',
      'quantity',
      'quantityUnit',
      'pieceWeightTon',
      'piecesPerBundle',
      'batchNo',
      'weightTon',
      'warehouseName',
    ],
  },
  itemColumns: freightItemColumns,
  data: [],
  buildOverview: (rows) =>
    buildStatementOverview(rows, 'totalFreight', 'paidAmount', 'unpaidAmount'),
  statusMap,
  rowHighlightStatuses: ['待审核', '未签署'],
}
