import { getCarrierOptions } from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import {
  AUDIT_STATUS_LABEL,
  CARRIER_NAME_LABEL,
  SIGN_STATUS_LABEL,
} from './filter-labels'
import { buildStatementOverview, freightItemColumns, statusMap } from './shared'

export const freightStatementPageConfig: ModulePageConfig = {
  key: 'freight-statement',
  title: '物流对账单',
  kicker: 'Statements',
  description:
    '物流对账单和运费对账汇总拆开处理，这里展示正式物流对账单列表，用于审核、签署、附件和付款累计。',
  primaryNoKey: 'statementNo',
  actions: [
    {
      key: 'generate_freight_statement',
      label: '生成物流对账单',
      type: 'primary',
    },
    {
      key: 'view_freight_summary',
      label: '查看运费对账汇总',
      type: 'default',
    },
  ],
  filters: [
    {
      key: 'carrierName',
      label: CARRIER_NAME_LABEL,
      type: 'select',
      options: getCarrierOptions,
    },
    {
      key: 'status',
      label: AUDIT_STATUS_LABEL,
      type: 'select',
      options: [
        { label: '待审核', value: '待审核' },
        { label: '已审核', value: '已审核' },
      ],
    },
    {
      key: 'signStatus',
      label: SIGN_STATUS_LABEL,
      type: 'select',
      options: [
        { label: '未签署', value: '未签署' },
        { label: '已签署', value: '已签署' },
      ],
    },
    { key: 'endDate', label: '账期', type: 'dateRange' },
  ],
  columns: [
    { title: '对账单号', dataIndex: 'statementNo', width: 170 },
    { title: '物流商', dataIndex: 'carrierName', width: 150 },
    { title: '开始日期', dataIndex: 'startDate', width: 120, type: 'date' },
    { title: '结束日期', dataIndex: 'endDate', width: 120, type: 'date' },
    {
      title: '总重量（吨）',
      dataIndex: 'totalWeight',
      width: 116,
      align: 'right',
      type: 'weight',
    },
    {
      title: '总运费',
      dataIndex: 'totalFreight',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '已付金额',
      dataIndex: 'paidAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '审核状态',
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
    {
      title: '签署状态',
      dataIndex: 'signStatus',
      width: 110,
      type: 'status',
      align: 'center',
    },
  ],
  detailFields: [
    { label: '对账单号', key: 'statementNo' },
    { label: '物流商', key: 'carrierName' },
    { label: '开始日期', key: 'startDate', type: 'date' },
    { label: '结束日期', key: 'endDate', type: 'date' },
    { label: '总重量（吨）', key: 'totalWeight', type: 'weight' },
    { label: '总运费', key: 'totalFreight', type: 'amount' },
    { label: '已付金额', key: 'paidAmount', type: 'amount' },
    { label: '审核状态', key: 'status', type: 'status' },
    { label: '签署状态', key: 'signStatus', type: 'status' },
    { label: '附件', key: 'attachment' },
    { label: '备注', key: 'remark' },
  ],
  formFields: [
    {
      key: 'statementNo',
      label: '对账单号',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'carrierName',
      label: '物流商',
      type: 'select',
      required: true,
      options: getCarrierOptions,
      row: 1,
    },
    {
      key: 'startDate',
      label: '开始日期',
      type: 'date',
      required: true,
      row: 1,
    },
    { key: 'endDate', label: '结束日期', type: 'date', required: true, row: 1 },
    {
      key: 'totalWeight',
      label: '总重量（吨）',
      type: 'number',
      required: true,
      min: 0,
      precision: 3,
      defaultValue: 0,
      row: 2,
    },
    {
      key: 'totalFreight',
      label: '总运费',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      row: 2,
    },
    {
      key: 'status',
      label: '审核状态',
      type: 'select',
      defaultValue: '待审核',
      options: [
        { label: '待审核', value: '待审核' },
        { label: '已审核', value: '已审核' },
      ],
      row: 2,
    },
    {
      key: 'signStatus',
      label: '签署状态',
      type: 'select',
      defaultValue: '未签署',
      options: [
        { label: '未签署', value: '未签署' },
        { label: '已签署', value: '已签署' },
      ],
      row: 2,
    },
    { key: 'remark', label: '备注', type: 'textarea', row: 3, fullRow: true },
  ],
  saveFields: {
    scalar: [
      'statementNo',
      'sourceBillNos',
      'carrierName',
      'startDate',
      'endDate',
      'totalWeight',
      'totalFreight',
      'paidAmount',
      'unpaidAmount',
      'status',
      'signStatus',
      'attachment',
      'remark',
    ],
    lineItem: [
      'sourceNo',
      'customerName',
      'projectName',
      'materialCode',
      'materialName',
      'brand',
      'category',
      'material',
      'spec',
      'length',
      'quantity',
      'quantityUnit',
      'pieceWeightTon',
      'piecesPerBundle',
      'batchNo',
      'weightTon',
      'warehouseName',
    ],
  },
  itemColumns: freightItemColumns,
  data: [],
  buildOverview: (rows) =>
    buildStatementOverview(rows, 'totalFreight', 'paidAmount', 'unpaidAmount'),
  statusMap,
  rowHighlightStatuses: ['待审核', '未签署'],
}
