import {
  buildValueOptions,
  getSupplierOptions,
} from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import { BILL_STATUS_LABEL, SUPPLIER_NAME_LABEL } from './filter-labels'
import {
  buildFinanceOverview,
  compactInvoiceReceiptItemColumns,
  statusMap,
} from './shared'

export const invoiceReceiptPageConfig: ModulePageConfig = {
  key: 'invoice-receipt',
  title: '收票单',
  kicker: 'Finance',
  description:
    '收票单用于登记供应商发票到票情况，表头维护票号与税额，明细支持从采购订单勾选导入并逐行核对金额。',
  primaryNoKey: 'receiveNo',
  actions: [
    { key: 'create_invoice_receipt', label: '新增收票单', type: 'primary' },
  ],
  filters: [
    {
      key: 'supplierName',
      label: SUPPLIER_NAME_LABEL,
      type: 'select',
      options: getSupplierOptions,
    },
    {
      key: 'status',
      label: BILL_STATUS_LABEL,
      type: 'select',
      options: buildValueOptions('草稿', '已收票'),
    },
    { key: 'invoiceDate', label: '发票日期', type: 'dateRange' },
  ],
  columns: [
    { title: '收票单号', dataIndex: 'receiveNo', width: 170 },
    {
      title: '关联采购订单',
      dataIndex: 'sourcePurchaseOrderNos',
      width: 180,
    },
    { title: '发票号码', dataIndex: 'invoiceNo', width: 150 },
    { title: '供应商', dataIndex: 'supplierName', width: 150 },
    { title: '开票方抬头', dataIndex: 'invoiceTitle', width: 170 },
    { title: '发票日期', dataIndex: 'invoiceDate', width: 120, type: 'date' },
    { title: '票种', dataIndex: 'invoiceType', width: 120 },
    {
      title: '金额',
      dataIndex: 'amount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '税额',
      dataIndex: 'taxAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
  ],
  defaultHiddenColumnKeys: ['sourcePurchaseOrderNos', 'invoiceTitle', 'taxAmount'],
  detailFields: [
    { label: '收票单号', key: 'receiveNo' },
    { label: '关联采购订单', key: 'sourcePurchaseOrderNos' },
    { label: '发票号码', key: 'invoiceNo' },
    { label: '供应商', key: 'supplierName' },
    { label: '开票方抬头', key: 'invoiceTitle' },
    { label: '发票日期', key: 'invoiceDate', type: 'date' },
    { label: '票种', key: 'invoiceType' },
    { label: '金额', key: 'amount', type: 'amount' },
    { label: '税额', key: 'taxAmount', type: 'amount' },
    { label: '状态', key: 'status', type: 'status' },
    { label: '经办人', key: 'operatorName' },
    { label: '备注', key: 'remark' },
  ],
  formFields: [
    {
      key: 'receiveNo',
      label: '收票单号',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'sourcePurchaseOrderNos',
      label: '关联采购订单',
      type: 'input',
      disabled: true,
      placeholder: '通过采购订单明细导入，可追加多个单号',
      row: 1,
    },
    {
      key: 'invoiceNo',
      label: '发票号码',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'supplierName',
      label: '供应商',
      type: 'select',
      required: true,
      options: getSupplierOptions,
      row: 1,
    },
    {
      key: 'invoiceTitle',
      label: '开票方抬头',
      type: 'input',
      required: true,
      row: 2,
    },
    {
      key: 'invoiceDate',
      label: '发票日期',
      type: 'date',
      required: true,
      row: 2,
    },
    {
      key: 'invoiceType',
      label: '票种',
      type: 'select',
      required: true,
      options: buildValueOptions('增值税专票', '增值税普票'),
      row: 2,
    },
    {
      key: 'amount',
      label: '金额',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 2,
    },
    {
      key: 'taxRate',
      label: '税率',
      type: 'number',
      min: 0,
      precision: 4,
      defaultValue: 0,
      disabled: true,
      row: 3,
    },
    {
      key: 'taxAmount',
      label: '税额',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 3,
    },
    {
      key: 'status',
      label: '状态',
      type: 'select',
      defaultValue: '草稿',
      options: buildValueOptions('草稿', '已收票'),
      row: 3,
    },
    {
      key: 'operatorName',
      label: '经办人',
      type: 'input',
      required: true,
      row: 3,
    },
    { key: 'remark', label: '备注', type: 'textarea', row: 4, fullRow: true },
  ],
  parentImport: {
    parentModuleKey: 'purchase-order',
    label: '上级采购订单',
    parentFieldKey: 'sourcePurchaseOrderNos',
    parentDisplayFieldKey: 'orderNo',
    buttonText: '导入采购订单明细',
    mapParentToDraft: (parentRecord) => ({
      supplierName: parentRecord.supplierName || '',
      invoiceTitle: parentRecord.supplierName || '',
    }),
    transformItems: (parentRecord) =>
      Array.isArray(parentRecord.items)
        ? parentRecord.items.map((item, index) => ({
            ...item,
            id: `invoice-receipt-item-${parentRecord.id}-${index + 1}`,
            sourceNo: parentRecord.orderNo || '',
            sourcePurchaseOrderItemId: item.id,
            _maxImportWeightTon: item.weightTon,
            _maxImportAmount: item.amount,
            maxImportQuantity: item.quantity,
            quantity: item.quantity,
          }))
        : [],
  },
  itemColumns: compactInvoiceReceiptItemColumns,
  saveFields: {
    scalar: [
      'receiveNo',
      'invoiceNo',
      'sourcePurchaseOrderNos',
      'supplierName',
      'invoiceTitle',
      'invoiceDate',
      'invoiceType',
      'amount',
      'taxAmount',
      'status',
      'operatorName',
      'remark',
    ],
    lineItem: [
      'sourceNo',
      'sourcePurchaseOrderItemId',
      'materialCode',
      'brand',
      'category',
      'material',
      'spec',
      'length',
      'unit',
      'warehouseName',
      'batchNo',
      'quantity',
      'quantityUnit',
      'pieceWeightTon',
      'piecesPerBundle',
      'weightTon',
      'unitPrice',
      'amount',
    ],
  },
  data: [],
  buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
  statusMap,
  rowHighlightStatuses: ['草稿'],
}
