import { buildValueOptions, customerOptions } from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import { BILL_STATUS_LABEL, CUSTOMER_NAME_LABEL } from './filter-labels'
import {
  buildFinanceOverview,
  compactInvoiceIssueItemColumns,
  statusMap,
} from './shared'

export const invoiceIssuePageConfig: ModulePageConfig = {
  key: 'invoice-issue',
  title: '开票单',
  kicker: 'Finance',
  description:
    '开票单用于登记客户开票记录，表头由用户填写，明细支持按销售订单勾选导入并自动汇总开票金额。',
  primaryNoKey: 'issueNo',
  actions: [
    { key: 'create_invoice_issue', label: '新增开票单', type: 'primary' },
  ],
  filters: [
    {
      key: 'customerName',
      label: CUSTOMER_NAME_LABEL,
      type: 'select',
      options: customerOptions,
    },
    {
      key: 'status',
      label: BILL_STATUS_LABEL,
      type: 'select',
      options: buildValueOptions('草稿', '已开票'),
    },
    { key: 'invoiceDate', label: '发票日期', type: 'dateRange' },
  ],
  columns: [
    { title: '开票单号', dataIndex: 'issueNo', width: 170 },
    { title: '关联销售订单', dataIndex: 'sourceSalesOrderNos', width: 180 },
    { title: '发票号码', dataIndex: 'invoiceNo', width: 150 },
    { title: '客户', dataIndex: 'customerName', width: 150 },
    { title: '项目', dataIndex: 'projectName', width: 180 },
    { title: '发票日期', dataIndex: 'invoiceDate', width: 120, type: 'date' },
    { title: '票种', dataIndex: 'invoiceType', width: 120 },
    {
      title: '金额',
      dataIndex: 'amount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '税额',
      dataIndex: 'taxAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
  ],
  detailFields: [
    { label: '开票单号', key: 'issueNo' },
    { label: '关联销售订单', key: 'sourceSalesOrderNos' },
    { label: '发票号码', key: 'invoiceNo' },
    { label: '客户', key: 'customerName' },
    { label: '项目', key: 'projectName' },
    { label: '发票日期', key: 'invoiceDate', type: 'date' },
    { label: '票种', key: 'invoiceType' },
    { label: '金额', key: 'amount', type: 'amount' },
    { label: '税额', key: 'taxAmount', type: 'amount' },
    { label: '状态', key: 'status', type: 'status' },
    { label: '经办人', key: 'operatorName' },
    { label: '备注', key: 'remark' },
  ],
  formFields: [
    {
      key: 'issueNo',
      label: '开票单号',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'sourceSalesOrderNos',
      label: '关联销售订单',
      type: 'input',
      disabled: true,
      placeholder: '通过销售订单明细导入，可追加多个单号',
      row: 1,
    },
    {
      key: 'invoiceNo',
      label: '发票号码',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'customerName',
      label: '客户',
      type: 'select',
      required: true,
      options: customerOptions,
      row: 1,
    },
    {
      key: 'projectName',
      label: '项目',
      type: 'input',
      required: true,
      row: 2,
    },
    {
      key: 'invoiceDate',
      label: '发票日期',
      type: 'date',
      required: true,
      row: 2,
    },
    {
      key: 'invoiceType',
      label: '票种',
      type: 'select',
      required: true,
      options: buildValueOptions('增值税专票', '增值税普票'),
      row: 2,
    },
    {
      key: 'targetAmount',
      label: '开票总金额',
      type: 'number',
      min: 0,
      precision: 2,
      defaultValue: 0,
      row: 2,
    },
    {
      key: 'amount',
      label: '金额',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 3,
    },
    {
      key: 'taxRate',
      label: '税率',
      type: 'number',
      min: 0,
      precision: 4,
      defaultValue: 0,
      disabled: true,
      row: 3,
    },
    {
      key: 'taxAmount',
      label: '税额',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 3,
    },
    {
      key: 'status',
      label: '状态',
      type: 'select',
      defaultValue: '草稿',
      options: buildValueOptions('草稿', '已开票'),
      row: 3,
    },
    {
      key: 'operatorName',
      label: '经办人',
      type: 'input',
      required: true,
      row: 4,
    },
    { key: 'remark', label: '备注', type: 'textarea', row: 5, fullRow: true },
  ],
  parentImport: {
    parentModuleKey: 'sales-order',
    label: '上级销售订单',
    parentFieldKey: 'sourceSalesOrderNos',
    parentDisplayFieldKey: 'orderNo',
    buttonText: '导入销售订单明细',
    mapParentToDraft: (parentRecord) => ({
      customerName: parentRecord.customerName || '',
      projectName: parentRecord.projectName || '',
    }),
    transformItems: (parentRecord) =>
      Array.isArray(parentRecord.items)
        ? parentRecord.items.map((item, index) => ({
            ...item,
            id: `invoice-issue-item-${parentRecord.id}-${index + 1}`,
            sourceNo: parentRecord.orderNo || '',
            sourceSalesOrderItemId: item.id,
            _maxImportWeightTon: item.weightTon,
            _maxImportAmount: item.amount,
            maxImportQuantity: item.quantity,
          }))
        : [],
  },
  itemColumns: compactInvoiceIssueItemColumns,
  saveFields: {
    scalar: [
      'issueNo',
      'invoiceNo',
      'sourceSalesOrderNos',
      'customerName',
      'projectName',
      'invoiceDate',
      'invoiceType',
      'amount',
      'taxAmount',
      'status',
      'operatorName',
      'remark',
    ],
    lineItem: [
      'sourceNo',
      'sourceSalesOrderItemId',
      'materialCode',
      'brand',
      'category',
      'material',
      'spec',
      'length',
      'unit',
      'warehouseName',
      'batchNo',
      'quantity',
      'quantityUnit',
      'pieceWeightTon',
      'piecesPerBundle',
      'weightTon',
      'unitPrice',
      'amount',
    ],
  },
  data: [],
  buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
  statusMap,
  rowHighlightStatuses: ['草稿'],
}
