import type { ModulePageConfig } from '@/types/module-page'
import {
  enabledStatusOptions,
  materialCategoryOptions,
  materialCategoryFallbackOptions,
} from '@/constants/module-options'
import {
  actionSet,
  buildMasterOverview,
  formatInteger,
  statusMap,
} from './shared'

export const masterDataPageConfigs: Record<string, ModulePageConfig> = {
  materials: {
    key: 'materials',
    title: '商品资料',
    kicker: 'Master Data',
    description: '根据既定商品字段维护主数据页面，支持按编码、品牌、规格和材质统一管理，便于直接对接真实商品接口。',
    primaryNoKey: 'materialCode',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '商品编码 / 品牌 / 规格' },
      { key: 'category', label: '类别', type: 'select', options: materialCategoryOptions },
      { key: 'material', label: '材质', type: 'input', placeholder: '材质' },
    ],
    columns: [
      { title: '商品编码', dataIndex: 'materialCode', width: 150 },
      { title: '品牌', dataIndex: 'brand', width: 120 },
      { title: '材质', dataIndex: 'material', width: 120 },
      { title: '类别', dataIndex: 'category', width: 110 },
      { title: '规格', dataIndex: 'spec', width: 100 },
      { title: '长度', dataIndex: 'length', width: 100 },
      { title: '单位', dataIndex: 'unit', width: 90 },
      { title: '数量单位', dataIndex: 'quantityUnit', width: 90 },
      { title: '件重/吨', dataIndex: 'pieceWeightTon', width: 110, align: 'right', type: 'weight' },
      { title: '每件支数', dataIndex: 'piecesPerBundle', width: 110, align: 'right', type: 'count' },
      { title: '单价', dataIndex: 'unitPrice', width: 100, align: 'right', type: 'amount' },
      { title: '批号管理', dataIndex: 'batchNoEnabled', width: 110 },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '商品编码', key: 'materialCode' },
      { label: '品牌', key: 'brand' },
      { label: '材质', key: 'material' },
      { label: '类别', key: 'category' },
      { label: '规格', key: 'spec' },
      { label: '长度', key: 'length' },
      { label: '单位', key: 'unit' },
      { label: '数量单位', key: 'quantityUnit' },
      { label: '件重/吨', key: 'pieceWeightTon', type: 'weight' },
      { label: '每件支数', key: 'piecesPerBundle', type: 'count' },
      { label: '单价', key: 'unitPrice', type: 'amount' },
      { label: '批号管理', key: 'batchNoEnabled' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'materialCode', label: '商品编码', type: 'input', required: true },
      { key: 'brand', label: '品牌', type: 'input', required: true },
      { key: 'material', label: '材质', type: 'input', required: true },
      { key: 'category', label: '类别', type: 'select', required: true, options: materialCategoryFallbackOptions },
      { key: 'spec', label: '规格', type: 'input', required: true },
      { key: 'length', label: '长度', type: 'input', required: true },
      { key: 'unit', label: '单位', type: 'input', required: true },
      { key: 'quantityUnit', label: '数量单位', type: 'input', required: true },
      { key: 'pieceWeightTon', label: '件重/吨', type: 'number', required: true, min: 0, precision: 3, defaultValue: 0 },
      { key: 'piecesPerBundle', label: '每件支数', type: 'number', required: true, min: 0, precision: 0, defaultValue: 0 },
      { key: 'unitPrice', label: '单价', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'batchNoEnabled', label: '批号管理', type: 'select', defaultValue: false, options: [
        { label: '关闭', value: false },
        { label: '启用', value: true },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '商品数', value: formatInteger(rows.length) },
      { label: '理算品类', value: formatInteger(rows.filter((row) => row.category === '螺纹钢').length) },
      { label: '过磅品类', value: formatInteger(rows.filter((row) => row.category !== '螺纹钢').length) },
    ],
  },
  suppliers: {
    key: 'suppliers',
    title: '供应商资料',
    kicker: 'Master Data',
    description: '供应商主数据统一维护基础档案、联系人和合作状态，供采购与对账页面复用。',
    primaryNoKey: 'supplierCode',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '供应商编码 / 名称 / 联系人' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    columns: [
      { title: '供应商编码', dataIndex: 'supplierCode', width: 140 },
      { title: '供应商名称', dataIndex: 'supplierName', width: 180 },
      { title: '联系人', dataIndex: 'contactName', width: 110 },
      { title: '联系电话', dataIndex: 'contactPhone', width: 140 },
      { title: '所在城市', dataIndex: 'city', width: 120 },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '供应商编码', key: 'supplierCode' },
      { label: '供应商名称', key: 'supplierName' },
      { label: '联系人', key: 'contactName' },
      { label: '联系电话', key: 'contactPhone' },
      { label: '所在城市', key: 'city' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'supplierCode', label: '供应商编码', type: 'input', required: true },
      { key: 'supplierName', label: '供应商名称', type: 'input', required: true },
      { key: 'contactName', label: '联系人', type: 'input', required: true },
      { key: 'contactPhone', label: '联系电话', type: 'input', required: true },
      { key: 'city', label: '所在城市', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: enabledStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  customers: {
    key: 'customers',
    title: '客户资料',
    kicker: 'Master Data',
    description: '客户主数据统一维护客户档案、项目偏好、结算方式和合作状态，供销售与对账页面复用。',
    primaryNoKey: 'customerCode',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '客户编码 / 名称 / 联系人' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    columns: [
      { title: '客户编码', dataIndex: 'customerCode', width: 140 },
      { title: '客户名称', dataIndex: 'customerName', width: 180 },
      { title: '联系人', dataIndex: 'contactName', width: 110 },
      { title: '联系电话', dataIndex: 'contactPhone', width: 140 },
      { title: '所在城市', dataIndex: 'city', width: 120 },
      { title: '结算方式', dataIndex: 'settlementMode', width: 110 },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '客户编码', key: 'customerCode' },
      { label: '客户名称', key: 'customerName' },
      { label: '联系人', key: 'contactName' },
      { label: '联系电话', key: 'contactPhone' },
      { label: '所在城市', key: 'city' },
      { label: '结算方式', key: 'settlementMode' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'customerCode', label: '客户编码', type: 'input', required: true },
      { key: 'customerName', label: '客户名称', type: 'input', required: true },
      { key: 'contactName', label: '联系人', type: 'input', required: true },
      { key: 'contactPhone', label: '联系电话', type: 'input', required: true },
      { key: 'city', label: '所在城市', type: 'input', required: true },
      { key: 'settlementMode', label: '结算方式', type: 'select', required: true, options: [
        { label: '现结', value: '现结' },
        { label: '月结', value: '月结' },
        { label: '授信', value: '授信' },
      ] },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: enabledStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  carriers: {
    key: 'carriers',
    title: '物流方资料',
    kicker: 'Master Data',
    description: '物流方主数据统一维护承运商档案、车型和合作状态，供物流单与物流对账复用。',
    primaryNoKey: 'carrierCode',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '物流方编码 / 名称 / 联系人' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    columns: [
      { title: '物流方编码', dataIndex: 'carrierCode', width: 140 },
      { title: '物流方名称', dataIndex: 'carrierName', width: 180 },
      { title: '联系人', dataIndex: 'contactName', width: 110 },
      { title: '联系电话', dataIndex: 'contactPhone', width: 140 },
      { title: '常用车型', dataIndex: 'vehicleType', width: 120 },
      { title: '计费模式', dataIndex: 'priceMode', width: 100, align: 'center' },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '物流方编码', key: 'carrierCode' },
      { label: '物流方名称', key: 'carrierName' },
      { label: '联系人', key: 'contactName' },
      { label: '联系电话', key: 'contactPhone' },
      { label: '常用车型', key: 'vehicleType' },
      { label: '计费模式', key: 'priceMode' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'carrierCode', label: '物流方编码', type: 'input', required: true },
      { key: 'carrierName', label: '物流方名称', type: 'input', required: true },
      { key: 'contactName', label: '联系人', type: 'input', required: true },
      { key: 'contactPhone', label: '联系电话', type: 'input', required: true },
      { key: 'vehicleType', label: '常用车型', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: enabledStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  warehouses: {
    key: 'warehouses',
    title: '仓库资料',
    kicker: 'Master Data',
    description: '仓库主数据统一维护仓库编码、仓库名称、仓库类型、联系人和启用状态，供采购入库、销售出库和物流单页面复用。',
    primaryNoKey: 'warehouseCode',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '仓库编码 / 名称 / 联系人' },
      { key: 'warehouseType', label: '仓库类型', type: 'select', options: [
        { label: '自有仓', value: '自有仓' },
        { label: '合作仓', value: '合作仓' },
        { label: '中转仓', value: '中转仓' },
      ] },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    columns: [
      { title: '仓库编码', dataIndex: 'warehouseCode', width: 140 },
      { title: '仓库名称', dataIndex: 'warehouseName', width: 160 },
      { title: '仓库类型', dataIndex: 'warehouseType', width: 110 },
      { title: '联系人', dataIndex: 'contactName', width: 110 },
      { title: '联系电话', dataIndex: 'contactPhone', width: 140 },
      { title: '仓库地址', dataIndex: 'address', width: 240 },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '仓库编码', key: 'warehouseCode' },
      { label: '仓库名称', key: 'warehouseName' },
      { label: '仓库类型', key: 'warehouseType' },
      { label: '联系人', key: 'contactName' },
      { label: '联系电话', key: 'contactPhone' },
      { label: '仓库地址', key: 'address' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'warehouseCode', label: '仓库编码', type: 'input', required: true },
      { key: 'warehouseName', label: '仓库名称', type: 'input', required: true },
      { key: 'warehouseType', label: '仓库类型', type: 'select', required: true, options: [
        { label: '自有仓', value: '自有仓' },
        { label: '合作仓', value: '合作仓' },
        { label: '中转仓', value: '中转仓' },
      ] },
      { key: 'contactName', label: '联系人', type: 'input', required: true },
      { key: 'contactPhone', label: '联系电话', type: 'input', required: true },
      { key: 'address', label: '仓库地址', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: enabledStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
}
