import {
  getMaterialCategoryOptions,
  materialCategoryOptions,
  materialGradeOptions,
} from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import { actionSet, formatInteger } from './shared'

export const materialsPageConfig: ModulePageConfig = {
  key: 'material',
  title: '商品资料',
  kicker: 'Master Data',
  description:
    '根据既定商品字段维护主数据页面，支持按编码、品牌、规格和材质统一管理，便于直接对接真实商品接口。',
  primaryNoKey: 'materialCode',
  actions: actionSet,
  filters: [
    {
      key: 'keyword',
      label: '关键字',
      type: 'input',
      placeholder: '商品编码 / 品牌 / 规格',
    },
    {
      key: 'category',
      label: '类别',
      type: 'select',
      options: materialCategoryOptions,
    },
    {
      key: 'material',
      label: '材质',
      type: 'select',
      options: materialGradeOptions,
    },
  ],
  columns: [
    { title: '商品编码', dataIndex: 'materialCode', width: 150 },
    { title: '品牌', dataIndex: 'brand', width: 120 },
    { title: '材质', dataIndex: 'material', width: 120 },
    { title: '类别', dataIndex: 'category', width: 110 },
    { title: '规格', dataIndex: 'spec', width: 100 },
    { title: '长度', dataIndex: 'length', width: 100 },
    { title: '单位', dataIndex: 'unit', width: 90 },
    { title: '数量单位', dataIndex: 'quantityUnit', width: 90 },
    {
      title: '件重/吨',
      dataIndex: 'pieceWeightTon',
      width: 110,
      align: 'right',
      type: 'weight',
    },
    {
      title: '每件支数',
      dataIndex: 'piecesPerBundle',
      width: 110,
      align: 'right',
      type: 'count',
    },
    {
      title: '单价',
      dataIndex: 'unitPrice',
      width: 100,
      align: 'right',
      type: 'amount',
    },
    { title: '批号管理', dataIndex: 'batchNoEnabled', width: 110 },
    { title: '备注', dataIndex: 'remark', width: 180 },
  ],
  detailFields: [
    { label: '商品编码', key: 'materialCode' },
    { label: '品牌', key: 'brand' },
    { label: '材质', key: 'material' },
    { label: '类别', key: 'category' },
    { label: '规格', key: 'spec' },
    { label: '长度', key: 'length' },
    { label: '单位', key: 'unit' },
    { label: '数量单位', key: 'quantityUnit' },
    { label: '件重/吨', key: 'pieceWeightTon', type: 'weight' },
    { label: '每件支数', key: 'piecesPerBundle', type: 'count' },
    { label: '单价', key: 'unitPrice', type: 'amount' },
    { label: '批号管理', key: 'batchNoEnabled' },
    { label: '备注', key: 'remark' },
  ],
  formFields: [
    { key: 'materialCode', label: '商品编码', type: 'input', required: true, row: 1 },
    { key: 'brand', label: '品牌', type: 'input', required: true, row: 1 },
    { key: 'material', label: '材质', type: 'input', required: true, row: 1 },
    {
      key: 'category',
      label: '类别',
      type: 'select',
      required: true,
      options: getMaterialCategoryOptions,
      row: 1,
    },
    { key: 'spec', label: '规格', type: 'input', required: true, row: 2 },
    { key: 'length', label: '长度', type: 'input', required: true, row: 2 },
    { key: 'unit', label: '单位', type: 'input', required: true, row: 2 },
    { key: 'quantityUnit', label: '数量单位', type: 'input', required: true, row: 2 },
    {
      key: 'pieceWeightTon',
      label: '件重/吨',
      type: 'number',
      required: true,
      min: 0,
      precision: 3,
      defaultValue: 0,
      row: 3,
    },
    {
      key: 'piecesPerBundle',
      label: '每件支数',
      type: 'number',
      required: true,
      min: 0,
      precision: 0,
      defaultValue: 0,
      row: 3,
    },
    {
      key: 'unitPrice',
      label: '单价',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      row: 3,
    },
    {
      key: 'batchNoEnabled',
      label: '批号管理',
      type: 'select',
      defaultValue: true,
      options: [
        { label: '启用', value: true },
        { label: '关闭', value: false },
      ],
      row: 3,
    },
    { key: 'remark', label: '备注', type: 'textarea', row: 4, fullRow: true },
  ],
  data: [],
  buildOverview: (rows) => [
    { label: '商品数', value: formatInteger(rows.length) },
    {
      label: '理算品类',
      value: formatInteger(
        rows.filter((row) => row.category === '螺纹钢').length,
      ),
    },
    {
      label: '过磅品类',
      value: formatInteger(
        rows.filter((row) => row.category !== '螺纹钢').length,
      ),
    },
  ],
}
