import type { ModulePageConfig } from '@/types/module-page'
import {
  buildValueOptions,
  getCarrierOptions,
  getCustomerOptions,
  getCustomerProjectOptions,
  getSupplierOptions,
  getWarehouseOptions,
  isPurchaseWeighRequiredCategory,
} from '@/constants/module-options'
import {
  actionSet,
  buildAmountWeightOverview,
  cloneLineItems,
  compactFreightItemColumns,
  compactOrderItemColumns,
  compactPurchaseInboundItemColumns,
  compactPurchaseItemColumns,
  statusMap,
  transformFreightItems,
} from './shared'

export const operationsPageConfigs: Record<string, ModulePageConfig> = {
  'purchase-orders': {
    key: 'purchase-orders',
    title: '采购订单',
    kicker: 'Purchase',
    description: '采购订单按文档字段展示，先交付标准列表、筛选、概览和明细，页面数据通过 RESTful API 返回。',
    primaryNoKey: 'orderNo',
    hidePageHeader: true,
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '单据编号', type: 'input', placeholder: '输入采购订单号' },
      { key: 'supplierName', label: '供应商', type: 'select', options: getSupplierOptions },
      { key: 'status', label: '状态', type: 'select', options: buildValueOptions('草稿', '已审核', '完成采购') },
      { key: 'orderDate', label: '订单日期', type: 'dateRange' },
    ],
    columns: [
      { title: '订单编号', dataIndex: 'orderNo', width: 160 },
      { title: '供应商', dataIndex: 'supplierName', width: 140 },
      { title: '采购员', dataIndex: 'buyerName', width: 110 },
      { title: '订单日期', dataIndex: 'orderDate', width: 120, type: 'date' },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 120 },
    ],
    detailFields: [
      { label: '订单编号', key: 'orderNo' },
      { label: '供应商', key: 'supplierName' },
      { label: '订单日期', key: 'orderDate', type: 'date' },
      { label: '采购员', key: 'buyerName' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'supplierName', label: '供应商', type: 'select', required: true, options: getSupplierOptions },
      { key: 'orderNo', label: '订单编号', type: 'input', required: true },
      { key: 'orderDate', label: '订单日期', type: 'date', required: true },
      { key: 'remark', label: '备注', type: 'input' },
    ],
    itemColumns: compactPurchaseItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'purchase-inbounds': {
    key: 'purchase-inbounds',
    title: '采购入库',
    kicker: 'Purchase',
    description: '采购入库页面承接采购订单，明细行展示码头、批号、结算方式、吨位和金额，适合作为后续库存和供应商对账入口。',
    primaryNoKey: 'inboundNo',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '入库单号', type: 'input', placeholder: '输入采购入库单号' },
      { key: 'supplierName', label: '供应商', type: 'select', options: getSupplierOptions },
      { key: 'status', label: '状态', type: 'select', options: buildValueOptions('草稿', '已审核', '完成入库') },
      { key: 'inboundDate', label: '入库日期', type: 'dateRange' },
    ],
    columns: [
      { title: '入库单号', dataIndex: 'inboundNo', width: 160 },
      { title: '关联订单', dataIndex: 'purchaseOrderNo', width: 160 },
      { title: '供应商', dataIndex: 'supplierName', width: 140 },
      { title: '入库日期', dataIndex: 'inboundDate', width: 120, type: 'date' },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '入库单号', key: 'inboundNo' },
      { label: '关联订单', key: 'purchaseOrderNo' },
      { label: '供应商', key: 'supplierName' },
      { label: '入库日期', key: 'inboundDate', type: 'date' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'inboundNo', label: '入库单号', type: 'input', required: true },
      { key: 'purchaseOrderNo', label: '关联订单', type: 'input', disabled: true, placeholder: '通过上级单据导入' },
      { key: 'supplierName', label: '供应商', type: 'select', required: true, options: getSupplierOptions },
      { key: 'inboundDate', label: '入库日期', type: 'date', required: true },
      { key: 'remark', label: '备注', type: 'input' },
    ],
    parentImport: {
      parentModuleKey: 'purchase-orders',
      label: '上级采购订单',
      parentFieldKey: 'purchaseOrderNo',
      parentDisplayFieldKey: 'orderNo',
      buttonText: '导入采购订单明细',
      mapParentToDraft: (parentRecord) => ({
        supplierName: parentRecord.supplierName || '',
      }),
      transformItems: (parentRecord) => cloneLineItems(
        Array.isArray(parentRecord.items)
          ? parentRecord.items.map((item) => ({
              ...item,
              sourcePurchaseOrderItemId: item.id,
              settlementMode: isPurchaseWeighRequiredCategory(item.category) ? '过磅' : '理算',
            }))
          : [],
        'purchase-inbound-item',
      ),
    },
    itemColumns: compactPurchaseInboundItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'sales-orders': {
    key: 'sales-orders',
    title: '销售订单',
    kicker: 'Sales',
    description: '销售订单围绕客户、项目和商品明细展开，页面默认展示完整业务字段，保持录入和查看口径一致。',
    primaryNoKey: 'orderNo',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '订单编号', type: 'input', placeholder: '输入销售订单号' },
      { key: 'customerName', label: '客户', type: 'select', options: getCustomerOptions },
      { key: 'status', label: '状态', type: 'select', options: buildValueOptions('草稿', '已审核', '完成销售') },
      { key: 'deliveryDate', label: '送货日期', type: 'dateRange' },
    ],
    columns: [
      { title: '关联入库单', dataIndex: 'purchaseInboundNo', width: 180 },
      { title: '订单编号', dataIndex: 'orderNo', width: 160 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '客户', dataIndex: 'customerName', width: 140 },
      { title: '销售员', dataIndex: 'salesName', width: 110 },
      { title: '送货日期', dataIndex: 'deliveryDate', width: 120, type: 'date' },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '关联入库单', key: 'purchaseInboundNo' },
      { label: '订单编号', key: 'orderNo' },
      { label: '项目', key: 'projectName' },
      { label: '客户', key: 'customerName' },
      { label: '销售员', key: 'salesName' },
      { label: '送货日期', key: 'deliveryDate', type: 'date' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'purchaseInboundNo', label: '关联入库单', type: 'input', disabled: true, placeholder: '通过采购入库导入，可追加多个单号' },
      { key: 'orderNo', label: '订单编号', type: 'input', required: true },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: getCustomerOptions },
      { key: 'projectName', label: '项目', type: 'select', required: true, options: getCustomerProjectOptions },
      { key: 'salesName', label: '销售员', type: 'input', required: true },
      { key: 'deliveryDate', label: '送货日期', type: 'date', required: true },
      { key: 'remark', label: '备注', type: 'input' },
    ],
    parentImport: {
      parentModuleKey: 'purchase-inbounds',
      label: '上级采购入库单',
      parentFieldKey: 'purchaseInboundNo',
      parentDisplayFieldKey: 'inboundNo',
      buttonText: '导入采购入库明细',
      transformItems: (parentRecord) => cloneLineItems(
        Array.isArray(parentRecord.items)
          ? parentRecord.items.map((item) => ({
              ...item,
              sourceInboundItemId: item.id,
            }))
          : [],
        'sales-order-item',
      ),
    },
    itemColumns: compactPurchaseItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'sales-outbounds': {
    key: 'sales-outbounds',
    title: '销售出库',
    kicker: 'Sales',
    description: '销售出库页承担发货和库存扣减，单据审核后会驱动关联销售订单进入完成销售，物流单和客户对账继续沿此单据下游流转。',
    primaryNoKey: 'outboundNo',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '出库单号', type: 'input', placeholder: '输入销售出库单号' },
      { key: 'customerName', label: '客户', type: 'select', options: getCustomerOptions },
      { key: 'status', label: '状态', type: 'select', options: buildValueOptions('草稿', '已审核') },
      { key: 'outboundDate', label: '出库日期', type: 'dateRange' },
    ],
    columns: [
      { title: '出库单号', dataIndex: 'outboundNo', width: 160 },
      { title: '关联订单', dataIndex: 'salesOrderNo', width: 160 },
      { title: '客户', dataIndex: 'customerName', width: 140 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '仓库', dataIndex: 'warehouseName', width: 120 },
      { title: '出库日期', dataIndex: 'outboundDate', width: 120, type: 'date' },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '出库单号', key: 'outboundNo' },
      { label: '关联订单', key: 'salesOrderNo' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '仓库', key: 'warehouseName' },
      { label: '出库日期', key: 'outboundDate', type: 'date' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'outboundNo', label: '出库单号', type: 'input', required: true },
      { key: 'salesOrderNo', label: '关联订单', type: 'input', disabled: true, placeholder: '通过上级单据导入' },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: getCustomerOptions },
      { key: 'projectName', label: '项目', type: 'input', required: true },
      { key: 'warehouseName', label: '仓库', type: 'select', required: true, options: getWarehouseOptions() },
      { key: 'outboundDate', label: '出库日期', type: 'date', required: true },
      { key: 'remark', label: '备注', type: 'input' },
    ],
    parentImport: {
      parentModuleKey: 'sales-orders',
      label: '上级销售订单',
      parentFieldKey: 'salesOrderNo',
      parentDisplayFieldKey: 'orderNo',
      buttonText: '导入销售订单明细',
      enforceUniqueRelation: true,
      mapParentToDraft: (parentRecord) => ({
        customerName: parentRecord.customerName || '',
        projectName: parentRecord.projectName || '',
      }),
      transformItems: (parentRecord) => cloneLineItems(parentRecord.items, 'sales-outbound-item'),
    },
    itemColumns: compactPurchaseItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'freight-bills': {
    key: 'freight-bills',
    title: '物流单',
    kicker: 'Freight',
    description: '物流单页面按现版逻辑建立在销售出库之上，支持关联出库单、自动计算总重量和总运费，并继续流向物流对账。',
    primaryNoKey: 'billNo',
    actions: [
      { label: '新增物流单', type: 'primary' },
      { label: '生成提货清单', type: 'default' },
      { label: '标记送达', type: 'default' },
    ],
    filters: [
      { key: 'keyword', label: '物流单号', type: 'input', placeholder: '输入物流单号' },
      { key: 'carrierName', label: '物流商', type: 'select', options: getCarrierOptions() },
      { key: 'status', label: '审核状态', type: 'select', options: [
        { label: '未审核', value: '未审核' },
        { label: '已审核', value: '已审核' },
      ] },
      { key: 'billTime', label: '单据日期', type: 'dateRange' },
    ],
    columns: [
      { title: '物流单号', dataIndex: 'billNo', width: 160 },
      { title: '物流商', dataIndex: 'carrierName', width: 140 },
      { title: '客户', dataIndex: 'customerName', width: 140 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '单据日期', dataIndex: 'billTime', width: 120, type: 'date' },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '单价', dataIndex: 'unitPrice', width: 100, align: 'right', type: 'amount' },
      { title: '总运费', dataIndex: 'totalFreight', width: 110, align: 'right', type: 'amount' },
      { title: '审核状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '送达状态', dataIndex: 'deliveryStatus', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '物流单号', key: 'billNo' },
      { label: '关联出库单', key: 'outboundNo' },
      { label: '物流商', key: 'carrierName' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '单据日期', key: 'billTime', type: 'date' },
      { label: '单价', key: 'unitPrice', type: 'amount' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总运费', key: 'totalFreight', type: 'amount' },
      { label: '审核状态', key: 'status', type: 'status' },
      { label: '送达状态', key: 'deliveryStatus', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'billNo', label: '物流单号', type: 'input', required: true },
      { key: 'outboundNo', label: '关联出库单', type: 'input', disabled: true, placeholder: '通过上级单据导入' },
      { key: 'carrierName', label: '物流商', type: 'select', required: true, options: getCarrierOptions() },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: getCustomerOptions },
      { key: 'projectName', label: '项目', type: 'input', required: true },
      { key: 'billTime', label: '单据日期', type: 'date', required: true },
      { key: 'unitPrice', label: '单价', type: 'number', required: true, min: 0, precision: 2, defaultValue: 0 },
      { key: 'status', label: '审核状态', type: 'select', defaultValue: '未审核', options: [
        { label: '未审核', value: '未审核' },
        { label: '已审核', value: '已审核' },
      ] },
      { key: 'deliveryStatus', label: '送达状态', type: 'select', defaultValue: '未送达', options: [
        { label: '未送达', value: '未送达' },
        { label: '已送达', value: '已送达' },
      ] },
      { key: 'remark', label: '备注', type: 'input' },
    ],
    parentImport: {
      parentModuleKey: 'sales-outbounds',
      label: '上级销售出库单',
      parentFieldKey: 'outboundNo',
      parentDisplayFieldKey: 'outboundNo',
      buttonText: '导入上级销售出库单',
      mapParentToDraft: (parentRecord) => ({
        customerName: parentRecord.customerName || '',
        projectName: parentRecord.projectName || '',
      }),
      transformItems: transformFreightItems,
    },
    itemColumns: compactFreightItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalFreight'),
    statusMap,
    rowHighlightStatuses: ['未审核', '未送达'],
  },
  'purchase-contracts': {
    key: 'purchase-contracts',
    title: '采购合同',
    kicker: 'Contracts',
    description: '采购合同按供应商、签约日期、执行周期和商品明细统一管理，沿用通用单据页风格并支持后续直接接入真实合同接口。',
    primaryNoKey: 'contractNo',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '合同编号', type: 'input', placeholder: '输入采购合同号' },
      { key: 'supplierName', label: '供应商', type: 'select', options: getSupplierOptions },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '执行中', value: '执行中' },
        { label: '已签署', value: '已签署' },
        { label: '已归档', value: '已归档' },
      ] },
      { key: 'signDate', label: '签订日期', type: 'dateRange' },
    ],
    columns: [
      { title: '合同编号', dataIndex: 'contractNo', width: 170 },
      { title: '供应商', dataIndex: 'supplierName', width: 150 },
      { title: '签订日期', dataIndex: 'signDate', width: 120, type: 'date' },
      { title: '生效日期', dataIndex: 'effectiveDate', width: 120, type: 'date' },
      { title: '截止日期', dataIndex: 'expireDate', width: 120, type: 'date' },
      { title: '采购员', dataIndex: 'buyerName', width: 110 },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 180 },
    ],
    detailFields: [
      { label: '合同编号', key: 'contractNo' },
      { label: '供应商', key: 'supplierName' },
      { label: '签订日期', key: 'signDate', type: 'date' },
      { label: '生效日期', key: 'effectiveDate', type: 'date' },
      { label: '截止日期', key: 'expireDate', type: 'date' },
      { label: '采购员', key: 'buyerName' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'contractNo', label: '合同编号', type: 'input', required: true },
      { key: 'supplierName', label: '供应商', type: 'select', required: true, options: getSupplierOptions },
      { key: 'signDate', label: '签订日期', type: 'date', required: true },
      { key: 'effectiveDate', label: '生效日期', type: 'date', required: true },
      { key: 'expireDate', label: '截止日期', type: 'date', required: true },
      { key: 'buyerName', label: '采购员', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '草稿', options: [
        { label: '草稿', value: '草稿' },
        { label: '执行中', value: '执行中' },
        { label: '已签署', value: '已签署' },
        { label: '已归档', value: '已归档' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    itemColumns: compactOrderItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
  'sales-contracts': {
    key: 'sales-contracts',
    title: '销售合同',
    kicker: 'Contracts',
    description: '销售合同围绕客户、项目、签约周期和商品明细管理，沿用通用业务页样式，方便后续继续接订单关联或打印。',
    primaryNoKey: 'contractNo',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '合同编号', type: 'input', placeholder: '输入销售合同号' },
      { key: 'customerName', label: '客户', type: 'select', options: getCustomerOptions },
      { key: 'status', label: '状态', type: 'select', options: [
        { label: '草稿', value: '草稿' },
        { label: '执行中', value: '执行中' },
        { label: '已签署', value: '已签署' },
        { label: '已归档', value: '已归档' },
      ] },
      { key: 'signDate', label: '签订日期', type: 'dateRange' },
    ],
    columns: [
      { title: '合同编号', dataIndex: 'contractNo', width: 170 },
      { title: '客户', dataIndex: 'customerName', width: 150 },
      { title: '项目', dataIndex: 'projectName', width: 180 },
      { title: '签订日期', dataIndex: 'signDate', width: 120, type: 'date' },
      { title: '生效日期', dataIndex: 'effectiveDate', width: 120, type: 'date' },
      { title: '截止日期', dataIndex: 'expireDate', width: 120, type: 'date' },
      { title: '销售员', dataIndex: 'salesName', width: 110 },
      { title: '总吨位', dataIndex: 'totalWeight', width: 100, align: 'right', type: 'weight' },
      { title: '总金额', dataIndex: 'totalAmount', width: 110, align: 'right', type: 'amount' },
      { title: '状态', dataIndex: 'status', width: 110, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '合同编号', key: 'contractNo' },
      { label: '客户', key: 'customerName' },
      { label: '项目', key: 'projectName' },
      { label: '签订日期', key: 'signDate', type: 'date' },
      { label: '生效日期', key: 'effectiveDate', type: 'date' },
      { label: '截止日期', key: 'expireDate', type: 'date' },
      { label: '销售员', key: 'salesName' },
      { label: '总吨位', key: 'totalWeight', type: 'weight' },
      { label: '总金额', key: 'totalAmount', type: 'amount' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'contractNo', label: '合同编号', type: 'input', required: true },
      { key: 'customerName', label: '客户', type: 'select', required: true, options: getCustomerOptions },
      { key: 'projectName', label: '项目', type: 'input', required: true },
      { key: 'signDate', label: '签订日期', type: 'date', required: true },
      { key: 'effectiveDate', label: '生效日期', type: 'date', required: true },
      { key: 'expireDate', label: '截止日期', type: 'date', required: true },
      { key: 'salesName', label: '销售员', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '草稿', options: [
        { label: '草稿', value: '草稿' },
        { label: '执行中', value: '执行中' },
        { label: '已签署', value: '已签署' },
        { label: '已归档', value: '已归档' },
      ] },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    itemColumns: compactOrderItemColumns,
    data: [],
    buildOverview: (rows) => buildAmountWeightOverview(rows, 'totalAmount'),
    statusMap,
    rowHighlightStatuses: ['草稿'],
  },
}
