import type { ModulePageConfig } from '@/types/module-page'
import { BILL_STATUS_LABEL } from './filter-labels'
import { buildFinanceOverview, statusMap } from './shared'
import i18next from 'i18next'

export const paymentsPageConfig: ModulePageConfig = {
  key: 'payment',
  title: i18next.t('modules.pages.payment.payment'),
  kicker: 'Finance',
  description:
    i18next.t('modules.pages.payment.paymentDesc'),
  primaryNoKey: 'paymentNo',
  actions: [{ key: 'create_payment', label: i18next.t('modules.pages.payment.createPayment'), type: 'primary' }],
  filters: [
    {
      key: 'businessType',
      label: i18next.t('modules.pages.payment.businessType'),
      type: 'select',
      options: [
        { label: i18next.t('modules.pages.payment.supplier'), value: '供应商' },
        { label: i18next.t('modules.pages.payment.carrier'), value: '物流商' },
      ],
    },
    {
      key: 'status',
      label: BILL_STATUS_LABEL,
      type: 'select',
      options: [
        { label: i18next.t('modules.pages.payment.draft'), value: '草稿' },
        { label: i18next.t('modules.pages.payment.paid'), value: '已付款' },
      ],
    },
    { key: 'paymentDate', label: i18next.t('modules.pages.payment.paymentDate'), type: 'dateRange' },
  ],
  columns: [
    { title: i18next.t('modules.pages.payment.paymentNo'), dataIndex: 'paymentNo', width: 170 },
    { title: i18next.t('modules.pages.payment.businessType'), dataIndex: 'businessType', width: 110 },
    { title: i18next.t('modules.pages.payment.counterparty'), dataIndex: 'counterpartyName', width: 160 },
    { title: i18next.t('modules.pages.payment.paymentDate'), dataIndex: 'paymentDate', width: 120, type: 'date' },
    { title: i18next.t('modules.pages.payment.payType'), dataIndex: 'payType', width: 120 },
    {
      title: i18next.t('modules.pages.payment.amount'),
      dataIndex: 'amount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: i18next.t('modules.pages.payment.status'),
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
  ],
  defaultHiddenColumnKeys: ['payType'],
  detailFields: [
    { label: i18next.t('modules.pages.payment.paymentNo'), key: 'paymentNo', row: 1 },
    { label: i18next.t('modules.pages.payment.businessType'), key: 'businessType', row: 1 },
    { label: i18next.t('modules.pages.payment.counterparty'), key: 'counterpartyName', row: 1 },
    { label: i18next.t('modules.pages.payment.relatedStatement'), key: 'sourceStatementId', row: 1 },
    { label: i18next.t('modules.pages.payment.paymentDate'), key: 'paymentDate', type: 'date', row: 2 },
    { label: i18next.t('modules.pages.payment.payType'), key: 'payType', row: 2 },
    { label: i18next.t('modules.pages.payment.amount'), key: 'amount', type: 'amount', row: 2 },
    { label: i18next.t('modules.pages.payment.status'), key: 'status', type: 'status', row: 2 },
    { label: i18next.t('modules.pages.payment.operator'), key: 'operatorName', row: 3 },
    { label: i18next.t('modules.pages.payment.remark'), key: 'remark', row: 4, fullRow: true },
  ],
  formFields: [
    {
      key: 'paymentNo',
      label: i18next.t('modules.pages.payment.paymentNo'),
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'businessType',
      label: i18next.t('modules.pages.payment.businessType'),
      type: 'select',
      required: true,
      options: [
        { label: i18next.t('modules.pages.payment.supplier'), value: '供应商' },
        { label: i18next.t('modules.pages.payment.carrier'), value: '物流商' },
      ],
      row: 1,
    },
    {
      key: 'counterpartyName',
      label: i18next.t('modules.pages.payment.counterparty'),
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'sourceStatementId',
      label: i18next.t('modules.pages.payment.relatedStatement'),
      type: 'select',
      required: true,
      row: 1,
    },
    {
      key: 'paymentDate',
      label: i18next.t('modules.pages.payment.paymentDate'),
      type: 'date',
      required: true,
      row: 2,
    },
    {
      key: 'payType',
      label: i18next.t('modules.pages.payment.payType'),
      type: 'select',
      required: true,
      options: [
        { label: i18next.t('modules.pages.payment.bankTransfer'), value: '银行转账' },
        { label: i18next.t('modules.pages.payment.bankAcceptance'), value: '银行承兑' },
        { label: i18next.t('modules.pages.payment.cash'), value: '现金' },
      ],
      row: 2,
    },
    {
      key: 'amount',
      label: i18next.t('modules.pages.payment.amount'),
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      row: 2,
    },
    {
      key: 'status',
      label: i18next.t('modules.pages.payment.status'),
      type: 'select',
      defaultValue: '草稿',
      options: [
        { label: i18next.t('modules.pages.payment.draft'), value: '草稿' },
        { label: i18next.t('modules.pages.payment.paid'), value: '已付款' },
      ],
      row: 2,
    },
    {
      key: 'operatorName',
      label: i18next.t('modules.pages.payment.operator'),
      type: 'input',
      required: true,
      row: 3,
    },
    { key: 'remark', label: i18next.t('modules.pages.payment.remark'), type: 'textarea', row: 4, fullRow: true },
  ],
  saveFields: {
    scalar: [
      'paymentNo',
      'businessType',
      'counterpartyName',
      'sourceStatementId',
      'paymentDate',
      'payType',
      'amount',
      'status',
      'operatorName',
      'remark',
    ],
  },
  data: [],
  buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
  statusMap,
  rowHighlightStatuses: ['草稿'],
}
