import type { ModulePageConfig } from '@/types/module-page'
import { BILL_STATUS_LABEL } from './filter-labels'
import { buildFinanceOverview, statusMap } from './shared'

export const paymentsPageConfig: ModulePageConfig = {
  key: 'payment',
  title: '付款单',
  kicker: 'Finance',
  description:
    '付款单统一承接供应商付款和物流付款，页面先以业务类型、往来单位、金额和状态为主。',
  primaryNoKey: 'paymentNo',
  actions: [{ key: 'create_payment', label: '新增付款单', type: 'primary' }],
  filters: [
    {
      key: 'businessType',
      label: '业务类型',
      type: 'select',
      options: [
        { label: '供应商', value: '供应商' },
        { label: '物流商', value: '物流商' },
      ],
    },
    {
      key: 'status',
      label: BILL_STATUS_LABEL,
      type: 'select',
      options: [
        { label: '草稿', value: '草稿' },
        { label: '已付款', value: '已付款' },
      ],
    },
    { key: 'paymentDate', label: '付款日期', type: 'dateRange' },
  ],
  columns: [
    { title: '付款单号', dataIndex: 'paymentNo', width: 170 },
    { title: '业务类型', dataIndex: 'businessType', width: 110 },
    { title: '往来单位', dataIndex: 'counterpartyName', width: 160 },
    { title: '付款日期', dataIndex: 'paymentDate', width: 120, type: 'date' },
    { title: '付款方式', dataIndex: 'payType', width: 120 },
    {
      title: '金额',
      dataIndex: 'amount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
  ],
  defaultHiddenColumnKeys: ['payType'],
  detailFields: [
    { label: '付款单号', key: 'paymentNo', row: 1 },
    { label: '业务类型', key: 'businessType', row: 1 },
    { label: '往来单位', key: 'counterpartyName', row: 1 },
    { label: '关联对账单', key: 'sourceStatementId', row: 1 },
    { label: '付款日期', key: 'paymentDate', type: 'date', row: 2 },
    { label: '付款方式', key: 'payType', row: 2 },
    { label: '金额', key: 'amount', type: 'amount', row: 2 },
    { label: '状态', key: 'status', type: 'status', row: 2 },
    { label: '经办人', key: 'operatorName', row: 3 },
    { label: '备注', key: 'remark', row: 4, fullRow: true },
  ],
  formFields: [
    {
      key: 'paymentNo',
      label: '付款单号',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'businessType',
      label: '业务类型',
      type: 'select',
      required: true,
      options: [
        { label: '供应商', value: '供应商' },
        { label: '物流商', value: '物流商' },
      ],
      row: 1,
    },
    {
      key: 'counterpartyName',
      label: '往来单位',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'sourceStatementId',
      label: '关联对账单',
      type: 'select',
      required: true,
      row: 1,
    },
    {
      key: 'paymentDate',
      label: '付款日期',
      type: 'date',
      required: true,
      row: 2,
    },
    {
      key: 'payType',
      label: '付款方式',
      type: 'select',
      required: true,
      options: [
        { label: '银行转账', value: '银行转账' },
        { label: '银行承兑', value: '银行承兑' },
        { label: '现金', value: '现金' },
      ],
      row: 2,
    },
    {
      key: 'amount',
      label: '金额',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      row: 2,
    },
    {
      key: 'status',
      label: '状态',
      type: 'select',
      defaultValue: '草稿',
      options: [
        { label: '草稿', value: '草稿' },
        { label: '已付款', value: '已付款' },
      ],
      row: 2,
    },
    {
      key: 'operatorName',
      label: '经办人',
      type: 'input',
      required: true,
      row: 3,
    },
    { key: 'remark', label: '备注', type: 'textarea', row: 4, fullRow: true },
  ],
  saveFields: {
    scalar: [
      'paymentNo',
      'businessType',
      'counterpartyName',
      'sourceStatementId',
      'paymentDate',
      'payType',
      'amount',
      'status',
      'operatorName',
      'remark',
    ],
  },
  data: [],
  buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
  statusMap,
  rowHighlightStatuses: ['草稿'],
}
