import { getSupplierOptions } from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import { SUPPLIER_NAME_LABEL } from './filter-labels'
import {
  formatAmount,
  formatInteger,
  formatWeight,
  statusMap,
  sumBy,
} from './shared'

export const pendingInvoiceReceiptReportPageConfig: ModulePageConfig = {
  key: 'pending-invoice-receipt-report',
  title: '未收票报表',
  kicker: 'Finance',
  description:
    '未收票报表按采购订单明细对比已收票明细，展示尚未收票的剩余重量（吨）与金额，供采购和财务快速追踪到票进度。',
  readOnly: true,
  actions: [{ key: 'export', label: '导出', type: 'primary' }],
  filters: [
    {
      key: 'keyword',
      label: '关键字',
      type: 'input',
      placeholder: '采购单号 / 供应商 / 商品编码 / 规格',
    },
    {
      key: 'supplierName',
      label: SUPPLIER_NAME_LABEL,
      type: 'select',
      options: getSupplierOptions,
    },
    { key: 'orderDate', label: '采购日期', type: 'dateRange' },
  ],
  columns: [
    { title: '采购订单号', dataIndex: 'orderNo', width: 170 },
    { title: '供应商', dataIndex: 'supplierName', width: 150 },
    { title: '开票方抬头', dataIndex: 'invoiceTitle', width: 170 },
    { title: '采购日期', dataIndex: 'orderDate', width: 120, type: 'date' },
    { title: '商品编码', dataIndex: 'materialCode', width: 140 },
    { title: '品牌', dataIndex: 'brand', width: 110 },
    { title: '材质', dataIndex: 'material', width: 110 },
    { title: '类别', dataIndex: 'category', width: 100 },
    { title: '规格', dataIndex: 'spec', width: 100 },
    { title: '长度', dataIndex: 'length', width: 100 },
    {
      title: '订单数量',
      dataIndex: 'orderQuantity',
      width: 100,
      align: 'right',
      type: 'count',
    },
    { title: '数量单位', dataIndex: 'quantityUnit', width: 90 },
    {
      title: '订单重量（吨）',
      dataIndex: 'orderWeightTon',
      width: 124,
      align: 'right',
      type: 'weight',
    },
    {
      title: '已收票重量（吨）',
      dataIndex: 'receivedInvoiceWeightTon',
      width: 136,
      align: 'right',
      type: 'weight',
    },
    {
      title: '未收票重量（吨）',
      dataIndex: 'pendingInvoiceWeightTon',
      width: 136,
      align: 'right',
      type: 'weight',
    },
    {
      title: '单价',
      dataIndex: 'unitPrice',
      width: 100,
      align: 'right',
      type: 'amount',
    },
    {
      title: '订单金额',
      dataIndex: 'orderAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '已收票金额',
      dataIndex: 'receivedInvoiceAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '未收票金额',
      dataIndex: 'pendingInvoiceAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      type: 'status',
      align: 'center',
    },
  ],
  detailFields: [
    { label: '采购订单号', key: 'orderNo' },
    { label: '供应商', key: 'supplierName' },
    { label: '开票方抬头', key: 'invoiceTitle' },
    { label: '采购日期', key: 'orderDate', type: 'date' },
    { label: '商品编码', key: 'materialCode' },
    { label: '品牌', key: 'brand' },
    { label: '材质', key: 'material' },
    { label: '类别', key: 'category' },
    { label: '规格', key: 'spec' },
    { label: '长度', key: 'length' },
    { label: '订单数量', key: 'orderQuantity', type: 'count' },
    { label: '数量单位', key: 'quantityUnit' },
    { label: '订单重量（吨）', key: 'orderWeightTon', type: 'weight' },
    {
      label: '已收票重量（吨）',
      key: 'receivedInvoiceWeightTon',
      type: 'weight',
    },
    {
      label: '未收票重量（吨）',
      key: 'pendingInvoiceWeightTon',
      type: 'weight',
    },
    { label: '单价', key: 'unitPrice', type: 'amount' },
    { label: '订单金额', key: 'orderAmount', type: 'amount' },
    { label: '已收票金额', key: 'receivedInvoiceAmount', type: 'amount' },
    { label: '未收票金额', key: 'pendingInvoiceAmount', type: 'amount' },
    { label: '状态', key: 'status', type: 'status' },
  ],
  data: [],
  buildOverview: (rows) => [
    { label: '待跟进明细', value: formatInteger(rows.length) },
    {
      label: '未收票重量（吨）',
      value: formatWeight(sumBy(rows, 'pendingInvoiceWeightTon')),
    },
    {
      label: '未收票金额',
      value: formatAmount(sumBy(rows, 'pendingInvoiceAmount')),
    },
  ],
  statusMap,
  rowHighlightStatuses: ['未收票'],
}
