import { customerOptions } from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import { BILL_STATUS_LABEL, CUSTOMER_NAME_LABEL } from './filter-labels'
import { buildFinanceOverview, statusMap } from './shared'

export const receiptsPageConfig: ModulePageConfig = {
  key: 'receipt',
  title: '收款单',
  kicker: 'Finance',
  description:
    '收款单页面用于承接客户回款，当前重点确认单据字段、状态和列表交互，不先接核销明细。',
  primaryNoKey: 'receiptNo',
  actions: [{ key: 'create_receipt', label: '新增收款单', type: 'primary' }],
  filters: [
    {
      key: 'customerName',
      label: CUSTOMER_NAME_LABEL,
      type: 'select',
      options: customerOptions,
    },
    {
      key: 'status',
      label: BILL_STATUS_LABEL,
      type: 'select',
      options: [
        { label: '草稿', value: '草稿' },
        { label: '已收款', value: '已收款' },
      ],
    },
    { key: 'receiptDate', label: '收款日期', type: 'dateRange' },
  ],
  columns: [
    { title: '收款单号', dataIndex: 'receiptNo', width: 170 },
    { title: '客户', dataIndex: 'customerName', width: 140 },
    { title: '项目', dataIndex: 'projectName', width: 180 },
    { title: '收款日期', dataIndex: 'receiptDate', width: 120, type: 'date' },
    { title: '收款方式', dataIndex: 'payType', width: 120 },
    {
      title: '金额',
      dataIndex: 'amount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
  ],
  defaultHiddenColumnKeys: ['projectName', 'payType'],
  detailFields: [
    { label: '收款单号', key: 'receiptNo', row: 1 },
    { label: '客户', key: 'customerName', row: 1 },
    { label: '项目', key: 'projectName', row: 1 },
    { label: '关联对账单', key: 'sourceStatementId', row: 1 },
    { label: '收款日期', key: 'receiptDate', type: 'date', row: 2 },
    { label: '收款方式', key: 'payType', row: 2 },
    { label: '金额', key: 'amount', type: 'amount', row: 2 },
    { label: '状态', key: 'status', type: 'status', row: 2 },
    { label: '经办人', key: 'operatorName', row: 3 },
    { label: '备注', key: 'remark', row: 4, fullRow: true },
  ],
  formFields: [
    {
      key: 'receiptNo',
      label: '收款单号',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'customerName',
      label: '客户',
      type: 'select',
      required: true,
      options: customerOptions,
      row: 1,
    },
    {
      key: 'projectName',
      label: '项目',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'sourceStatementId',
      label: '关联对账单',
      type: 'select',
      required: true,
      row: 1,
    },
    {
      key: 'receiptDate',
      label: '收款日期',
      type: 'date',
      required: true,
      row: 2,
    },
    {
      key: 'payType',
      label: '收款方式',
      type: 'select',
      required: true,
      options: [
        { label: '银行转账', value: '银行转账' },
        { label: '银行承兑', value: '银行承兑' },
        { label: '承兑汇票', value: '承兑汇票' },
        { label: '现金', value: '现金' },
      ],
      row: 2,
    },
    {
      key: 'amount',
      label: '金额',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      row: 2,
    },
    {
      key: 'status',
      label: '状态',
      type: 'select',
      defaultValue: '草稿',
      options: [
        { label: '草稿', value: '草稿' },
        { label: '已收款', value: '已收款' },
      ],
      row: 2,
    },
    {
      key: 'operatorName',
      label: '经办人',
      type: 'input',
      required: true,
      row: 3,
    },
    { key: 'remark', label: '备注', type: 'textarea', row: 4, fullRow: true },
  ],
  saveFields: {
    scalar: [
      'receiptNo',
      'customerName',
      'projectName',
      'sourceStatementId',
      'receiptDate',
      'payType',
      'amount',
      'status',
      'operatorName',
      'remark',
    ],
  },
  data: [],
  buildOverview: (rows) => buildFinanceOverview(rows, 'amount'),
  statusMap,
  rowHighlightStatuses: ['草稿'],
}
