import {
  getSupplierOptions,
  statementStatusOptions,
} from '@/constants/module-options'
import type { ModulePageConfig } from '@/types/module-page'
import { BILL_STATUS_LABEL, SUPPLIER_NAME_LABEL } from './filter-labels'
import {
  buildStatementOverview,
  compactBatchSupplierStatementItemColumns,
  statusMap,
} from './shared'

export const supplierStatementPageConfig: ModulePageConfig = {
  key: 'supplier-statement',
  title: '供应商对账单',
  kicker: 'Statements',
  description:
    '供应商对账单按已审核采购入库明细口径组织，生成后保留来源入库行，便于逐项核对采购数量、单价和金额。',
  primaryNoKey: 'statementNo',
  actions: [
    { key: 'generate_statement', label: '生成对账单', type: 'primary' },
  ],
  filters: [
    {
      key: 'supplierName',
      label: SUPPLIER_NAME_LABEL,
      type: 'select',
      options: getSupplierOptions,
    },
    {
      key: 'status',
      label: BILL_STATUS_LABEL,
      type: 'select',
      options: statementStatusOptions,
    },
    { key: 'endDate', label: '账期', type: 'dateRange' },
  ],
  columns: [
    { title: '对账单号', dataIndex: 'statementNo', width: 170 },
    { title: '供应商', dataIndex: 'supplierName', width: 140 },
    { title: '开始日期', dataIndex: 'startDate', width: 120, type: 'date' },
    { title: '结束日期', dataIndex: 'endDate', width: 120, type: 'date' },
    {
      title: '采购金额',
      dataIndex: 'purchaseAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '付款金额',
      dataIndex: 'paymentAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '期末余额',
      dataIndex: 'closingAmount',
      width: 110,
      align: 'right',
      type: 'amount',
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 110,
      type: 'status',
      align: 'center',
    },
  ],
  detailFields: [
    { label: '对账单号', key: 'statementNo' },
    { label: '供应商', key: 'supplierName' },
    { label: '开始日期', key: 'startDate', type: 'date' },
    { label: '结束日期', key: 'endDate', type: 'date' },
    { label: '采购金额', key: 'purchaseAmount', type: 'amount' },
    { label: '付款金额', key: 'paymentAmount', type: 'amount' },
    { label: '期末余额', key: 'closingAmount', type: 'amount' },
    { label: '状态', key: 'status', type: 'status' },
    { label: '备注', key: 'remark' },
  ],
  formFields: [
    {
      key: 'statementNo',
      label: '对账单号',
      type: 'input',
      required: true,
      row: 1,
    },
    {
      key: 'supplierName',
      label: '供应商',
      type: 'select',
      required: true,
      options: getSupplierOptions,
      row: 1,
    },
    {
      key: 'startDate',
      label: '开始日期',
      type: 'date',
      required: true,
      row: 1,
    },
    { key: 'endDate', label: '结束日期', type: 'date', required: true, row: 1 },
    {
      key: 'purchaseAmount',
      label: '采购金额',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 2,
    },
    {
      key: 'closingAmount',
      label: '期末余额',
      type: 'number',
      required: true,
      min: 0,
      precision: 2,
      defaultValue: 0,
      disabled: true,
      row: 2,
    },
    {
      key: 'status',
      label: '状态',
      type: 'select',
      defaultValue: '待确认',
      options: statementStatusOptions,
      row: 2,
    },
    { key: 'remark', label: '备注', type: 'textarea', row: 3, fullRow: true },
  ],
  saveFields: {
    scalar: [
      'statementNo',
      'sourceInboundNos',
      'supplierName',
      'startDate',
      'endDate',
      'purchaseAmount',
      'paymentAmount',
      'closingAmount',
      'status',
      'remark',
    ],
    lineItem: [
      'sourceNo',
      'materialCode',
      'brand',
      'category',
      'material',
      'spec',
      'length',
      'unit',
      'batchNo',
      'quantity',
      'quantityUnit',
      'pieceWeightTon',
      'piecesPerBundle',
      'weightTon',
      'weighWeightTon',
      'weightAdjustmentTon',
      'weightAdjustmentAmount',
      'unitPrice',
      'amount',
    ],
  },
  itemColumns: compactBatchSupplierStatementItemColumns,
  data: [],
  buildOverview: (rows) =>
    buildStatementOverview(
      rows,
      'purchaseAmount',
      'paymentAmount',
      'closingAmount',
    ),
  statusMap,
  rowHighlightStatuses: ['待确认'],
}
