import type { ModulePageConfig } from '@/types/module-page'
import {
  enabledStatusOptions,
  roleDataScopeOptions,
  roleTypeOptions,
  userAccountDataScopeOptions,
} from '@/constants/module-options'
import {
  actionSet,
  buildMasterOverview,
  formatInteger,
  statusMap,
} from './shared'

const operationLogActionOptions = [
  { label: '查询', value: '查询' },
  { label: '查看', value: '查看' },
  { label: '新增', value: '新增' },
  { label: '编辑', value: '编辑' },
  { label: '删除', value: '删除' },
  { label: '审核', value: '审核' },
  { label: '导出', value: '导出' },
  { label: '打印', value: '打印' },
  { label: '登录', value: '登录' },
  { label: '登录失败', value: '登录失败' },
  { label: '退出登录', value: '退出登录' },
  { label: '执行', value: '执行' },
  { label: '保存', value: '保存' },
  { label: '修改密码', value: '修改密码' },
  { label: '生成2FA密钥', value: '生成2FA密钥' },
  { label: '启用2FA', value: '启用2FA' },
  { label: '禁用2FA', value: '禁用2FA' },
  { label: '编辑权限', value: '编辑权限' },
  { label: '生成 API Key', value: '生成 API Key' },
  { label: '禁用 API Key', value: '禁用 API Key' },
  { label: '轮转JWT主密钥', value: '轮转JWT主密钥' },
  { label: '轮转2FA主密钥', value: '轮转2FA主密钥' },
  { label: '导出备份', value: '导出备份' },
  { label: '导入备份', value: '导入备份' },
  { label: '编辑上传命名规则', value: '编辑上传命名规则' },
  { label: '上传附件', value: '上传附件' },
]

const operationLogActionOptionsByModule: Record<string, ReadonlyArray<{ label: string; value: string }>> = {
  '认证授权': [
    { label: '登录', value: '登录' },
    { label: '登录失败', value: '登录失败' },
    { label: '退出登录', value: '退出登录' },
  ],
  '个人设置': [
    { label: '修改密码', value: '修改密码' },
    { label: '生成2FA密钥', value: '生成2FA密钥' },
    { label: '启用2FA', value: '启用2FA' },
    { label: '禁用2FA', value: '禁用2FA' },
  ],
  '用户账户': [
    { label: '新增', value: '新增' },
    { label: '编辑', value: '编辑' },
    { label: '删除', value: '删除' },
    { label: '生成2FA密钥', value: '生成2FA密钥' },
    { label: '启用2FA', value: '启用2FA' },
    { label: '禁用2FA', value: '禁用2FA' },
  ],
  '角色权限配置': [
    { label: '新增', value: '新增' },
    { label: '编辑', value: '编辑' },
    { label: '删除', value: '删除' },
    { label: '编辑权限', value: '编辑权限' },
  ],
  '角色设置': [
    { label: '新增', value: '新增' },
    { label: '编辑', value: '编辑' },
    { label: '删除', value: '删除' },
    { label: '编辑权限', value: '编辑权限' },
  ],
  'API Key 管理': [
    { label: '生成 API Key', value: '生成 API Key' },
    { label: '禁用 API Key', value: '禁用 API Key' },
  ],
  '安全密钥管理': [
    { label: '轮转JWT主密钥', value: '轮转JWT主密钥' },
    { label: '轮转2FA主密钥', value: '轮转2FA主密钥' },
  ],
  '数据库管理': [
    { label: '导出备份', value: '导出备份' },
    { label: '导入备份', value: '导入备份' },
  ],
  '公司信息': [
    { label: '保存', value: '保存' },
  ],
  '单号规则': [
    { label: '编辑上传命名规则', value: '编辑上传命名规则' },
  ],
  '附件管理': [
    { label: '上传附件', value: '上传附件' },
  ],
}

function resolveOperationLogActionOptions(filters: Record<string, unknown>) {
  const moduleName = String(filters.moduleName || '').trim()
  return [...(operationLogActionOptionsByModule[moduleName] || operationLogActionOptions)]
}

const operationLogModuleOptions = [
  {
    label: '常用',
    options: [
      { label: '认证授权', value: '认证授权' },
      { label: '用户账户', value: '用户账户' },
      { label: '角色权限配置', value: '角色权限配置' },
      { label: '通用设置', value: '通用设置' },
      { label: 'API Key 管理', value: 'API Key 管理' },
      { label: '数据库管理', value: '数据库管理' },
    ],
  },
  {
    label: '系统',
    options: [
      { label: '公司信息', value: '公司信息' },
      { label: '权限管理', value: '权限管理' },
      { label: '角色权限配置', value: '角色权限配置' },
      { label: '打印模板', value: '打印模板' },
      { label: '操作日志', value: '操作日志' },
      { label: '会话管理', value: '会话管理' },
      { label: '安全密钥管理', value: '安全密钥管理' },
    ],
  },
  {
    label: '业务',
    options: [
      { label: '商品资料', value: '商品资料' },
      { label: '供应商', value: '供应商' },
      { label: '客户', value: '客户' },
      { label: '物流商', value: '物流商' },
      { label: '仓库', value: '仓库' },
      { label: '采购订单', value: '采购订单' },
      { label: '采购入库', value: '采购入库' },
      { label: '销售订单', value: '销售订单' },
      { label: '销售出库', value: '销售出库' },
      { label: '物流单', value: '物流单' },
      { label: '采购合同', value: '采购合同' },
      { label: '销售合同', value: '销售合同' },
      { label: '供应商对账单', value: '供应商对账单' },
      { label: '客户对账单', value: '客户对账单' },
      { label: '物流对账单', value: '物流对账单' },
      { label: '收款单', value: '收款单' },
      { label: '付款单', value: '付款单' },
      { label: '收票单', value: '收票单' },
      { label: '开票单', value: '开票单' },
      { label: '未收票报表', value: '未收票报表' },
      { label: '出入库报表', value: '出入库报表' },
      { label: '库存报表', value: '库存报表' },
    ],
  },
]

export const systemPageConfigs: Record<string, ModulePageConfig> = {
  'general-settings': {
    key: 'general-settings',
    title: '通用设置',
    kicker: 'System',
    description: '通用设置集中维护默认税率和系统开关，用于控制页面行为、草稿默认值和附件命名策略。',
    actions: [...actionSet],
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '配置编码 / 单据名称 / 前缀' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    columns: [
      { title: '配置编码', dataIndex: 'settingCode', width: 150 },
      { title: '配置名称', dataIndex: 'settingName', width: 180 },
      { title: '单据名称', dataIndex: 'billName', width: 140 },
      { title: '前缀', dataIndex: 'prefix', width: 90 },
      { title: '日期规则', dataIndex: 'dateRule', width: 120 },
      { title: '流水位数', dataIndex: 'serialLength', width: 100, align: 'right', type: 'count' },
      { title: '重置规则', dataIndex: 'resetRule', width: 110 },
      { title: '示例号 / 配置值', dataIndex: 'sampleNo', width: 170 },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 220 },
    ],
    detailFields: [
      { label: '配置编码', key: 'settingCode' },
      { label: '配置名称', key: 'settingName' },
      { label: '单据名称', key: 'billName' },
      { label: '前缀', key: 'prefix' },
      { label: '日期规则', key: 'dateRule' },
      { label: '流水位数', key: 'serialLength', type: 'count' },
      { label: '重置规则', key: 'resetRule' },
      { label: '示例号 / 配置值', key: 'sampleNo' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'settingCode', label: '配置编码', type: 'input', required: true },
      { key: 'settingName', label: '配置名称', type: 'input', required: true },
      { key: 'billName', label: '单据名称', type: 'input', required: true },
      { key: 'prefix', label: '前缀', type: 'input', required: true },
      { key: 'dateRule', label: '日期规则', type: 'select', required: true, options: [
        { label: 'YYYY', value: 'YYYY' },
        { label: 'YYYYMM', value: 'YYYYMM' },
      ] },
      { key: 'serialLength', label: '流水位数', type: 'number', required: true, min: 1, precision: 0, defaultValue: 6 },
      { key: 'resetRule', label: '重置规则', type: 'select', required: true, options: [
        { label: '按年重置', value: '按年重置' },
        { label: '按月重置', value: '按月重置' },
        { label: '永不重置', value: '永不重置' },
      ] },
      { key: 'sampleNo', label: '示例号 / 配置值', type: 'input', required: true, placeholder: '单号规则为示例; 系统开关为当前值' },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: enabledStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '规则数', value: formatInteger(rows.length) },
      { label: '启用规则', value: formatInteger(rows.filter((row) => row.status === '正常').length) },
    ],
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  'company-settings': {
    key: 'company-settings',
    title: '公司信息',
    kicker: 'System',
    description: '公司信息集中维护公司名称、税号与多个结算银行信息，供打印模板、结算抬头和财务页面统一引用。',
    primaryNoKey: 'companyName',
    actions: [...actionSet],
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '公司名称 / 税号 / 银行 / 账号' },
    ],
    columns: [
      { title: '公司名称', dataIndex: 'companyName', width: 180 },
      { title: '税号', dataIndex: 'taxNo', width: 180 },
      { title: '备注', dataIndex: 'remark', width: 220 },
    ],
    detailFields: [
      { label: '公司名称', key: 'companyName' },
      { label: '税号', key: 'taxNo' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'companyName', label: '公司名称', type: 'input', required: true },
      { key: 'taxNo', label: '税号', type: 'input', required: true },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
  },
  'operation-logs': {
    key: 'operation-logs',
    title: '操作日志',
    kicker: 'System',
    description: '操作日志用于审计整个系统的写操作，记录操作人、模块、动作、对象、请求路径和结果状态，便于问题追踪与合规检查。',
    readOnly: true,
    actions: [{ label: '导出', type: 'primary' }],
    quickFilters: [
      { key: 'all', label: '全部日志', values: {} },
      { key: 'auth', label: '认证授权', values: { moduleName: '认证授权' } },
    ],
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '日志编号 / 操作人 / 业务单号 / 请求路径' },
      { key: 'moduleName', label: '模块', type: 'select', options: operationLogModuleOptions },
      { key: 'actionType', label: '动作', type: 'select', options: resolveOperationLogActionOptions },
      { key: 'resultStatus', label: '结果', type: 'select', options: [
        { label: '成功', value: '成功' },
        { label: '失败', value: '失败' },
      ] },
      { key: 'operationTime', label: '操作时间', type: 'dateRange' },
    ],
    columns: [
      { title: '日志编号', dataIndex: 'logNo', width: 160 },
      { title: '操作人', dataIndex: 'operatorName', width: 120 },
      { title: '登录账号', dataIndex: 'loginName', width: 130 },
      { title: '模块', dataIndex: 'moduleName', width: 120 },
      { title: '动作', dataIndex: 'actionType', width: 100 },
      { title: '业务单号', dataIndex: 'businessNo', width: 180 },
      { title: '请求方式', dataIndex: 'requestMethod', width: 100 },
      { title: '请求路径', dataIndex: 'requestPath', width: 220 },
      { title: '客户端IP', dataIndex: 'clientIp', width: 130 },
      { title: '结果', dataIndex: 'resultStatus', width: 90, type: 'status', align: 'center' },
      { title: '操作时间', dataIndex: 'operationTime', width: 170 },
      { title: '备注', dataIndex: 'remark', width: 240 },
    ],
    detailFields: [
      { label: '日志编号', key: 'logNo' },
      { label: '操作人', key: 'operatorName' },
      { label: '登录账号', key: 'loginName' },
      { label: '模块', key: 'moduleName' },
      { label: '动作', key: 'actionType' },
      { label: '业务单号', key: 'businessNo' },
      { label: '请求方式', key: 'requestMethod' },
      { label: '请求路径', key: 'requestPath' },
      { label: '客户端IP', key: 'clientIp' },
      { label: '结果', key: 'resultStatus', type: 'status' },
      { label: '操作时间', key: 'operationTime' },
      { label: '备注', key: 'remark' },
    ],
    data: [],
    buildOverview: (rows) => [
      { label: '日志数', value: formatInteger(rows.length) },
      { label: '成功数', value: formatInteger(rows.filter((row) => row.resultStatus === '成功').length) },
      { label: '失败数', value: formatInteger(rows.filter((row) => row.resultStatus === '失败').length) },
    ],
    statusMap,
    rowHighlightStatuses: ['失败'],
  },
  'permission-management': {
    key: 'permission-management',
    title: '权限管理',
    kicker: 'System',
    description: '权限管理页面展示系统菜单和操作权限定义，权限分配请通过「角色权限配置」页面操作。',
    readOnly: true,
    actions: [{ label: '导出', type: 'primary' }],
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '权限编码 / 名称 / 模块' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    columns: [
      { title: '权限编码', dataIndex: 'permissionCode', width: 150 },
      { title: '权限名称', dataIndex: 'permissionName', width: 180 },
      { title: '模块', dataIndex: 'moduleName', width: 140 },
      { title: '权限类型', dataIndex: 'permissionType', width: 110 },
      { title: '动作', dataIndex: 'actionName', width: 120 },
      { title: '数据范围', dataIndex: 'scopeName', width: 120 },
      { title: '资源标识', dataIndex: 'resourceKey', width: 180 },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 220 },
    ],
    detailFields: [
      { label: '权限编码', key: 'permissionCode' },
      { label: '权限名称', key: 'permissionName' },
      { label: '模块', key: 'moduleName' },
      { label: '权限类型', key: 'permissionType' },
      { label: '动作', key: 'actionName' },
      { label: '数据范围', key: 'scopeName' },
      { label: '资源标识', key: 'resourceKey' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'permissionCode', label: '权限编码', type: 'input', required: true },
      { key: 'permissionName', label: '权限名称', type: 'input', required: true },
      { key: 'moduleName', label: '模块', type: 'input', required: true },
      { key: 'permissionType', label: '权限类型', type: 'select', required: true, options: [
        { label: '菜单权限', value: '菜单权限' },
        { label: '按钮权限', value: '按钮权限' },
        { label: '数据权限', value: '数据权限' },
      ] },
      { key: 'actionName', label: '动作', type: 'select', required: true, options: [
        { label: '查看', value: '查看' },
        { label: '新增', value: '新增' },
        { label: '编辑', value: '编辑' },
        { label: '删除', value: '删除' },
        { label: '审核', value: '审核' },
        { label: '导出', value: '导出' },
        { label: '打印', value: '打印' },
      ] },
      { key: 'scopeName', label: '数据范围', type: 'select', required: true, options: [
        ...userAccountDataScopeOptions,
        { label: '自定义范围', value: '自定义范围' },
      ] },
      { key: 'resourceKey', label: '资源标识', type: 'input', required: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: enabledStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  departments: {
    key: 'departments',
    title: '部门管理',
    kicker: 'System',
    description: '部门管理维护组织部门、负责人、联系电话和启用状态，为用户账户的数据范围控制提供基础归属。',
    primaryNoKey: 'departmentCode',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '部门编码 / 部门名称 / 负责人' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    columns: [
      { title: '部门编码', dataIndex: 'departmentCode', width: 140 },
      { title: '部门名称', dataIndex: 'departmentName', width: 160 },
      { title: '上级部门', dataIndex: 'parentName', width: 150 },
      { title: '负责人', dataIndex: 'managerName', width: 120 },
      { title: '联系电话', dataIndex: 'contactPhone', width: 140 },
      { title: '排序号', dataIndex: 'sortOrder', width: 90, align: 'right', type: 'count' },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 220 },
    ],
    detailFields: [
      { label: '部门编码', key: 'departmentCode' },
      { label: '部门名称', key: 'departmentName' },
      { label: '上级部门', key: 'parentName' },
      { label: '负责人', key: 'managerName' },
      { label: '联系电话', key: 'contactPhone' },
      { label: '排序号', key: 'sortOrder', type: 'count' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'departmentCode', label: '部门编码', type: 'input', required: true },
      { key: 'departmentName', label: '部门名称', type: 'input', required: true },
      { key: 'parentId', label: '上级部门', type: 'select', allowClear: true, placeholder: '请选择上级部门' },
      { key: 'managerName', label: '负责人', type: 'input' },
      { key: 'contactPhone', label: '联系电话', type: 'input' },
      { key: 'sortOrder', label: '排序号', type: 'number', min: 0, precision: 0, defaultValue: 0 },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: enabledStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  'user-accounts': {
    key: 'user-accounts',
    title: '用户账户',
    kicker: 'System',
    description: '用户账户页面维护登录账号、角色、联系方式和启用状态，供后续权限和审计链路复用。',
    actions: actionSet,
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '登录账号 / 用户姓名 / 手机号' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    columns: [
      { title: '登录账号', dataIndex: 'loginName', width: 140 },
      { title: '用户姓名', dataIndex: 'userName', width: 140 },
      { title: '所属部门', dataIndex: 'departmentName', width: 140 },
      { title: '手机号', dataIndex: 'mobile', width: 140 },
      { title: '所属角色', dataIndex: 'roleNames', width: 220 },
      { title: '数据范围', dataIndex: 'dataScope', width: 120 },
      { title: '权限摘要', dataIndex: 'permissionSummary', width: 220 },
      { title: '最近登录', dataIndex: 'lastLoginDate', width: 120, type: 'date' },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
    ],
    detailFields: [
      { label: '登录账号', key: 'loginName' },
      { label: '用户姓名', key: 'userName' },
      { label: '所属部门', key: 'departmentName' },
      { label: '手机号', key: 'mobile' },
      { label: '所属角色', key: 'roleNames' },
      { label: '数据范围', key: 'dataScope' },
      { label: '权限摘要', key: 'permissionSummary' },
      { label: '最近登录', key: 'lastLoginDate', type: 'date' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'loginName', label: '登录账号', type: 'input', required: true },
      { key: 'password', label: '初始密码', type: 'input' },
      { key: 'userName', label: '用户姓名', type: 'input', required: true },
      { key: 'mobile', label: '手机号', type: 'input', required: true },
      { key: 'departmentId', label: '所属部门ID', type: 'number', min: 0, precision: 0 },
      { key: 'roleNames', label: '所属角色', type: 'multiSelect', required: true },
      { key: 'dataScope', label: '数据范围', type: 'select', required: true, options: userAccountDataScopeOptions },
      { key: 'permissionSummary', label: '权限摘要', type: 'textarea', disabled: true },
      { key: 'lastLoginDate', label: '最近登录', type: 'date', disabled: true },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: enabledStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
  'role-settings': {
    key: 'role-settings',
    title: '角色权限配置',
    kicker: 'System',
    description: '角色权限配置统一维护角色资料、数据范围和权限矩阵，方便角色维护与授权配置在同一处完成。',
    actions: [
      { label: '新增', type: 'primary' as const },
      { label: '配置权限', type: 'default' as const },
      { label: '导出', type: 'default' as const },
    ],
    filters: [
      { key: 'keyword', label: '关键字', type: 'input', placeholder: '角色编码 / 角色名称 / 角色类型' },
      { key: 'status', label: '状态', type: 'select', options: enabledStatusOptions },
    ],
    columns: [
      { title: '角色编码', dataIndex: 'roleCode', width: 140 },
      { title: '角色名称', dataIndex: 'roleName', width: 160 },
      { title: '角色类型', dataIndex: 'roleType', width: 120 },
      { title: '数据范围', dataIndex: 'dataScope', width: 120 },
      { title: '权限项', dataIndex: 'permissionCount', width: 90, align: 'right', type: 'count' },
      { title: '权限摘要', dataIndex: 'permissionSummary', width: 240 },
      { title: '绑定人数', dataIndex: 'userCount', width: 100, align: 'right', type: 'count' },
      { title: '状态', dataIndex: 'status', width: 100, type: 'status', align: 'center' },
      { title: '备注', dataIndex: 'remark', width: 220 },
    ],
    detailFields: [
      { label: '角色编码', key: 'roleCode' },
      { label: '角色名称', key: 'roleName' },
      { label: '角色类型', key: 'roleType' },
      { label: '数据范围', key: 'dataScope' },
      { label: '权限项', key: 'permissionCount', type: 'count' },
      { label: '权限摘要', key: 'permissionSummary' },
      { label: '绑定人数', key: 'userCount', type: 'count' },
      { label: '状态', key: 'status', type: 'status' },
      { label: '备注', key: 'remark' },
    ],
    formFields: [
      { key: 'roleCode', label: '角色编码', type: 'input', required: true },
      { key: 'roleName', label: '角色名称', type: 'input', required: true },
      { key: 'roleType', label: '角色类型', type: 'select', required: true, options: roleTypeOptions },
      { key: 'dataScope', label: '数据范围', type: 'select', required: true, options: roleDataScopeOptions },
      { key: 'permissionCodes', label: '绑定权限', type: 'textarea', disabled: true, placeholder: '请通过「角色权限配置」页面设置' },
      { key: 'permissionSummary', label: '权限摘要', type: 'textarea', disabled: true },
      { key: 'userCount', label: '绑定人数', type: 'number', required: true, min: 0, precision: 0, defaultValue: 0 },
      { key: 'status', label: '状态', type: 'select', defaultValue: '正常', options: enabledStatusOptions },
      { key: 'remark', label: '备注', type: 'textarea' },
    ],
    data: [],
    buildOverview: (rows) => buildMasterOverview(rows),
    statusMap,
    rowHighlightStatuses: ['禁用'],
  },
}
